In [1]:
import pandas as pd

In [2]:
TRX=pd.read_excel("../../../Tron/0 day lag individual.xlsx")
TRX['Date'] = pd.to_datetime(TRX['Date'])
TRX.set_index('Date', inplace=True)

In [3]:
TRX

,Gold_Price,Oil_Price,Nasdaq_Change,Nasdaq_Volume,S&P500_Change,S&P500_Volume,BTC_Change,BTC_Volume,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Tron_Change
Date,,,,,,,,,,,,
2017-10-01,1284.8,51.67,1,1970720000,1,3220260000,0,1.177333e+09,20852,0.110879,0.255300,0
2017-10-02,1275.8,50.58,1,1984400000,1,3226370000,1,1.146607e+09,28365,0.103813,-0.031300,1
2017-10-03,1274.6,50.42,1,1972760000,1,3073480000,1,9.741398e+08,26464,0.076525,0.000000,0
2017-10-04,1276.8,49.98,1,1941470000,1,3020770000,1,9.920291e+08,28277,0.100994,-0.047070,1
2017-10-05,1273.2,50.79,1,1888970000,1,3059730000,1,9.624500e+08,26405,0.118650,-0.148610,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-27,1797.7,75.89,0,3827290000,0,3030300000,0,1.574858e+10,39816,0.097602,-0.054126,0
2022-12-28,1797.7,75.89,0,3842970000,0,3083520000,0,1.700571e+10,42534,0.084050,-0.066367,1
2022-12-29,1797.7,75.89,1,4154100000,1,3003680000,1,1.447224e+10,41316,0.099584,-0.052279,0
2022-12-30,1797.7,75.89,1,3959030000,1,2979870000,0,1.592916e+10,40485,0.095240,-0.024360,1
2022-12-31,1797.7,75.89,1,3959030000,1,2979870000,0,1.123919e+10,35625,0.119512,-0.068864,1

In [5]:
# btc market cap missing
# List of columns to convert
columns_to_convert = ['Gold_Price', 'Oil_Price','BTC_Volume','Tweets_Count','Tweets_Vader_Sentiment','News_Vader_Sentiment']

# Applying the transformation
for column in columns_to_convert:
    TRX[column + '_binary'] = (TRX[column] > TRX[column].shift(1)).astype(int)

In [6]:
TRX.drop(["Nasdaq_Volume",'Gold_Price', 'Oil_Price','S&P500_Volume'],inplace=True,axis=1)

In [7]:
TRX

,Nasdaq_Change,S&P500_Change,BTC_Change,BTC_Volume,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Tron_Change,Gold_Price_binary,Oil_Price_binary,BTC_Volume_binary,Tweets_Count_binary,Tweets_Vader_Sentiment_binary,News_Vader_Sentiment_binary
Date,,,,,,,,,,,,,,
2017-10-01,1,1,0,1.177333e+09,20852,0.110879,0.255300,0,0,0,0,0,0,0
2017-10-02,1,1,1,1.146607e+09,28365,0.103813,-0.031300,1,0,0,0,1,0,0
2017-10-03,1,1,1,9.741398e+08,26464,0.076525,0.000000,0,0,0,0,0,0,1
2017-10-04,1,1,1,9.920291e+08,28277,0.100994,-0.047070,1,1,0,1,1,1,0
2017-10-05,1,1,1,9.624500e+08,26405,0.118650,-0.148610,1,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-27,0,0,0,1.574858e+10,39816,0.097602,-0.054126,0,0,0,1,1,1,0
2022-12-28,0,0,0,1.700571e+10,42534,0.084050,-0.066367,1,0,0,1,1,0,0
2022-12-29,1,1,1,1.447224e+10,41316,0.099584,-0.052279,0,0,0,0,0,1,1
2022-12-30,1,1,0,1.592916e+10,40485,0.095240,-0.024360,1,0,0,1,0,0,1
2022-12-31,1,1,0,1.123919e+10,35625,0.119512,-0.068864,1,0,0,0,0,1,0

In [8]:
columns_to_lag = ['Tron_Change'] #'Gold_Price_binary','Oil_Price_binary','Tweets_Count_binary','Tweets_Vader_Sentiment_binary','News_Vader_Sentiment_binary'

# Number of lags (days back) to create
number_of_lags = 5

# Create lag features for the selected columns
for column in columns_to_lag:
    for lag in range(1, number_of_lags + 1):
        TRX[f'{column}_lag_{lag}'] = TRX[column].shift(lag)

# Optionally, remove any rows with NaN values that were created due to shifting
TRX.dropna(inplace=True)

In [9]:
TRX

,Nasdaq_Change,S&P500_Change,BTC_Change,BTC_Volume,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Tron_Change,Gold_Price_binary,Oil_Price_binary,BTC_Volume_binary,Tweets_Count_binary,Tweets_Vader_Sentiment_binary,News_Vader_Sentiment_binary,Tron_Change_lag_1,Tron_Change_lag_2,Tron_Change_lag_3,Tron_Change_lag_4,Tron_Change_lag_5
Date,,,,,,,,,,,,,,,,,,,
2017-10-06,1,1,1,7.810308e+08,25712,0.095004,-0.148610,0,1,0,0,0,0,0,1.0,1.0,0.0,1.0,0.0
2017-10-07,1,1,0,9.193761e+08,17848,0.075911,-0.148610,0,0,0,1,0,0,0,0.0,1.0,1.0,0.0,1.0
2017-10-08,1,1,1,1.437590e+09,18663,0.041593,0.000000,0,0,0,1,1,0,1,0.0,0.0,1.0,1.0,0.0
2017-10-09,0,0,1,1.844580e+09,27314,0.084234,0.080380,0,1,1,1,1,1,1,0.0,0.0,0.0,1.0,1.0
2017-10-10,0,1,1,1.376093e+09,27988,0.080740,-0.078155,1,1,1,0,1,0,0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-27,0,0,0,1.574858e+10,39816,0.097602,-0.054126,0,0,0,1,1,1,0,0.0,1.0,1.0,0.0,1.0
2022-12-28,0,0,0,1.700571e+10,42534,0.084050,-0.066367,1,0,0,1,1,0,0,0.0,0.0,1.0,1.0,0.0
2022-12-29,1,1,1,1.447224e+10,41316,0.099584,-0.052279,0,0,0,0,0,1,1,1.0,0.0,0.0,1.0,1.0
2022-12-30,1,1,0,1.592916e+10,40485,0.095240,-0.024360,1,0,0,1,0,0,1,0.0,1.0,0.0,0.0,1.0
2022-12-31,1,1,0,1.123919e+10,35625,0.119512,-0.068864,1,0,0,0,0,1,0,1.0,0.0,1.0,0.0,0.0

In [11]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Selecting the columns to standardize
features = TRX[['BTC_Volume', 'Tweets_Count', 'Tweets_Vader_Sentiment', 'News_Vader_Sentiment']]

# Initialize the StandardScaler
scaler = StandardScaler()

# Standardize the features
features_scaled = scaler.fit_transform(features)

# Replace the original columns with the scaled columns
TRX[['BTC_Volume', 'Tweets_Count', 'Tweets_Vader_Sentiment', 'News_Vader_Sentiment']] = features_scaled

In [12]:
TRX

,Nasdaq_Change,S&P500_Change,BTC_Change,BTC_Volume,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Tron_Change,Gold_Price_binary,Oil_Price_binary,BTC_Volume_binary,Tweets_Count_binary,Tweets_Vader_Sentiment_binary,News_Vader_Sentiment_binary,Tron_Change_lag_1,Tron_Change_lag_2,Tron_Change_lag_3,Tron_Change_lag_4,Tron_Change_lag_5
Date,,,,,,,,,,,,,,,,,,,
2017-10-06,1,1,1,-1.059972,-0.553737,-1.344478,-1.549435,0,1,0,0,0,0,0,1.0,1.0,0.0,1.0,0.0
2017-10-07,1,1,0,-1.056185,-0.996854,-1.774782,-1.549435,0,0,0,1,0,0,0,0.0,1.0,1.0,0.0,1.0
2017-10-08,1,1,1,-1.041996,-0.950931,-2.548240,-0.198639,0,0,0,1,1,0,1,0.0,0.0,1.0,1.0,0.0
2017-10-09,0,0,1,-1.030853,-0.463469,-1.587198,0.531977,0,1,1,1,1,1,1,0.0,0.0,0.0,1.0,1.0
2017-10-10,0,1,1,-1.043680,-0.425490,-1.665948,-0.909028,1,1,1,0,1,0,0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-27,0,0,0,-0.650175,0.240988,-1.285909,-0.690615,0,0,0,1,1,1,0,0.0,1.0,1.0,0.0,1.0
2022-12-28,0,0,0,-0.615756,0.394141,-1.591353,-0.801881,1,0,0,1,1,0,0,0.0,0.0,1.0,1.0,0.0
2022-12-29,1,1,1,-0.685120,0.325510,-1.241241,-0.673828,0,0,0,0,0,1,1,1.0,0.0,0.0,1.0,1.0
2022-12-30,1,1,0,-0.645231,0.278685,-1.339143,-0.420060,1,0,0,1,0,0,1,0.0,1.0,0.0,0.0,1.0
2022-12-31,1,1,0,-0.773638,0.004836,-0.792101,-0.824579,1,0,0,0,0,1,0,1.0,0.0,1.0,0.0,0.0

In [14]:
TRX_market= pd.read_excel("../../Base_Datasets/Alt_Coin_Yearly_Rank.xlsx", sheet_name = 'TRON_Daily')
TRX_market['Date'] = pd.to_datetime(TRX_market['Date'])
TRX_market.set_index('Date', inplace=True)

In [15]:
TRX_market.tail(10)

                Open*       High        Low    Close**    Volume Market Cap
Date
2017-09-22  $0.002079  $0.002172  $0.001852  $0.001951   $38,829         $0
2017-09-21  $0.002638  $0.003173  $0.001935  $0.002079   $99,853         $0
2017-09-20  $0.002306  $0.003199  $0.002039  $0.002647   $83,399         $0
2017-09-19  $0.003273   $0.02324  $0.001746  $0.002291  $158,416         $0
2017-09-18  $0.003324  $0.003438  $0.002534  $0.003263  $159,158         $0
2017-09-17  $0.001836  $0.003879  $0.001781   $0.00332  $124,998         $0
2017-09-16  $0.001815   $0.01767  $0.001371  $0.001831   $54,535         $0
2017-09-15  $0.001419  $0.001831  $0.001091  $0.001801   $26,475         $0
2017-09-14  $0.002006  $0.002479  $0.001298  $0.001427   $58,770         $0
2017-09-13  $0.002051  $0.002447  $0.001711  $0.001988   $48,512         $0

In [16]:
TRX_market

,Open*,High,Low,Close**,Volume,Market Cap
Date,,,,,,
2023-01-10,$0.05462,$0.0549,$0.05401,$0.05478,"$196,148,451","$5,035,251,212"
2023-01-09,$0.0539,$0.05637,$0.05379,$0.05463,"$374,224,118","$5,021,223,279"
2023-01-08,$0.05201,$0.05382,$0.05139,$0.05382,"$202,055,018","$4,947,138,156"
2023-01-07,$0.05249,$0.05281,$0.05149,$0.05202,"$277,255,900","$4,782,224,349"
2023-01-06,$0.05367,$0.05389,$0.05007,$0.05249,"$769,019,622","$4,826,038,337"
...,...,...,...,...,...,...
2017-09-17,$0.001836,$0.003879,$0.001781,$0.00332,"$124,998",$0
2017-09-16,$0.001815,$0.01767,$0.001371,$0.001831,"$54,535",$0
2017-09-15,$0.001419,$0.001831,$0.001091,$0.001801,"$26,475",$0
2017-09-14,$0.002006,$0.002479,$0.001298,$0.001427,"$58,770",$0
2017-09-13,$0.002051,$0.002447,$0.001711,$0.001988,"$48,512",$0

In [17]:
# Convert columns to float, removing any non-numeric characters like commas
TRX_market['Open*'] = pd.to_numeric(TRX_market['Open*'].replace('[^\d.]', '', regex=True), errors='coerce')
TRX_market['High'] = pd.to_numeric(TRX_market['High'].replace('[^\d.]', '', regex=True), errors='coerce')
TRX_market['Low'] = pd.to_numeric(TRX_market['Low'].replace('[^\d.]', '', regex=True), errors='coerce')
TRX_market['Close**'] = pd.to_numeric(TRX_market['Close**'].replace('[^\d.]', '', regex=True), errors='coerce')
TRX_market['Volume'] = pd.to_numeric(TRX_market['Volume'].replace('[^\d.]', '', regex=True), errors='coerce')
TRX_market['Market Cap'] = pd.to_numeric(TRX_market['Market Cap'].replace('[^\d.]', '', regex=True), errors='coerce')

In [18]:
TRX_market

               Open*      High       Low   Close**     Volume  Market Cap
Date
2023-01-10  0.054620  0.054900  0.054010  0.054780  196148451  5035251212
2023-01-09  0.053900  0.056370  0.053790  0.054630  374224118  5021223279
2023-01-08  0.052010  0.053820  0.051390  0.053820  202055018  4947138156
2023-01-07  0.052490  0.052810  0.051490  0.052020  277255900  4782224349
2023-01-06  0.053670  0.053890  0.050070  0.052490  769019622  4826038337
...              ...       ...       ...       ...        ...         ...
2017-09-17  0.001836  0.003879  0.001781  0.003320     124998           0
2017-09-16  0.001815  0.017670  0.001371  0.001831      54535           0
2017-09-15  0.001419  0.001831  0.001091  0.001801      26475           0
2017-09-14  0.002006  0.002479  0.001298  0.001427      58770           0
2017-09-13  0.002051  0.002447  0.001711  0.001988      48512           0

[1946 rows x 6 columns]

In [19]:
from ta import add_all_ta_features
from ta.utils import dropna

# Clean NaN values
TRX_market = dropna(TRX_market)

# Add all technical indicators
TRX_market = add_all_ta_features(
    TRX_market, open="Open*", high="High", low="Low", close="Close**", volume="Volume", fillna=True
)

C:\Users\sdas1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\ta\trend.py:1030: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  self._psar[i] = high2

In [20]:
TRX_market

,Open*,High,Low,Close**,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,...,momentum_ppo,momentum_ppo_signal,momentum_ppo_hist,momentum_pvo,momentum_pvo_signal,momentum_pvo_hist,momentum_kama,others_dr,others_dlr,others_cr
Date,,,,,,,,,,,,,,,,,,,,,
2023-01-10,0.054620,0.054900,0.054010,0.054780,196148451,5.035251e+09,1.432545e+08,196148451,0.730337,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.054780,0.000000,0.000000,0.000000
2023-01-09,0.053900,0.056370,0.053790,0.054630,374224118,5.021223e+09,1.271119e+07,-178075667,0.022286,-56133.617700,...,-0.021848,-0.004370,-0.017478,6.785859,1.357172,5.428687,0.054714,-0.273823,-0.274198,-0.273823
2023-01-08,0.052010,0.053820,0.051390,0.053820,202055018,4.947138e+09,2.147662e+08,-380130685,0.278041,-71495.181540,...,-0.156896,-0.034875,-0.122021,5.478425,2.181422,3.297002,0.054348,-1.482702,-1.493804,-1.752464
2023-01-07,0.052490,0.052810,0.051490,0.052020,277255900,4.782224e+09,1.601552e+08,-657386585,0.152575,-132575.958463,...,-0.525309,-0.132962,-0.392347,7.079047,3.160947,3.918099,0.053504,-3.344482,-3.401689,-5.038335
2023-01-06,0.053670,0.053890,0.050070,0.052490,769019622,4.826038e+09,3.654955e+08,111633037,0.200965,-62002.361205,...,-0.740747,-0.254519,-0.486229,22.391297,7.007017,15.384280,0.053125,0.903499,0.899442,-4.180358
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-10-02,0.001848,0.003177,0.001768,0.002803,887622,1.121204e+08,1.019273e+11,959980896,0.052561,-12.853587,...,-2.505340,-7.817416,5.312076,-79.351503,-86.802093,7.450590,0.002608,14.548427,13.582749,-94.883169
2017-10-01,0.002261,0.002269,0.001806,0.001848,72807,1.860063e+07,1.019273e+11,959908089,0.015829,-20.950315,...,-4.826284,-7.219189,2.392906,-80.752396,-85.592153,4.839758,0.002588,-34.070639,-41.658630,-96.626506
2017-09-30,0.001983,0.002621,0.001763,0.002261,53734,2.275725e+07,1.019273e+11,959961823,0.036984,-14.787107,...,-5.368764,-6.849104,1.480340,-82.107753,-84.895273,2.787521,0.002586,22.348485,20.170322,-95.872581
2017-09-29,0.002901,0.002973,0.001487,0.001983,58162,1.996157e+07,1.019273e+11,959903661,0.073752,-14.984526,...,-6.651700,-6.809623,0.157924,-83.293507,-84.574920,1.281413,0.002581,-12.295444,-13.119634,-96.380066
2017-09-28,0.002563,0.003474,0.001816,0.002906,69532,2.925584e+07,1.019273e+11,959973193,0.051597,-3.675588,...,-4.619575,-6.371614,1.752039,-84.272045,-84.514345,0.242300,0.002585,46.545638,38.216672,-94.695144

In [21]:
from ta.momentum import RSIIndicator
from ta.trend import MACD
from ta.volatility import BollingerBands

# RSI
TRX_market['rsi'] = RSIIndicator(close=TRX_market['Close**'], window=14, fillna=True).rsi()

# MACD
macd = MACD(close=TRX_market['Close**'], window_slow=26, window_fast=12, window_sign=9, fillna=True)
TRX_market['macd'] = macd.macd()
TRX_market['macd_signal'] = macd.macd_signal()
TRX_market['macd_diff'] = macd.macd_diff()

# Bollinger Bands
indicator_bb = BollingerBands(close=TRX_market['Close**'], window=20, window_dev=2, fillna=True)
TRX_market['bb_bbm'] = indicator_bb.bollinger_mavg()
TRX_market['bb_bbh'] = indicator_bb.bollinger_hband()
TRX_market['bb_bbl'] = indicator_bb.bollinger_lband()

In [22]:
TRX_market

,Open*,High,Low,Close**,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,...,others_dr,others_dlr,others_cr,rsi,macd,macd_signal,macd_diff,bb_bbm,bb_bbh,bb_bbl
Date,,,,,,,,,,,,,,,,,,,,,
2023-01-10,0.054620,0.054900,0.054010,0.054780,196148451,5.035251e+09,1.432545e+08,196148451,0.730337,0.000000,...,0.000000,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,0.054780,0.054780,0.054780
2023-01-09,0.053900,0.056370,0.053790,0.054630,374224118,5.021223e+09,1.271119e+07,-178075667,0.022286,-56133.617700,...,-0.273823,-0.274198,-0.273823,0.000000,-0.000012,-0.000002,-0.000010,0.054705,0.054855,0.054555
2023-01-08,0.052010,0.053820,0.051390,0.053820,202055018,4.947138e+09,2.147662e+08,-380130685,0.278041,-71495.181540,...,-1.482702,-1.493804,-1.752464,0.000000,-0.000086,-0.000019,-0.000067,0.054410,0.055253,0.053567
2023-01-07,0.052490,0.052810,0.051490,0.052020,277255900,4.782224e+09,1.601552e+08,-657386585,0.152575,-132575.958463,...,-3.344482,-3.401689,-5.038335,0.000000,-0.000286,-0.000073,-0.000214,0.053812,0.056007,0.051618
2023-01-06,0.053670,0.053890,0.050070,0.052490,769019622,4.826038e+09,3.654955e+08,111633037,0.200965,-62002.361205,...,0.903499,0.899442,-4.180358,15.878672,-0.000403,-0.000139,-0.000264,0.053548,0.055778,0.051318
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-10-02,0.001848,0.003177,0.001768,0.002803,887622,1.121204e+08,1.019273e+11,959980896,0.052561,-12.853587,...,14.548427,13.582749,-94.883169,50.294311,-0.000069,-0.000219,0.000151,0.002408,0.003197,0.001620
2017-10-01,0.002261,0.002269,0.001806,0.001848,72807,1.860063e+07,1.019273e+11,959908089,0.015829,-20.950315,...,-34.070639,-41.658630,-96.626506,40.410072,-0.000129,-0.000201,0.000072,0.002386,0.003210,0.001562
2017-09-30,0.001983,0.002621,0.001763,0.002261,53734,2.275725e+07,1.019273e+11,959961823,0.036984,-14.787107,...,22.348485,20.170322,-95.872581,45.406890,-0.000142,-0.000189,0.000048,0.002402,0.003203,0.001601
2017-09-29,0.002901,0.002973,0.001487,0.001983,58162,1.996157e+07,1.019273e+11,959903661,0.073752,-14.984526,...,-12.295444,-13.119634,-96.380066,42.804968,-0.000172,-0.000186,0.000014,0.002405,0.003199,0.001612
2017-09-28,0.002563,0.003474,0.001816,0.002906,69532,2.925584e+07,1.019273e+11,959973193,0.051597,-3.675588,...,46.545638,38.216672,-94.695144,52.530787,-0.000121,-0.000173,0.000052,0.002446,0.003255,0.001637

In [23]:
# Shift all columns except 'Date'
columns_to_shift = TRX_market.columns.difference(['Date'])
TRX_market[columns_to_shift] = TRX_market[columns_to_shift].shift(-1)

TRX_market.dropna(inplace=True)

In [24]:
TRX_market

,Open*,High,Low,Close**,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,...,others_dr,others_dlr,others_cr,rsi,macd,macd_signal,macd_diff,bb_bbm,bb_bbh,bb_bbl
Date,,,,,,,,,,,,,,,,,,,,,
2023-01-10,0.053900,0.056370,0.053790,0.054630,374224118.0,5.021223e+09,1.271119e+07,-178075667.0,0.022286,-56133.617700,...,-0.273823,-0.274198,-0.273823,0.000000,-0.000012,-0.000002,-0.000010,0.054705,0.054855,0.054555
2023-01-09,0.052010,0.053820,0.051390,0.053820,202055018.0,4.947138e+09,2.147662e+08,-380130685.0,0.278041,-71495.181540,...,-1.482702,-1.493804,-1.752464,0.000000,-0.000086,-0.000019,-0.000067,0.054410,0.055253,0.053567
2023-01-08,0.052490,0.052810,0.051490,0.052020,277255900.0,4.782224e+09,1.601552e+08,-657386585.0,0.152575,-132575.958463,...,-3.344482,-3.401689,-5.038335,0.000000,-0.000286,-0.000073,-0.000214,0.053812,0.056007,0.051618
2023-01-07,0.053670,0.053890,0.050070,0.052490,769019622.0,4.826038e+09,3.654955e+08,111633037.0,0.200965,-62002.361205,...,0.903499,0.899442,-4.180358,15.878672,-0.000403,-0.000139,-0.000264,0.053548,0.055778,0.051318
2023-01-06,0.054730,0.054980,0.053460,0.053660,182910374.0,4.933684e+09,2.307194e+08,294543411.0,0.115267,-22572.718522,...,2.228996,2.204517,-2.044542,40.995792,-0.000396,-0.000190,-0.000206,0.053567,0.055604,0.051529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-10-03,0.001848,0.003177,0.001768,0.002803,887622.0,1.121204e+08,1.019273e+11,959980896.0,0.052561,-12.853587,...,14.548427,13.582749,-94.883169,50.294311,-0.000069,-0.000219,0.000151,0.002408,0.003197,0.001620
2017-10-02,0.002261,0.002269,0.001806,0.001848,72807.0,1.860063e+07,1.019273e+11,959908089.0,0.015829,-20.950315,...,-34.070639,-41.658630,-96.626506,40.410072,-0.000129,-0.000201,0.000072,0.002386,0.003210,0.001562
2017-10-01,0.001983,0.002621,0.001763,0.002261,53734.0,2.275725e+07,1.019273e+11,959961823.0,0.036984,-14.787107,...,22.348485,20.170322,-95.872581,45.406890,-0.000142,-0.000189,0.000048,0.002402,0.003203,0.001601
2017-09-30,0.002901,0.002973,0.001487,0.001983,58162.0,1.996157e+07,1.019273e+11,959903661.0,0.073752,-14.984526,...,-12.295444,-13.119634,-96.380066,42.804968,-0.000172,-0.000186,0.000014,0.002405,0.003199,0.001612
2017-09-29,0.002563,0.003474,0.001816,0.002906,69532.0,2.925584e+07,1.019273e+11,959973193.0,0.051597,-3.675588,...,46.545638,38.216672,-94.695144,52.530787,-0.000121,-0.000173,0.000052,0.002446,0.003255,0.001637

In [25]:
Tron_final_dataset=TRX_market.join(TRX,how='inner')

In [26]:
Tron_final_dataset

,Open*,High,Low,Close**,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,...,Oil_Price_binary,BTC_Volume_binary,Tweets_Count_binary,Tweets_Vader_Sentiment_binary,News_Vader_Sentiment_binary,Tron_Change_lag_1,Tron_Change_lag_2,Tron_Change_lag_3,Tron_Change_lag_4,Tron_Change_lag_5
Date,,,,,,,,,,,,,,,,,,,,,
2022-12-31,0.054010,0.054440,0.053650,0.054370,160347943.0,5.000631e+09,1.961172e+08,351978039.0,0.069115,-2900.618287,...,0,0,0,1,0,1.0,0.0,1.0,0.0,0.0
2022-12-30,0.054150,0.054460,0.053330,0.054010,159780714.0,4.967752e+09,2.286389e+08,192197325.0,0.076281,-10703.538109,...,0,1,0,0,1,0.0,1.0,0.0,0.0,1.0
2022-12-29,0.054100,0.054600,0.053370,0.054150,165230958.0,4.980109e+09,2.729692e+08,357428283.0,0.086312,-5869.842077,...,0,0,0,1,1,1.0,0.0,0.0,1.0,1.0
2022-12-28,0.054550,0.054690,0.053780,0.054110,146077041.0,4.976782e+09,2.328381e+08,211351242.0,0.070373,-5866.019157,...,0,1,1,0,0,0.0,0.0,1.0,1.0,0.0
2022-12-27,0.054820,0.055000,0.054350,0.054550,116647160.0,5.018012e+09,1.879739e+08,327998402.0,0.054878,2304.090780,...,0,1,1,1,0,0.0,1.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-10-10,0.002567,0.002719,0.001943,0.002181,350960.0,1.420210e+08,1.019269e+11,959918568.0,0.154379,-37.343841,...,1,0,1,0,0,0.0,0.0,0.0,0.0,1.0
2017-10-09,0.002565,0.002854,0.002326,0.002530,239490.0,1.647396e+08,1.019268e+11,960158058.0,0.123704,-20.068719,...,1,1,1,1,1,0.0,0.0,0.0,1.0,1.0
2017-10-08,0.002995,0.004173,0.002240,0.002459,352974.0,1.601321e+08,1.019266e+11,959805084.0,0.031300,-20.781924,...,0,1,1,0,1,0.0,0.0,1.0,1.0,0.0
2017-10-07,0.003321,0.003354,0.002815,0.002996,478330.0,1.198216e+08,1.019264e+11,960283414.0,-0.012252,18.881667,...,0,1,0,0,0,0.0,1.0,1.0,0.0,1.0
2017-10-06,0.003269,0.003488,0.002942,0.003320,704167.0,1.328088e+08,1.019267e+11,960987581.0,0.009438,48.777158,...,0,0,0,0,0,1.0,1.0,0.0,1.0,0.0

In [27]:
Tron_final_dataset.to_csv("Tron_final_dataset.csv")

In [28]:
import numpy as np
from pycaret.classification import *

# Initialize setup
clf = setup(data=Tron_final_dataset, target='Tron_Change', session_id=123)

In [29]:
best_model=compare_models()

In [30]:
TRX_market["Tron_Change"]=TRX["Tron_Change"]

In [31]:
TRX_market

,Open*,High,Low,Close**,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,...,others_dlr,others_cr,rsi,macd,macd_signal,macd_diff,bb_bbm,bb_bbh,bb_bbl,Tron_Change
Date,,,,,,,,,,,,,,,,,,,,,
2023-01-10,0.053900,0.056370,0.053790,0.054630,374224118.0,5.021223e+09,1.271119e+07,-178075667.0,0.022286,-56133.617700,...,-0.274198,-0.273823,0.000000,-0.000012,-0.000002,-0.000010,0.054705,0.054855,0.054555,NaN
2023-01-09,0.052010,0.053820,0.051390,0.053820,202055018.0,4.947138e+09,2.147662e+08,-380130685.0,0.278041,-71495.181540,...,-1.493804,-1.752464,0.000000,-0.000086,-0.000019,-0.000067,0.054410,0.055253,0.053567,NaN
2023-01-08,0.052490,0.052810,0.051490,0.052020,277255900.0,4.782224e+09,1.601552e+08,-657386585.0,0.152575,-132575.958463,...,-3.401689,-5.038335,0.000000,-0.000286,-0.000073,-0.000214,0.053812,0.056007,0.051618,NaN
2023-01-07,0.053670,0.053890,0.050070,0.052490,769019622.0,4.826038e+09,3.654955e+08,111633037.0,0.200965,-62002.361205,...,0.899442,-4.180358,15.878672,-0.000403,-0.000139,-0.000264,0.053548,0.055778,0.051318,NaN
2023-01-06,0.054730,0.054980,0.053460,0.053660,182910374.0,4.933684e+09,2.307194e+08,294543411.0,0.115267,-22572.718522,...,2.204517,-2.044542,40.995792,-0.000396,-0.000190,-0.000206,0.053567,0.055604,0.051529,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-10-03,0.001848,0.003177,0.001768,0.002803,887622.0,1.121204e+08,1.019273e+11,959980896.0,0.052561,-12.853587,...,13.582749,-94.883169,50.294311,-0.000069,-0.000219,0.000151,0.002408,0.003197,0.001620,NaN
2017-10-02,0.002261,0.002269,0.001806,0.001848,72807.0,1.860063e+07,1.019273e+11,959908089.0,0.015829,-20.950315,...,-41.658630,-96.626506,40.410072,-0.000129,-0.000201,0.000072,0.002386,0.003210,0.001562,NaN
2017-10-01,0.001983,0.002621,0.001763,0.002261,53734.0,2.275725e+07,1.019273e+11,959961823.0,0.036984,-14.787107,...,20.170322,-95.872581,45.406890,-0.000142,-0.000189,0.000048,0.002402,0.003203,0.001601,NaN
2017-09-30,0.002901,0.002973,0.001487,0.001983,58162.0,1.996157e+07,1.019273e+11,959903661.0,0.073752,-14.984526,...,-13.119634,-96.380066,42.804968,-0.000172,-0.000186,0.000014,0.002405,0.003199,0.001612,NaN
2017-09-29,0.002563,0.003474,0.001816,0.002906,69532.0,2.925584e+07,1.019273e+11,959973193.0,0.051597,-3.675588,...,38.216672,-94.695144,52.530787,-0.000121,-0.000173,0.000052,0.002446,0.003255,0.001637,NaN

In [32]:
TRX_market.dropna(inplace=True)

In [33]:
import numpy as np
from pycaret.classification import *

# Initialize setup
clf = setup(data=TRX_market, target='Tron_Change', session_id=123)

In [34]:
best_model=compare_models()

Initiated  . . . . . . . . . . . . . . . . . .              18:42:21
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library