In [83]:
import pandas as pd

In [84]:
ETH=pd.read_excel("../../../Ethereum/2022Ethereum_Original.xlsx")
ETH['Date'] = pd.to_datetime(ETH['Date'])
ETH.set_index('Date', inplace=True)

In [85]:
# List of columns to convert
columns_to_convert = ['Gold_Price', 'Oil_Price', 'Nasdaq_Close', 'S&P500_Close', 'BTC_Close','BTC_Volume','BTC_Market_Cap','Tweets_Count','Tweets_Vader_Sentiment','News_Vader_Sentiment']

# Applying the transformation
for column in columns_to_convert:
    ETH[column + '_binary'] = (ETH[column] > ETH[column].shift(1)).astype(int)

In [86]:
ETH.drop(["Internet_Penetration_USA","Population_USA","GDP_USA","Inflation_USA","Nasdaq_Open","Nasdaq_High","Nasdaq_Low","Nasdaq_Adj Close","Nasdaq_Volume","S&P500_Open","S&P500_High","S&P500_Low","S&P500_Adj Close","BTC_Open","BTC_High","BTC_Low",'Gold_Price', 'Oil_Price', 'Nasdaq_Close', 'S&P500_Close', 'BTC_Close','S&P500_Volume',],inplace=True,axis=1)
#'BTC_Volume','BTC_Market_Cap','Tweets_Count','Tweets_Vader_Sentiment','News_Vader_Sentiment'

In [87]:
ETH

,BTC_Volume,BTC_Market_Cap,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Ethereum_Change,Gold_Price_binary,Oil_Price_binary,Nasdaq_Close_binary,S&P500_Close_binary,BTC_Close_binary,BTC_Volume_binary,BTC_Market_Cap_binary,Tweets_Count_binary,Tweets_Vader_Sentiment_binary,News_Vader_Sentiment_binary
Date,,,,,,,,,,,,,,,,
2016-01-01,3.173093e+07,6.521422e+09,13583,0.238774,0.000000,1,0,0,0,0,0,0,0,0,0,0
2016-01-02,3.117175e+07,6.461269e+09,13691,0.254835,0.000000,0,0,0,0,0,0,0,0,1,1,0
2016-01-03,3.715623e+07,6.494453e+09,13167,0.248901,0.000000,1,0,0,0,0,1,1,1,0,0,0
2016-01-04,3.669657e+07,6.504166e+09,15821,0.181530,0.000000,0,1,0,0,0,0,0,1,1,0,0
2016-01-05,3.357784e+07,6.471942e+09,16689,0.182860,0.153550,0,1,0,0,1,0,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-27,1.574858e+10,3.217172e+11,39816,0.097602,-0.054126,0,0,0,0,0,0,1,0,1,1,0
2022-12-28,1.700571e+10,3.185671e+11,42534,0.084050,-0.066367,0,0,0,0,0,0,1,0,1,0,0
2022-12-29,1.447224e+10,3.203093e+11,41316,0.099584,-0.052279,1,0,0,1,1,1,0,1,0,1,1
2022-12-30,1.592916e+10,3.195595e+11,40485,0.095240,-0.024360,0,0,0,0,0,0,1,0,0,0,1
2022-12-31,1.123919e+10,3.185163e+11,35625,0.119512,-0.068864,0,0,0,0,0,0,0,0,0,1,0

In [88]:
columns_to_lag = ['Ethereum_Change'] #'Gold_Price_binary','Oil_Price_binary','Tweets_Count_binary','Tweets_Vader_Sentiment_binary','News_Vader_Sentiment_binary'

# Number of lags (days back) to create
number_of_lags = 5

# Create lag features for the selected columns
for column in columns_to_lag:
    for lag in range(1, number_of_lags + 1):
        ETH[f'{column}_lag_{lag}'] = ETH[column].shift(lag)

# Optionally, remove any rows with NaN values that were created due to shifting
ETH.dropna(inplace=True)

In [89]:
ETH

,BTC_Volume,BTC_Market_Cap,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Ethereum_Change,Gold_Price_binary,Oil_Price_binary,Nasdaq_Close_binary,S&P500_Close_binary,...,BTC_Volume_binary,BTC_Market_Cap_binary,Tweets_Count_binary,Tweets_Vader_Sentiment_binary,News_Vader_Sentiment_binary,Ethereum_Change_lag_1,Ethereum_Change_lag_2,Ethereum_Change_lag_3,Ethereum_Change_lag_4,Ethereum_Change_lag_5
Date,,,,,,,,,,,,,,,,,,,,,
2016-01-06,6.315093e+07,6.756367e+09,15981,0.212686,0.000000,1,1,0,0,0,...,1,1,0,1,0,0.0,0.0,1.0,0.0,1.0
2016-01-07,6.861985e+07,6.841605e+09,15888,0.206986,0.127267,0,1,0,0,0,...,1,1,0,0,1,1.0,0.0,0.0,1.0,0.0
2016-01-08,4.082228e+07,6.778368e+09,15049,0.219188,-0.050575,1,0,0,0,0,...,0,0,0,1,0,0.0,1.0,0.0,0.0,1.0
2016-01-09,3.223451e+07,6.702061e+09,12819,0.257393,-0.050575,1,0,0,0,0,...,0,0,0,1,0,1.0,0.0,1.0,0.0,0.0
2016-01-10,3.777257e+07,6.752461e+09,14539,0.239474,-0.050575,1,0,0,0,0,...,1,1,1,0,0,1.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-27,1.574858e+10,3.217172e+11,39816,0.097602,-0.054126,0,0,0,0,0,...,1,0,1,1,0,1.0,0.0,1.0,1.0,1.0
2022-12-28,1.700571e+10,3.185671e+11,42534,0.084050,-0.066367,0,0,0,0,0,...,1,0,1,0,0,0.0,1.0,0.0,1.0,1.0
2022-12-29,1.447224e+10,3.203093e+11,41316,0.099584,-0.052279,1,0,0,1,1,...,0,1,0,1,1,0.0,0.0,1.0,0.0,1.0
2022-12-30,1.592916e+10,3.195595e+11,40485,0.095240,-0.024360,0,0,0,0,0,...,1,0,0,0,1,1.0,0.0,0.0,1.0,0.0
2022-12-31,1.123919e+10,3.185163e+11,35625,0.119512,-0.068864,0,0,0,0,0,...,0,0,0,1,0,0.0,1.0,0.0,0.0,1.0

In [92]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Selecting the columns to standardize
features = ETH[['BTC_Volume', 'BTC_Market_Cap', 'Tweets_Count', 'Tweets_Vader_Sentiment', 'News_Vader_Sentiment']]

# Initialize the StandardScaler
scaler = StandardScaler()

# Standardize the features
features_scaled = scaler.fit_transform(features)

# Replace the original columns with the scaled columns
ETH[['BTC_Volume', 'BTC_Market_Cap', 'Tweets_Count', 'Tweets_Vader_Sentiment', 'News_Vader_Sentiment']] = features_scaled

In [93]:
ETH

,BTC_Volume,BTC_Market_Cap,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Ethereum_Change,Gold_Price_binary,Oil_Price_binary,Nasdaq_Close_binary,S&P500_Close_binary,...,BTC_Volume_binary,BTC_Market_Cap_binary,Tweets_Count_binary,Tweets_Vader_Sentiment_binary,News_Vader_Sentiment_binary,Ethereum_Change_lag_1,Ethereum_Change_lag_2,Ethereum_Change_lag_3,Ethereum_Change_lag_4,Ethereum_Change_lag_5
Date,,,,,,,,,,,,,,,,,,,,,
2016-01-06,-0.827014,-0.873368,-0.793090,1.293722,-0.169681,1,1,0,0,0,...,1,1,0,1,0,0.0,0.0,1.0,0.0,1.0
2016-01-07,-0.826862,-0.873097,-0.798254,1.174629,0.841095,0,1,0,0,0,...,1,1,0,0,1,1.0,0.0,0.0,1.0,0.0
2016-01-08,-0.827637,-0.873298,-0.844844,1.429583,-0.571358,1,0,0,0,0,...,0,0,0,1,0,0.0,1.0,0.0,0.0,1.0
2016-01-09,-0.827876,-0.873541,-0.968677,2.227892,-0.571358,1,0,0,0,0,...,0,0,0,1,0,1.0,0.0,1.0,0.0,0.0
2016-01-10,-0.827722,-0.873381,-0.873165,1.853464,-0.571358,1,0,0,0,0,...,1,1,1,0,0,1.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-27,-0.389634,0.128549,0.530476,-1.110987,-0.599557,0,0,0,0,0,...,1,0,1,1,0,1.0,0.0,1.0,1.0,1.0
2022-12-28,-0.354580,0.118528,0.681407,-1.394168,-0.696778,0,0,0,0,0,...,1,0,1,0,0,0.0,1.0,0.0,1.0,1.0
2022-12-29,-0.425225,0.124071,0.613771,-1.069575,-0.584888,1,0,0,1,1,...,0,1,0,1,1,0.0,0.0,1.0,0.0,1.0
2022-12-30,-0.384599,0.121685,0.567625,-1.160341,-0.363153,0,0,0,0,0,...,1,0,0,0,1,1.0,0.0,0.0,1.0,0.0
2022-12-31,-0.515376,0.118367,0.297748,-0.653171,-0.716611,0,0,0,0,0,...,0,0,0,1,0,0.0,1.0,0.0,0.0,1.0

In [100]:
ETH_market= pd.read_excel("../../Base_Datasets/Alt_Coin_Yearly_Rank.xlsx", sheet_name = 'Ethereum_Daily')
ETH_market['Date'] = pd.to_datetime(ETH_market['Date'])
ETH_market.set_index('Date', inplace=True)

In [101]:
ETH_market

,Open*,High,Low,Close**,Volume,Market Cap
Date,,,,,,
2022-12-31,"$1,199.36","$1,205.09","$1,194.20","$1,196.77","$3,018,513,333","$146,453,523,490"
2022-12-30,"$1,201.57","$1,202.03","$1,187.46","$1,199.23","$4,055,668,253","$146,754,748,633"
2022-12-29,"$1,190.01","$1,204.14","$1,188.36","$1,201.60","$4,132,233,940","$147,043,867,255"
2022-12-28,"$1,212.74","$1,213.13","$1,185.70","$1,189.99","$4,991,669,631","$145,623,194,889"
2022-12-27,"$1,226.99","$1,230.42","$1,205.90","$1,212.79","$4,091,530,737","$148,414,001,604"
...,...,...,...,...,...,...
2016-01-05,$0.9531,$0.9706,$0.9465,$0.9502,"$219,833","$72,240,974"
2016-01-04,$0.972,$0.9764,$0.9298,$0.9545,"$346,245","$72,543,707"
2016-01-03,$0.9384,$0.9914,$0.9343,$0.9719,"$407,632","$73,843,292"
2016-01-02,$0.9474,$0.9696,$0.9366,$0.9371,"$255,504","$71,176,658"
2016-01-01,$0.9337,$0.9548,$0.9314,$0.948,"$206,062","$71,980,386"

In [102]:
# Convert columns to float, removing any non-numeric characters like commas
ETH_market['Open*'] = pd.to_numeric(ETH_market['Open*'].replace('[^\d.]', '', regex=True), errors='coerce')
ETH_market['High'] = pd.to_numeric(ETH_market['High'].replace('[^\d.]', '', regex=True), errors='coerce')
ETH_market['Low'] = pd.to_numeric(ETH_market['Low'].replace('[^\d.]', '', regex=True), errors='coerce')
ETH_market['Close**'] = pd.to_numeric(ETH_market['Close**'].replace('[^\d.]', '', regex=True), errors='coerce')
ETH_market['Volume'] = pd.to_numeric(ETH_market['Volume'].replace('[^\d.]', '', regex=True), errors='coerce')
ETH_market['Market Cap'] = pd.to_numeric(ETH_market['Market Cap'].replace('[^\d.]', '', regex=True), errors='coerce')

In [103]:
ETH_market

,Open*,High,Low,Close**,Volume,Market Cap
Date,,,,,,
2022-12-31,1199.3600,1205.0900,1194.2000,1196.7700,3018513333,146453523490
2022-12-30,1201.5700,1202.0300,1187.4600,1199.2300,4055668253,146754748633
2022-12-29,1190.0100,1204.1400,1188.3600,1201.6000,4132233940,147043867255
2022-12-28,1212.7400,1213.1300,1185.7000,1189.9900,4991669631,145623194889
2022-12-27,1226.9900,1230.4200,1205.9000,1212.7900,4091530737,148414001604
...,...,...,...,...,...,...
2016-01-05,0.9531,0.9706,0.9465,0.9502,219833,72240974
2016-01-04,0.9720,0.9764,0.9298,0.9545,346245,72543707
2016-01-03,0.9384,0.9914,0.9343,0.9719,407632,73843292
2016-01-02,0.9474,0.9696,0.9366,0.9371,255504,71176658
2016-01-01,0.9337,0.9548,0.9314,0.9480,206062,71980386

In [104]:
from ta import add_all_ta_features
from ta.utils import dropna

# Clean NaN values
ETH_market = dropna(ETH_market)

# Add all technical indicators
ETH_market = add_all_ta_features(
    ETH_market, open="Open*", high="High", low="Low", close="Close**", volume="Volume", fillna=True
)

In [105]:
ETH_market

,Open*,High,Low,Close**,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,...,momentum_ppo,momentum_ppo_signal,momentum_ppo_hist,momentum_pvo,momentum_pvo_signal,momentum_pvo_hist,momentum_kama,others_dr,others_dlr,others_cr
Date,,,,,,,,,,,,,,,,,,,,,
2022-12-31,1199.3600,1205.0900,1194.2000,1196.7700,3018513333,146453523490,-1.593797e+09,3018513333,-0.528007,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.770000,0.000000,0.000000,0.000000
2022-12-30,1201.5700,1202.0300,1187.4600,1199.2300,4055668253,146754748633,9.030692e+08,7074181586,0.127657,9.976944e+09,...,0.016395,0.003279,0.013116,2.672922,0.534584,2.138337,1197.863269,0.205553,0.205342,0.205553
2022-12-29,1190.0100,1204.1400,1188.3600,1201.6000,4132233940,147043867255,3.705028e+09,11206415526,0.330617,9.950723e+09,...,0.044835,0.011590,0.033245,4.814488,1.390565,3.423923,1199.523942,0.197627,0.197432,0.403586
2022-12-28,1212.7400,1213.1300,1185.7000,1189.9900,4991669631,145623194889,2.747333e+08,6214745895,0.016961,2.501501e+08,...,-0.010748,0.007123,-0.017871,8.296949,2.771842,5.525107,1195.431945,-0.966212,-0.970910,-0.566525
2022-12-27,1226.9900,1230.4200,1205.9000,1212.7900,4091530737,148414001604,-1.517397e+09,10306276632,-0.074787,1.354111e+10,...,0.097691,0.025236,0.072455,8.759233,3.969320,4.789913,1202.886818,1.915982,1.897859,1.338603
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-05,0.9531,0.9706,0.9465,0.9502,219833,72240974,2.460530e+12,-1372918065031,0.197787,-9.471747e+04,...,-33.826201,-33.998999,0.172799,-63.568733,-54.197643,-9.371090,0.977765,-0.073614,-0.073642,-99.920603
2016-01-04,0.9720,0.9764,0.9298,0.9545,346245,72543707,2.460530e+12,-1372917718786,0.195874,-8.097371e+04,...,-33.178039,-33.834807,0.656768,-65.356722,-56.429459,-8.927263,0.970271,0.452536,0.451515,-99.920244
2016-01-03,0.9384,0.9914,0.9343,0.9719,407632,73843292,2.460530e+12,-1372917311154,0.051470,-6.839278e+04,...,-32.295747,-33.526995,1.231248,-66.624797,-58.468526,-8.156271,0.970619,1.822944,1.806528,-99.918790
2016-01-02,0.9474,0.9696,0.9366,0.9371,255504,71176658,2.460530e+12,-1372917566658,0.070587,-5.989260e+04,...,-31.562686,-33.134133,1.571448,-68.338193,-60.442460,-7.895733,0.961305,-3.580615,-3.646292,-99.921698
2016-01-01,0.9337,0.9548,0.9314,0.9480,206062,71980386,2.460530e+12,-1372917360596,0.065394,-5.101565e+04,...,-30.652799,-32.637866,1.985068,-70.050714,-62.364110,-7.686603,0.959065,1.163163,1.156450,-99.920787

In [106]:
from ta.momentum import RSIIndicator
from ta.trend import MACD
from ta.volatility import BollingerBands

# RSI
ETH_market['rsi'] = RSIIndicator(close=ETH_market['Close**'], window=14, fillna=True).rsi()

# MACD
macd = MACD(close=ETH_market['Close**'], window_slow=26, window_fast=12, window_sign=9, fillna=True)
ETH_market['macd'] = macd.macd()
ETH_market['macd_signal'] = macd.macd_signal()
ETH_market['macd_diff'] = macd.macd_diff()

# Bollinger Bands
indicator_bb = BollingerBands(close=ETH_market['Close**'], window=20, window_dev=2, fillna=True)
ETH_market['bb_bbm'] = indicator_bb.bollinger_mavg()
ETH_market['bb_bbh'] = indicator_bb.bollinger_hband()
ETH_market['bb_bbl'] = indicator_bb.bollinger_lband()

In [107]:
ETH_market

,Open*,High,Low,Close**,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,...,others_dr,others_dlr,others_cr,rsi,macd,macd_signal,macd_diff,bb_bbm,bb_bbh,bb_bbl
Date,,,,,,,,,,,,,,,,,,,,,
2022-12-31,1199.3600,1205.0900,1194.2000,1196.7700,3018513333,146453523490,-1.593797e+09,3018513333,-0.528007,0.000000e+00,...,0.000000,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,1196.770000,1196.770000,1196.770000
2022-12-30,1201.5700,1202.0300,1187.4600,1199.2300,4055668253,146754748633,9.030692e+08,7074181586,0.127657,9.976944e+09,...,0.205553,0.205342,0.205553,100.000000,0.196239,0.039248,0.156991,1198.000000,1200.460000,1195.540000
2022-12-29,1190.0100,1204.1400,1188.3600,1201.6000,4132233940,147043867255,3.705028e+09,11206415526,0.330617,9.950723e+09,...,0.197627,0.197432,0.403586,100.000000,0.536812,0.138761,0.398051,1199.200000,1203.143907,1195.256093
2022-12-28,1212.7400,1213.1300,1185.7000,1189.9900,4991669631,145623194889,2.747333e+08,6214745895,0.016961,2.501501e+08,...,-0.966212,-0.970910,-0.566525,27.127046,-0.128630,0.085283,-0.213912,1196.897500,1205.574128,1188.220872
2022-12-27,1226.9900,1230.4200,1205.9000,1212.7900,4091530737,148414001604,-1.517397e+09,10306276632,-0.074787,1.354111e+10,...,1.915982,1.897859,1.338603,71.323196,1.170282,0.302283,0.868000,1200.076000,1214.971398,1185.180602
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-05,0.9531,0.9706,0.9465,0.9502,219833,72240974,2.460530e+12,-1372918065031,0.197787,-9.471747e+04,...,-0.073614,-0.073642,-99.920603,23.222015,-0.573078,-0.675665,0.102587,1.279295,1.930723,0.627867
2016-01-04,0.9720,0.9764,0.9298,0.9545,346245,72543707,2.460530e+12,-1372917718786,0.195874,-8.097371e+04,...,0.452536,0.451515,-99.920244,23.443580,-0.543918,-0.649316,0.105398,1.220020,1.752223,0.687817
2016-01-03,0.9384,0.9914,0.9343,0.9719,407632,73843292,2.460530e+12,-1372917311154,0.051470,-6.839278e+04,...,1.822944,1.806528,-99.918790,24.394372,-0.513486,-0.622150,0.108664,1.170115,1.586163,0.754067
2016-01-02,0.9474,0.9696,0.9366,0.9371,255504,71176658,2.460530e+12,-1372917566658,0.070587,-5.989260e+04,...,-3.580615,-3.646292,-99.921698,23.758831,-0.486567,-0.595033,0.108466,1.141970,1.540746,0.743194
2016-01-01,0.9337,0.9548,0.9314,0.9480,206062,71980386,2.460530e+12,-1372917360596,0.065394,-5.101565e+04,...,1.163163,1.156450,-99.920787,24.422995,-0.459062,-0.567839,0.108777,1.111870,1.471905,0.751835

In [108]:
# Shift all columns except 'Date'
columns_to_shift = ETH_market.columns.difference(['Date'])
ETH_market[columns_to_shift] = ETH_market[columns_to_shift].shift(-1)

ETH_market.dropna(inplace=True)

In [109]:
ETH_market

,Open*,High,Low,Close**,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,...,others_dr,others_dlr,others_cr,rsi,macd,macd_signal,macd_diff,bb_bbm,bb_bbh,bb_bbl
Date,,,,,,,,,,,,,,,,,,,,,
2022-12-31,1201.5700,1202.0300,1187.4600,1199.2300,4.055668e+09,1.467547e+11,9.030692e+08,7.074182e+09,0.127657,9.976944e+09,...,0.205553,0.205342,0.205553,100.000000,0.196239,0.039248,0.156991,1198.000000,1200.460000,1195.540000
2022-12-30,1190.0100,1204.1400,1188.3600,1201.6000,4.132234e+09,1.470439e+11,3.705028e+09,1.120642e+10,0.330617,9.950723e+09,...,0.197627,0.197432,0.403586,100.000000,0.536812,0.138761,0.398051,1199.200000,1203.143907,1195.256093
2022-12-29,1212.7400,1213.1300,1185.7000,1189.9900,4.991670e+09,1.456232e+11,2.747333e+08,6.214746e+09,0.016961,2.501501e+08,...,-0.966212,-0.970910,-0.566525,27.127046,-0.128630,0.085283,-0.213912,1196.897500,1205.574128,1188.220872
2022-12-28,1226.9900,1230.4200,1205.9000,1212.7900,4.091531e+09,1.484140e+11,-1.517397e+09,1.030628e+10,-0.074787,1.354111e+10,...,1.915982,1.897859,1.338603,71.323196,1.170282,0.302283,0.868000,1200.076000,1214.971398,1185.180602
2022-12-27,1218.9200,1226.9700,1214.3400,1226.9700,3.282098e+09,1.501496e+11,1.764701e+09,1.358838e+10,0.074865,1.825526e+10,...,1.169205,1.162423,2.523459,79.606938,3.305780,0.902982,2.402798,1204.558333,1228.780644,1180.336023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-06,0.9531,0.9706,0.9465,0.9502,2.198330e+05,7.224097e+07,2.460530e+12,-1.372918e+12,0.197787,-9.471747e+04,...,-0.073614,-0.073642,-99.920603,23.222015,-0.573078,-0.675665,0.102587,1.279295,1.930723,0.627867
2016-01-05,0.9720,0.9764,0.9298,0.9545,3.462450e+05,7.254371e+07,2.460530e+12,-1.372918e+12,0.195874,-8.097371e+04,...,0.452536,0.451515,-99.920244,23.443580,-0.543918,-0.649316,0.105398,1.220020,1.752223,0.687817
2016-01-04,0.9384,0.9914,0.9343,0.9719,4.076320e+05,7.384329e+07,2.460530e+12,-1.372917e+12,0.051470,-6.839278e+04,...,1.822944,1.806528,-99.918790,24.394372,-0.513486,-0.622150,0.108664,1.170115,1.586163,0.754067
2016-01-03,0.9474,0.9696,0.9366,0.9371,2.555040e+05,7.117666e+07,2.460530e+12,-1.372918e+12,0.070587,-5.989260e+04,...,-3.580615,-3.646292,-99.921698,23.758831,-0.486567,-0.595033,0.108466,1.141970,1.540746,0.743194
2016-01-02,0.9337,0.9548,0.9314,0.9480,2.060620e+05,7.198039e+07,2.460530e+12,-1.372917e+12,0.065394,-5.101565e+04,...,1.163163,1.156450,-99.920787,24.422995,-0.459062,-0.567839,0.108777,1.111870,1.471905,0.751835

In [116]:
Ethereum_final_dataset=ETH_market.join(ETH,how='inner')

In [117]:
Ethereum_final_dataset

,Open*,High,Low,Close**,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,...,BTC_Volume_binary,BTC_Market_Cap_binary,Tweets_Count_binary,Tweets_Vader_Sentiment_binary,News_Vader_Sentiment_binary,Ethereum_Change_lag_1,Ethereum_Change_lag_2,Ethereum_Change_lag_3,Ethereum_Change_lag_4,Ethereum_Change_lag_5
Date,,,,,,,,,,,,,,,,,,,,,
2022-12-31,1201.5700,1202.0300,1187.4600,1199.2300,4.055668e+09,1.467547e+11,9.030692e+08,7.074182e+09,0.127657,9.976944e+09,...,0,0,0,1,0,0.0,1.0,0.0,0.0,1.0
2022-12-30,1190.0100,1204.1400,1188.3600,1201.6000,4.132234e+09,1.470439e+11,3.705028e+09,1.120642e+10,0.330617,9.950723e+09,...,1,0,0,0,1,1.0,0.0,0.0,1.0,0.0
2022-12-29,1212.7400,1213.1300,1185.7000,1189.9900,4.991670e+09,1.456232e+11,2.747333e+08,6.214746e+09,0.016961,2.501501e+08,...,0,1,0,1,1,0.0,0.0,1.0,0.0,1.0
2022-12-28,1226.9900,1230.4200,1205.9000,1212.7900,4.091531e+09,1.484140e+11,-1.517397e+09,1.030628e+10,-0.074787,1.354111e+10,...,1,0,1,0,0,0.0,1.0,0.0,1.0,1.0
2022-12-27,1218.9200,1226.9700,1214.3400,1226.9700,3.282098e+09,1.501496e+11,1.764701e+09,1.358838e+10,0.074865,1.825526e+10,...,1,0,1,1,0,1.0,0.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-10,0.9855,0.9923,0.9736,0.9868,2.262810e+05,7.512831e+07,2.460530e+12,-1.372918e+12,0.127497,-1.704184e+05,...,1,1,1,0,0,1.0,1.0,0.0,1.0,0.0
2016-01-09,0.9428,0.9918,0.9397,0.9868,5.456000e+05,7.509981e+07,2.460531e+12,-1.372918e+12,0.133026,-1.460729e+05,...,0,0,0,1,0,1.0,0.0,1.0,0.0,0.0
2016-01-08,0.9558,0.9746,0.9358,0.9420,6.474620e+05,7.166715e+07,2.460530e+12,-1.372918e+12,0.138765,-1.293491e+05,...,0,0,0,1,0,0.0,1.0,0.0,0.0,1.0
2016-01-07,0.9500,0.9607,0.9357,0.9509,3.087910e+05,7.231715e+07,2.460530e+12,-1.372918e+12,0.252894,-1.104781e+05,...,1,1,0,0,1,1.0,0.0,0.0,1.0,0.0
2016-01-06,0.9531,0.9706,0.9465,0.9502,2.198330e+05,7.224097e+07,2.460530e+12,-1.372918e+12,0.197787,-9.471747e+04,...,1,1,0,1,0,0.0,0.0,1.0,0.0,1.0

In [126]:
Ethereum_final_dataset.to_csv("Ethereum_final_dataset.csv")

In [119]:
ETH_market["Ethereum_Change"]=ETH["Ethereum_Change"]

In [122]:
ETH_market.dropna(inplace=True)

In [123]:
ETH_market

,Open*,High,Low,Close**,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,...,others_dlr,others_cr,rsi,macd,macd_signal,macd_diff,bb_bbm,bb_bbh,bb_bbl,Ethereum_Change
Date,,,,,,,,,,,,,,,,,,,,,
2022-12-31,1201.5700,1202.0300,1187.4600,1199.2300,4.055668e+09,1.467547e+11,9.030692e+08,7.074182e+09,0.127657,9.976944e+09,...,0.205342,0.205553,100.000000,0.196239,0.039248,0.156991,1198.000000,1200.460000,1195.540000,0.0
2022-12-30,1190.0100,1204.1400,1188.3600,1201.6000,4.132234e+09,1.470439e+11,3.705028e+09,1.120642e+10,0.330617,9.950723e+09,...,0.197432,0.403586,100.000000,0.536812,0.138761,0.398051,1199.200000,1203.143907,1195.256093,0.0
2022-12-29,1212.7400,1213.1300,1185.7000,1189.9900,4.991670e+09,1.456232e+11,2.747333e+08,6.214746e+09,0.016961,2.501501e+08,...,-0.970910,-0.566525,27.127046,-0.128630,0.085283,-0.213912,1196.897500,1205.574128,1188.220872,1.0
2022-12-28,1226.9900,1230.4200,1205.9000,1212.7900,4.091531e+09,1.484140e+11,-1.517397e+09,1.030628e+10,-0.074787,1.354111e+10,...,1.897859,1.338603,71.323196,1.170282,0.302283,0.868000,1200.076000,1214.971398,1185.180602,0.0
2022-12-27,1218.9200,1226.9700,1214.3400,1226.9700,3.282098e+09,1.501496e+11,1.764701e+09,1.358838e+10,0.074865,1.825526e+10,...,1.162423,2.523459,79.606938,3.305780,0.902982,2.402798,1204.558333,1228.780644,1180.336023,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-10,0.9855,0.9923,0.9736,0.9868,2.262810e+05,7.512831e+07,2.460530e+12,-1.372918e+12,0.127497,-1.704184e+05,...,-1.248757,-99.917545,23.401585,-0.681572,-0.774581,0.093009,1.572800,2.599725,0.545875,1.0
2016-01-09,0.9428,0.9918,0.9397,0.9868,5.456000e+05,7.509981e+07,2.460531e+12,-1.372918e+12,0.133026,-1.460729e+05,...,0.000000,-99.917545,23.401585,-0.654357,-0.750536,0.096180,1.495640,2.452820,0.538460,1.0
2016-01-08,0.9558,0.9746,0.9358,0.9420,6.474620e+05,7.166715e+07,2.460530e+12,-1.372918e+12,0.138765,-1.293491e+05,...,-4.646211,-99.921288,22.833437,-0.629151,-0.726259,0.097108,1.423240,2.315739,0.530741,1.0
2016-01-07,0.9500,0.9607,0.9357,0.9509,3.087910e+05,7.231715e+07,2.460530e+12,-1.372918e+12,0.252894,-1.104781e+05,...,0.940363,-99.920544,23.232179,-0.601523,-0.701312,0.099789,1.356785,2.179404,0.534166,0.0
2016-01-06,0.9531,0.9706,0.9465,0.9502,2.198330e+05,7.224097e+07,2.460530e+12,-1.372918e+12,0.197787,-9.471747e+04,...,-0.073642,-99.920603,23.222015,-0.573078,-0.675665,0.102587,1.279295,1.930723,0.627867,1.0

In [ ]:
ETH_market.drop()

In [114]:
import numpy as np
from pycaret.classification import *

# Initialize setup
clf = setup(data=Ethereum_final_dataset, target='Ethereum_Change', session_id=123)

In [115]:
best_model=compare_models()

In [124]:
import numpy as np
from pycaret.classification import *

# Initialize setup
clf = setup(data=ETH_market, target='Ethereum_Change', session_id=123)

In [125]:
best_model=compare_models()