In [1]:
import pandas as pd

In [2]:
LTC=pd.read_excel("../../../Litecoin/2022Litecoin_Original.xlsx")
LTC['Date'] = pd.to_datetime(LTC['Date'])
LTC.set_index('Date', inplace=True)

In [3]:
LTC

,Internet_Penetration_USA,Population_USA,GDP_USA,Inflation_USA,Gold_Price,Oil_Price,Nasdaq_Open,Nasdaq_High,Nasdaq_Low,Nasdaq_Close,...,BTC_Open,BTC_High,BTC_Low,BTC_Close,BTC_Volume,BTC_Market_Cap,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Litecoin_Change
Date,,,,,,,,,,,,,,,,,,,,,
2016-01-01,85.544421,323689,18425.3,1.4,1060.5,37.04,4897.649902,4903.089844,4846.979980,4903.089844,...,434.334,436.062,431.870,433.307,3.173093e+07,6.521422e+09,13583,0.238774,0.000000,1
2016-01-02,85.544421,323689,18425.3,1.4,1060.5,37.04,4897.649902,4903.089844,4846.979980,4903.089844,...,433.438,433.743,424.706,429.880,3.117175e+07,6.461269e+09,13691,0.254835,0.000000,0
2016-01-03,85.544421,323689,18425.3,1.4,1060.5,37.04,4897.649902,4903.089844,4846.979980,4903.089844,...,430.011,434.517,429.084,433.122,3.715623e+07,6.494453e+09,13167,0.248901,0.000000,0
2016-01-04,85.544421,323689,18425.3,1.4,1075.5,36.76,4897.649902,4903.089844,4846.979980,4903.089844,...,433.091,434.182,429.676,431.945,3.669657e+07,6.504166e+09,15821,0.181530,0.000000,1
2016-01-05,85.544421,323689,18425.3,1.4,1078.7,35.97,4917.839844,4926.729980,4872.740234,4891.430176,...,431.960,431.960,426.341,430.231,3.357784e+07,6.471942e+09,16689,0.182860,0.153550,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-27,92.000000,333241,25723.9,6.5,1797.7,75.89,10462.190430,10472.320313,10340.730469,10353.230469,...,16919.290,16959.850,16642.070,16717.170,1.574858e+10,3.217172e+11,39816,0.097602,-0.054126,0
2022-12-28,92.000000,333241,25723.9,6.5,1797.7,75.89,10339.200195,10414.820313,10207.469727,10213.290039,...,16716.400,16768.170,16497.560,16552.570,1.700571e+10,3.185671e+11,42534,0.084050,-0.066367,0
2022-12-29,92.000000,333241,25723.9,6.5,1797.7,75.89,10321.459961,10502.080078,10301.059570,10478.089844,...,16552.320,16651.760,16508.680,16642.340,1.447224e+10,3.203093e+11,41316,0.099584,-0.052279,1
2022-12-30,92.000000,333241,25723.9,6.5,1797.7,75.89,10368.370117,10468.309570,10324.700195,10466.480469,...,16641.330,16643.430,16408.480,16602.590,1.592916e+10,3.195595e+11,40485,0.095240,-0.024360,1
2022-12-31,92.000000,333241,25723.9,6.5,1797.7,75.89,10368.370117,10468.309570,10324.700195,10466.480469,...,16603.670,16628.990,16517.520,16547.500,1.123919e+10,3.185163e+11,35625,0.119512,-0.068864,1

In [4]:
# List of columns to convert
columns_to_convert = ['Gold_Price', 'Oil_Price', 'Nasdaq_Close', 'S&P500_Close', 'BTC_Close','BTC_Volume','BTC_Market_Cap','Tweets_Count','Tweets_Vader_Sentiment','News_Vader_Sentiment']

# Applying the transformation
for column in columns_to_convert:
    LTC[column + '_binary'] = (LTC[column] > LTC[column].shift(1)).astype(int)

In [5]:
LTC.drop(["Internet_Penetration_USA","Population_USA","GDP_USA","Inflation_USA","Nasdaq_Open","Nasdaq_High","Nasdaq_Low","Nasdaq_Adj Close","Nasdaq_Volume","S&P500_Open","S&P500_High","S&P500_Low","S&P500_Adj Close","BTC_Open","BTC_High","BTC_Low",'Gold_Price', 'Oil_Price', 'Nasdaq_Close', 'S&P500_Close', 'BTC_Close','S&P500_Volume',],inplace=True,axis=1)

In [6]:
LTC

,BTC_Volume,BTC_Market_Cap,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Litecoin_Change,Gold_Price_binary,Oil_Price_binary,Nasdaq_Close_binary,S&P500_Close_binary,BTC_Close_binary,BTC_Volume_binary,BTC_Market_Cap_binary,Tweets_Count_binary,Tweets_Vader_Sentiment_binary,News_Vader_Sentiment_binary
Date,,,,,,,,,,,,,,,,
2016-01-01,3.173093e+07,6.521422e+09,13583,0.238774,0.000000,1,0,0,0,0,0,0,0,0,0,0
2016-01-02,3.117175e+07,6.461269e+09,13691,0.254835,0.000000,0,0,0,0,0,0,0,0,1,1,0
2016-01-03,3.715623e+07,6.494453e+09,13167,0.248901,0.000000,0,0,0,0,0,1,1,1,0,0,0
2016-01-04,3.669657e+07,6.504166e+09,15821,0.181530,0.000000,1,1,0,0,0,0,0,1,1,0,0
2016-01-05,3.357784e+07,6.471942e+09,16689,0.182860,0.153550,0,1,0,0,1,0,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-27,1.574858e+10,3.217172e+11,39816,0.097602,-0.054126,0,0,0,0,0,0,1,0,1,1,0
2022-12-28,1.700571e+10,3.185671e+11,42534,0.084050,-0.066367,0,0,0,0,0,0,1,0,1,0,0
2022-12-29,1.447224e+10,3.203093e+11,41316,0.099584,-0.052279,1,0,0,1,1,1,0,1,0,1,1
2022-12-30,1.592916e+10,3.195595e+11,40485,0.095240,-0.024360,1,0,0,0,0,0,1,0,0,0,1
2022-12-31,1.123919e+10,3.185163e+11,35625,0.119512,-0.068864,1,0,0,0,0,0,0,0,0,1,0

In [7]:
columns_to_lag = ['Litecoin_Change'] #'Gold_Price_binary','Oil_Price_binary','Tweets_Count_binary','Tweets_Vader_Sentiment_binary','News_Vader_Sentiment_binary'

# Number of lags (days back) to create
number_of_lags = 5

# Create lag features for the selected columns
for column in columns_to_lag:
    for lag in range(1, number_of_lags + 1):
        LTC[f'{column}_lag_{lag}'] = LTC[column].shift(lag)

# Optionally, remove any rows with NaN values that were created due to shifting
LTC.dropna(inplace=True)

In [8]:
LTC

,BTC_Volume,BTC_Market_Cap,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Litecoin_Change,Gold_Price_binary,Oil_Price_binary,Nasdaq_Close_binary,S&P500_Close_binary,...,BTC_Volume_binary,BTC_Market_Cap_binary,Tweets_Count_binary,Tweets_Vader_Sentiment_binary,News_Vader_Sentiment_binary,Litecoin_Change_lag_1,Litecoin_Change_lag_2,Litecoin_Change_lag_3,Litecoin_Change_lag_4,Litecoin_Change_lag_5
Date,,,,,,,,,,,,,,,,,,,,,
2016-01-06,6.315093e+07,6.756367e+09,15981,0.212686,0.000000,0,1,0,0,0,...,1,1,0,1,0,0.0,1.0,0.0,0.0,1.0
2016-01-07,6.861985e+07,6.841605e+09,15888,0.206986,0.127267,1,1,0,0,0,...,1,1,0,0,1,0.0,0.0,1.0,0.0,0.0
2016-01-08,4.082228e+07,6.778368e+09,15049,0.219188,-0.050575,0,0,0,0,0,...,0,0,0,1,0,1.0,0.0,0.0,1.0,0.0
2016-01-09,3.223451e+07,6.702061e+09,12819,0.257393,-0.050575,0,0,0,0,0,...,0,0,0,1,0,0.0,1.0,0.0,0.0,1.0
2016-01-10,3.777257e+07,6.752461e+09,14539,0.239474,-0.050575,0,0,0,0,0,...,1,1,1,0,0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-27,1.574858e+10,3.217172e+11,39816,0.097602,-0.054126,0,0,0,0,0,...,1,0,1,1,0,1.0,1.0,1.0,0.0,1.0
2022-12-28,1.700571e+10,3.185671e+11,42534,0.084050,-0.066367,0,0,0,0,0,...,1,0,1,0,0,0.0,1.0,1.0,1.0,0.0
2022-12-29,1.447224e+10,3.203093e+11,41316,0.099584,-0.052279,1,0,0,1,1,...,0,1,0,1,1,0.0,0.0,1.0,1.0,1.0
2022-12-30,1.592916e+10,3.195595e+11,40485,0.095240,-0.024360,1,0,0,0,0,...,1,0,0,0,1,1.0,0.0,0.0,1.0,1.0
2022-12-31,1.123919e+10,3.185163e+11,35625,0.119512,-0.068864,1,0,0,0,0,...,0,0,0,1,0,1.0,1.0,0.0,0.0,1.0

In [9]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Selecting the columns to standardize
features = LTC[['BTC_Volume', 'BTC_Market_Cap', 'Tweets_Count', 'Tweets_Vader_Sentiment', 'News_Vader_Sentiment']]

# Initialize the StandardScaler
scaler = StandardScaler()

# Standardize the features
features_scaled = scaler.fit_transform(features)

# Replace the original columns with the scaled columns
LTC[['BTC_Volume', 'BTC_Market_Cap', 'Tweets_Count', 'Tweets_Vader_Sentiment', 'News_Vader_Sentiment']] = features_scaled

In [10]:
LTC

,BTC_Volume,BTC_Market_Cap,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Litecoin_Change,Gold_Price_binary,Oil_Price_binary,Nasdaq_Close_binary,S&P500_Close_binary,...,BTC_Volume_binary,BTC_Market_Cap_binary,Tweets_Count_binary,Tweets_Vader_Sentiment_binary,News_Vader_Sentiment_binary,Litecoin_Change_lag_1,Litecoin_Change_lag_2,Litecoin_Change_lag_3,Litecoin_Change_lag_4,Litecoin_Change_lag_5
Date,,,,,,,,,,,,,,,,,,,,,
2016-01-06,-0.827014,-0.873368,-0.793090,1.293722,-0.169681,0,1,0,0,0,...,1,1,0,1,0,0.0,1.0,0.0,0.0,1.0
2016-01-07,-0.826862,-0.873097,-0.798254,1.174629,0.841095,1,1,0,0,0,...,1,1,0,0,1,0.0,0.0,1.0,0.0,0.0
2016-01-08,-0.827637,-0.873298,-0.844844,1.429583,-0.571358,0,0,0,0,0,...,0,0,0,1,0,1.0,0.0,0.0,1.0,0.0
2016-01-09,-0.827876,-0.873541,-0.968677,2.227892,-0.571358,0,0,0,0,0,...,0,0,0,1,0,0.0,1.0,0.0,0.0,1.0
2016-01-10,-0.827722,-0.873381,-0.873165,1.853464,-0.571358,0,0,0,0,0,...,1,1,1,0,0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-27,-0.389634,0.128549,0.530476,-1.110987,-0.599557,0,0,0,0,0,...,1,0,1,1,0,1.0,1.0,1.0,0.0,1.0
2022-12-28,-0.354580,0.118528,0.681407,-1.394168,-0.696778,0,0,0,0,0,...,1,0,1,0,0,0.0,1.0,1.0,1.0,0.0
2022-12-29,-0.425225,0.124071,0.613771,-1.069575,-0.584888,1,0,0,1,1,...,0,1,0,1,1,0.0,0.0,1.0,1.0,1.0
2022-12-30,-0.384599,0.121685,0.567625,-1.160341,-0.363153,1,0,0,0,0,...,1,0,0,0,1,1.0,0.0,0.0,1.0,1.0
2022-12-31,-0.515376,0.118367,0.297748,-0.653171,-0.716611,1,0,0,0,0,...,0,0,0,1,0,1.0,1.0,0.0,0.0,1.0

In [15]:
LTC_market= pd.read_excel("../../Base_Datasets/Alt_Coin_Yearly_Rank.xlsx", sheet_name = 'Litecoin_Daily')
LTC_market['Date'] = pd.to_datetime(LTC_market['Date'])
LTC_market.set_index('Date', inplace=True)

In [16]:
LTC_market

             Open*    High     Low Close**        Volume      Market Cap
Date
2023-01-10  $81.73  $82.60  $79.88  $80.89  $561,103,552  $5,825,957,315
2023-01-09  $77.68  $83.29  $77.68  $81.75  $879,528,523  $5,887,263,235
2023-01-08  $76.37  $77.68  $75.53  $77.68  $384,160,222  $5,593,945,349
2023-01-07  $75.99  $76.60  $75.67  $76.37  $332,539,243  $5,499,144,136
2023-01-06  $74.26  $76.27  $73.01  $75.99  $537,790,219  $5,471,155,488
...            ...     ...     ...     ...           ...             ...
2016-01-05   $3.49   $3.51   $3.45   $3.47    $2,104,650    $152,390,643
2016-01-04   $3.48   $3.51   $3.48   $3.50    $3,309,740    $153,467,942
2016-01-03   $3.50   $3.51   $3.45   $3.48    $2,406,150    $152,873,557
2016-01-02   $3.52   $3.53   $3.49   $3.50    $3,020,260    $153,658,445
2016-01-01   $3.48   $3.53   $3.47   $3.51    $2,791,170    $153,910,742

[2567 rows x 6 columns]

In [17]:
# Convert columns to float, removing any non-numeric characters like commas
LTC_market['Open*'] = pd.to_numeric(LTC_market['Open*'].replace('[^\d.]', '', regex=True), errors='coerce')
LTC_market['High'] = pd.to_numeric(LTC_market['High'].replace('[^\d.]', '', regex=True), errors='coerce')
LTC_market['Low'] = pd.to_numeric(LTC_market['Low'].replace('[^\d.]', '', regex=True), errors='coerce')
LTC_market['Close**'] = pd.to_numeric(LTC_market['Close**'].replace('[^\d.]', '', regex=True), errors='coerce')
LTC_market['Volume'] = pd.to_numeric(LTC_market['Volume'].replace('[^\d.]', '', regex=True), errors='coerce')
LTC_market['Market Cap'] = pd.to_numeric(LTC_market['Market Cap'].replace('[^\d.]', '', regex=True), errors='coerce')

In [18]:
LTC_market

            Open*   High    Low  Close**     Volume  Market Cap
Date
2023-01-10  81.73  82.60  79.88    80.89  561103552  5825957315
2023-01-09  77.68  83.29  77.68    81.75  879528523  5887263235
2023-01-08  76.37  77.68  75.53    77.68  384160222  5593945349
2023-01-07  75.99  76.60  75.67    76.37  332539243  5499144136
2023-01-06  74.26  76.27  73.01    75.99  537790219  5471155488
...           ...    ...    ...      ...        ...         ...
2016-01-05   3.49   3.51   3.45     3.47    2104650   152390643
2016-01-04   3.48   3.51   3.48     3.50    3309740   153467942
2016-01-03   3.50   3.51   3.45     3.48    2406150   152873557
2016-01-02   3.52   3.53   3.49     3.50    3020260   153658445
2016-01-01   3.48   3.53   3.47     3.51    2791170   153910742

[2567 rows x 6 columns]

In [19]:
from ta import add_all_ta_features
from ta.utils import dropna

# Clean NaN values
LTC_market = dropna(LTC_market)

# Add all technical indicators
LTC_market = add_all_ta_features(
    LTC_market, open="Open*", high="High", low="Low", close="Close**", volume="Volume", fillna=True
)

In [18]:
LTC_market

,Open*,High,Low,Close**,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,...,momentum_ppo,momentum_ppo_signal,momentum_ppo_hist,momentum_pvo,momentum_pvo_signal,momentum_pvo_hist,momentum_kama,others_dr,others_dlr,others_cr
Date,,,,,,,,,,,,,,,,,,,,,
2023-01-10,81.73,82.60,79.88,80.89,561103552,5825957315,-1.444016e+08,561103552,-0.257353,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,80.890000,0.000000,0.000000,0.000000
2023-01-09,77.68,83.29,77.68,81.75,879528523,5887263235,2.522485e+08,1440632075,0.175096,7.563945e+08,...,0.084745,0.016949,0.067796,4.344421,0.868884,3.475537,81.271781,1.063172,1.057560,1.063172
2023-01-08,76.37,77.68,75.53,77.68,384160222,5593945349,6.364087e+08,1056471853,0.348757,4.249764e+08,...,-0.251639,-0.036769,-0.214870,0.964625,0.888032,0.076593,79.949795,-4.978593,-5.106799,-3.968352
2023-01-07,75.99,76.60,75.67,76.37,332539243,5499144136,8.044662e+08,723932610,0.372899,3.020332e+08,...,-0.644563,-0.158327,-0.486235,-2.585484,0.193329,-2.778813,78.709847,-1.686406,-1.700788,-5.587835
2023-01-06,74.26,76.27,73.01,75.99,537790219,5471155488,1.249875e+09,186142391,0.463755,2.296913e+08,...,-0.985980,-0.323858,-0.662122,-2.401374,-0.325611,-2.075762,77.780587,-0.497578,-0.498820,-6.057609
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-05,3.49,3.51,3.45,3.47,2104650,152390643,3.518959e+11,-87596417040,-0.000912,3.519048e+04,...,3.000413,2.389240,0.611173,5.159473,11.951298,-6.791825,3.426695,0.579710,0.578036,-95.710224
2016-01-04,3.48,3.51,3.48,3.50,3309740,153467942,3.518970e+11,-87593107300,0.003361,4.434787e+04,...,2.912337,2.493859,0.418478,5.198991,10.600837,-5.401845,3.427636,0.864553,0.860837,-95.673136
2016-01-03,3.50,3.51,3.45,3.48,2406150,152873557,3.518970e+11,-87595513450,0.018760,3.113775e+04,...,2.763018,2.547691,0.215327,2.848045,9.050278,-6.202234,3.427854,-0.571429,-0.573067,-95.697861
2016-01-02,3.52,3.53,3.49,3.50,3020260,153658445,3.518955e+11,-87592493190,0.033292,3.531881e+04,...,2.660328,2.570218,0.090110,2.562606,7.752744,-5.190138,3.428316,0.574713,0.573067,-95.673136
2016-01-01,3.48,3.53,3.47,3.51,2791170,153910742,3.518964e+11,-87589702020,0.098578,3.426065e+04,...,2.571991,2.570573,0.001418,1.704415,6.543078,-4.838663,3.430297,0.285714,0.285307,-95.660774

In [19]:
from ta.momentum import RSIIndicator
from ta.trend import MACD
from ta.volatility import BollingerBands

# RSI
LTC_market['rsi'] = RSIIndicator(close=LTC_market['Close**'], window=14, fillna=True).rsi()

# MACD
macd = MACD(close=LTC_market['Close**'], window_slow=26, window_fast=12, window_sign=9, fillna=True)
LTC_market['macd'] = macd.macd()
LTC_market['macd_signal'] = macd.macd_signal()
LTC_market['macd_diff'] = macd.macd_diff()

# Bollinger Bands
indicator_bb = BollingerBands(close=LTC_market['Close**'], window=20, window_dev=2, fillna=True)
LTC_market['bb_bbm'] = indicator_bb.bollinger_mavg()
LTC_market['bb_bbh'] = indicator_bb.bollinger_hband()
LTC_market['bb_bbl'] = indicator_bb.bollinger_lband()

In [20]:
LTC_market

,Open*,High,Low,Close**,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,...,others_dr,others_dlr,others_cr,rsi,macd,macd_signal,macd_diff,bb_bbm,bb_bbh,bb_bbl
Date,,,,,,,,,,,,,,,,,,,,,
2023-01-10,81.73,82.60,79.88,80.89,561103552,5825957315,-1.444016e+08,561103552,-0.257353,0.000000e+00,...,0.000000,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,80.890000,80.890000,80.890000
2023-01-09,77.68,83.29,77.68,81.75,879528523,5887263235,2.522485e+08,1440632075,0.175096,7.563945e+08,...,1.063172,1.057560,1.063172,100.000000,0.068604,0.013721,0.054883,81.320000,82.180000,80.460000
2023-01-08,76.37,77.68,75.53,77.68,384160222,5593945349,6.364087e+08,1056471853,0.348757,4.249764e+08,...,-4.978593,-5.106799,-3.968352,16.402582,-0.203101,-0.029643,-0.173457,80.106667,83.609592,76.603741
2023-01-07,75.99,76.60,75.67,76.37,332539243,5499144136,8.044662e+08,723932610,0.372899,3.020332e+08,...,-1.686406,-1.700788,-5.587835,12.717441,-0.518161,-0.127347,-0.390814,79.172500,83.608137,74.736863
2023-01-06,74.26,76.27,73.01,75.99,537790219,5471155488,1.249875e+09,186142391,0.463755,2.296913e+08,...,-0.497578,-0.498820,-6.057609,11.883414,-0.789412,-0.259760,-0.529652,78.536000,83.250023,73.821977
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-05,3.49,3.51,3.45,3.47,2104650,152390643,3.518959e+11,-87596417040,-0.000912,3.519048e+04,...,0.579710,0.578036,-95.710224,57.079795,0.100193,0.079099,0.021094,3.317500,3.756493,2.878507
2016-01-04,3.48,3.51,3.48,3.50,3309740,153467942,3.518970e+11,-87593107300,0.003361,4.434787e+04,...,0.864553,0.860837,-95.673136,58.389737,0.097598,0.082798,0.014800,3.333500,3.774602,2.892398
2016-01-03,3.50,3.51,3.45,3.48,2406150,152873557,3.518970e+11,-87595513450,0.018760,3.113775e+04,...,-0.571429,-0.573067,-95.697861,57.137730,0.092858,0.084810,0.008048,3.352500,3.784374,2.920626
2016-01-02,3.52,3.53,3.49,3.50,3020260,153658445,3.518955e+11,-87592493190,0.033292,3.531881e+04,...,0.574713,0.573067,-95.673136,58.105151,0.089681,0.085784,0.003897,3.373500,3.790934,2.956066
2016-01-01,3.48,3.53,3.47,3.51,2791170,153910742,3.518964e+11,-87589702020,0.098578,3.426065e+04,...,0.285714,0.285307,-95.660774,58.608199,0.086968,0.086021,0.000947,3.388000,3.803240,2.972760

In [21]:
# Shift all columns except 'Date'
columns_to_shift = LTC_market.columns.difference(['Date'])
LTC_market[columns_to_shift] = LTC_market[columns_to_shift].shift(-1)

LTC_market.dropna(inplace=True)

In [22]:
Litecoin_final_dataset=LTC_market.join(LTC,how='inner')

In [23]:
Litecoin_final_dataset

,Open*,High,Low,Close**,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,...,BTC_Volume_binary,BTC_Market_Cap_binary,Tweets_Count_binary,Tweets_Vader_Sentiment_binary,News_Vader_Sentiment_binary,Litecoin_Change_lag_1,Litecoin_Change_lag_2,Litecoin_Change_lag_3,Litecoin_Change_lag_4,Litecoin_Change_lag_5
Date,,,,,,,,,,,,,,,,,,,,,
2022-12-31,66.75,68.33,66.32,67.99,324391932.0,4.891935e+09,1.927900e+09,-8.417107e+08,0.321134,-2.347370e+08,...,0,0,0,1,0,1.0,1.0,0.0,0.0,1.0
2022-12-30,66.34,67.17,65.93,66.75,337784432.0,4.801994e+09,2.036863e+09,-1.179495e+09,0.321211,-2.610393e+08,...,1,0,0,0,1,1.0,0.0,0.0,1.0,1.0
2022-12-29,68.75,69.22,66.11,66.34,457672812.0,4.771857e+09,1.646884e+09,-1.637168e+09,0.242229,-2.505545e+08,...,0,1,0,1,1,0.0,0.0,1.0,1.0,1.0
2022-12-28,70.68,70.84,67.97,68.75,440850738.0,4.944646e+09,1.445660e+09,-1.196317e+09,0.199684,-6.298239e+07,...,1,0,1,0,0,0.0,1.0,1.0,1.0,0.0
2022-12-27,69.21,70.83,68.71,70.68,457389047.0,5.083452e+09,1.838324e+09,-7.389282e+08,0.238833,7.212378e+07,...,1,0,1,1,0,1.0,1.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-10,3.57,3.59,3.54,3.56,2934720.0,1.565865e+08,3.518942e+11,-8.760415e+10,-0.023482,9.714967e+04,...,1,1,1,0,0,0.0,0.0,1.0,0.0,0.0
2016-01-09,3.60,3.64,3.53,3.57,3277990.0,1.569011e+08,3.518933e+11,-8.760087e+10,0.004660,8.795399e+04,...,0,0,0,1,0,0.0,1.0,0.0,0.0,1.0
2016-01-08,3.45,3.61,3.44,3.60,4560680.0,1.583995e+08,3.518973e+11,-8.759631e+10,0.015199,9.493491e+04,...,0,0,0,1,0,1.0,0.0,0.0,1.0,0.0
2016-01-07,3.47,3.47,3.44,3.45,2208860.0,1.517348e+08,3.518966e+11,-8.759852e+10,-0.005065,3.404006e+04,...,1,1,0,0,1,0.0,0.0,1.0,0.0,0.0
2016-01-06,3.49,3.51,3.45,3.47,2104650.0,1.523906e+08,3.518959e+11,-8.759642e+10,-0.000912,3.519048e+04,...,1,1,0,1,0,0.0,1.0,0.0,0.0,1.0

In [24]:
Litecoin_final_dataset.to_csv("Litecoin_final_dataset.csv")

In [25]:
import numpy as np
from pycaret.classification import *

# Initialize setup
clf = setup(data=Litecoin_final_dataset, target='Litecoin_Change', session_id=123)

In [26]:
best_model=compare_models()

In [27]:
LTC_market["Litecoin_Change"]=LTC["Litecoin_Change"]

In [30]:
LTC_market.dropna(inplace=True)

In [31]:
import numpy as np
from pycaret.classification import *

# Initialize setup
clf = setup(data=LTC_market, target='Litecoin_Change', session_id=123)

In [32]:
best_model=compare_models()

# Future Open

In [7]:
LTC_market['Future_Open'] = LTC_market['Open*'].shift(-1)  # Shift open price to the previous day for comparison
LTC_market['Price_Direction'] = (LTC_market['Future_Open'] > LTC_market['Open*']).astype(int)  # 1 if price increases, else 0
LTC_market.dropna(inplace=True)

In [8]:
LTC_market

,Open*,High,Low,Close**,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,...,momentum_ppo_hist,momentum_pvo,momentum_pvo_signal,momentum_pvo_hist,momentum_kama,others_dr,others_dlr,others_cr,Future_Open,Price_Direction
Date,,,,,,,,,,,,,,,,,,,,,
2023-01-10,81.73,82.60,79.88,80.89,561103552,5825957315,-1.444016e+08,561103552,-0.257353,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,80.890000,0.000000,0.000000,0.000000,77.68,0
2023-01-09,77.68,83.29,77.68,81.75,879528523,5887263235,2.522485e+08,1440632075,0.175096,7.563945e+08,...,0.067796,4.344421,0.868884,3.475537,81.271781,1.063172,1.057560,1.063172,76.37,0
2023-01-08,76.37,77.68,75.53,77.68,384160222,5593945349,6.364087e+08,1056471853,0.348757,4.249764e+08,...,-0.214870,0.964625,0.888032,0.076593,79.949795,-4.978593,-5.106799,-3.968352,75.99,0
2023-01-07,75.99,76.60,75.67,76.37,332539243,5499144136,8.044662e+08,723932610,0.372899,3.020332e+08,...,-0.486235,-2.585484,0.193329,-2.778813,78.709847,-1.686406,-1.700788,-5.587835,74.26,0
2023-01-06,74.26,76.27,73.01,75.99,537790219,5471155488,1.249875e+09,186142391,0.463755,2.296913e+08,...,-0.662122,-2.401374,-0.325611,-2.075762,77.780587,-0.497578,-0.498820,-6.057609,75.43,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-06,3.47,3.47,3.44,3.45,2208860,151734839,3.518966e+11,-87598521690,-0.005065,3.404006e+04,...,0.920849,8.884978,13.649254,-4.764276,3.417742,-4.166667,-4.255961,-95.734949,3.49,1
2016-01-05,3.49,3.51,3.45,3.47,2104650,152390643,3.518959e+11,-87596417040,-0.000912,3.519048e+04,...,0.611173,5.159473,11.951298,-6.791825,3.426695,0.579710,0.578036,-95.710224,3.48,0
2016-01-04,3.48,3.51,3.48,3.50,3309740,153467942,3.518970e+11,-87593107300,0.003361,4.434787e+04,...,0.418478,5.198991,10.600837,-5.401845,3.427636,0.864553,0.860837,-95.673136,3.50,1
2016-01-03,3.50,3.51,3.45,3.48,2406150,152873557,3.518970e+11,-87595513450,0.018760,3.113775e+04,...,0.215327,2.848045,9.050278,-6.202234,3.427854,-0.571429,-0.573067,-95.697861,3.52,1
2016-01-02,3.52,3.53,3.49,3.50,3020260,153658445,3.518955e+11,-87592493190,0.033292,3.531881e+04,...,0.090110,2.562606,7.752744,-5.190138,3.428316,0.574713,0.573067,-95.673136,3.48,0

In [9]:
LTC_market.drop(["Future_Open"],axis=1,inplace=True)

In [10]:
# Shift all columns except 'Date'
columns_to_shift = LTC_market.columns.difference(['Date','Price_Direction'])
LTC_market[columns_to_shift] = LTC_market[columns_to_shift].shift(-1)

LTC_market.dropna(inplace=True)

In [11]:
LTC_market

,Open*,High,Low,Close**,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,...,momentum_ppo_signal,momentum_ppo_hist,momentum_pvo,momentum_pvo_signal,momentum_pvo_hist,momentum_kama,others_dr,others_dlr,others_cr,Price_Direction
Date,,,,,,,,,,,,,,,,,,,,,
2023-01-10,77.68,83.29,77.68,81.75,879528523.0,5.887263e+09,2.522485e+08,1.440632e+09,0.175096,7.563945e+08,...,0.016949,0.067796,4.344421,0.868884,3.475537,81.271781,1.063172,1.057560,1.063172,0
2023-01-09,76.37,77.68,75.53,77.68,384160222.0,5.593945e+09,6.364087e+08,1.056472e+09,0.348757,4.249764e+08,...,-0.036769,-0.214870,0.964625,0.888032,0.076593,79.949795,-4.978593,-5.106799,-3.968352,0
2023-01-08,75.99,76.60,75.67,76.37,332539243.0,5.499144e+09,8.044662e+08,7.239326e+08,0.372899,3.020332e+08,...,-0.158327,-0.486235,-2.585484,0.193329,-2.778813,78.709847,-1.686406,-1.700788,-5.587835,0
2023-01-07,74.26,76.27,73.01,75.99,537790219.0,5.471155e+09,1.249875e+09,1.861424e+08,0.463755,2.296913e+08,...,-0.323858,-0.662122,-2.401374,-0.325611,-2.075762,77.780587,-0.497578,-0.498820,-6.057609,0
2023-01-06,75.43,76.17,73.91,74.25,432215597.0,5.345242e+09,9.477068e+08,-2.460732e+08,0.303040,8.944177e+07,...,-0.543325,-0.877866,-3.814773,-1.023444,-2.791329,76.667048,-2.289775,-2.316397,-8.208678,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-07,3.47,3.47,3.44,3.45,2208860.0,1.517348e+08,3.518966e+11,-8.759852e+10,-0.005065,3.404006e+04,...,2.236446,0.920849,8.884978,13.649254,-4.764276,3.417742,-4.166667,-4.255961,-95.734949,1
2016-01-06,3.49,3.51,3.45,3.47,2104650.0,1.523906e+08,3.518959e+11,-8.759642e+10,-0.000912,3.519048e+04,...,2.389240,0.611173,5.159473,11.951298,-6.791825,3.426695,0.579710,0.578036,-95.710224,1
2016-01-05,3.48,3.51,3.48,3.50,3309740.0,1.534679e+08,3.518970e+11,-8.759311e+10,0.003361,4.434787e+04,...,2.493859,0.418478,5.198991,10.600837,-5.401845,3.427636,0.864553,0.860837,-95.673136,0
2016-01-04,3.50,3.51,3.45,3.48,2406150.0,1.528736e+08,3.518970e+11,-8.759551e+10,0.018760,3.113775e+04,...,2.547691,0.215327,2.848045,9.050278,-6.202234,3.427854,-0.571429,-0.573067,-95.697861,1
2016-01-03,3.52,3.53,3.49,3.50,3020260.0,1.536584e+08,3.518955e+11,-8.759249e+10,0.033292,3.531881e+04,...,2.570218,0.090110,2.562606,7.752744,-5.190138,3.428316,0.574713,0.573067,-95.673136,1

In [12]:
import numpy as np
from pycaret.classification import *

# Initialize setup
clf = setup(data=LTC_market, target='Price_Direction', session_id=123)

In [13]:
best_model=compare_models()

# Future Close

In [20]:
LTC_market['Future_Close'] = LTC_market['Close**'].shift(-1)  # Shift closing price to the previous day for comparison
LTC_market['Price_Direction'] = (LTC_market['Future_Close'] > LTC_market['Close**']).astype(int)  # 1 if price increases, else 0
LTC_market.dropna(inplace=True)

In [21]:
LTC_market

,Open*,High,Low,Close**,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,...,momentum_ppo_hist,momentum_pvo,momentum_pvo_signal,momentum_pvo_hist,momentum_kama,others_dr,others_dlr,others_cr,Future_Close,Price_Direction
Date,,,,,,,,,,,,,,,,,,,,,
2023-01-10,81.73,82.60,79.88,80.89,561103552,5825957315,-1.444016e+08,561103552,-0.257353,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,80.890000,0.000000,0.000000,0.000000,81.75,1
2023-01-09,77.68,83.29,77.68,81.75,879528523,5887263235,2.522485e+08,1440632075,0.175096,7.563945e+08,...,0.067796,4.344421,0.868884,3.475537,81.271781,1.063172,1.057560,1.063172,77.68,0
2023-01-08,76.37,77.68,75.53,77.68,384160222,5593945349,6.364087e+08,1056471853,0.348757,4.249764e+08,...,-0.214870,0.964625,0.888032,0.076593,79.949795,-4.978593,-5.106799,-3.968352,76.37,0
2023-01-07,75.99,76.60,75.67,76.37,332539243,5499144136,8.044662e+08,723932610,0.372899,3.020332e+08,...,-0.486235,-2.585484,0.193329,-2.778813,78.709847,-1.686406,-1.700788,-5.587835,75.99,0
2023-01-06,74.26,76.27,73.01,75.99,537790219,5471155488,1.249875e+09,186142391,0.463755,2.296913e+08,...,-0.662122,-2.401374,-0.325611,-2.075762,77.780587,-0.497578,-0.498820,-6.057609,74.25,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-06,3.47,3.47,3.44,3.45,2208860,151734839,3.518966e+11,-87598521690,-0.005065,3.404006e+04,...,0.920849,8.884978,13.649254,-4.764276,3.417742,-4.166667,-4.255961,-95.734949,3.47,1
2016-01-05,3.49,3.51,3.45,3.47,2104650,152390643,3.518959e+11,-87596417040,-0.000912,3.519048e+04,...,0.611173,5.159473,11.951298,-6.791825,3.426695,0.579710,0.578036,-95.710224,3.50,1
2016-01-04,3.48,3.51,3.48,3.50,3309740,153467942,3.518970e+11,-87593107300,0.003361,4.434787e+04,...,0.418478,5.198991,10.600837,-5.401845,3.427636,0.864553,0.860837,-95.673136,3.48,0
2016-01-03,3.50,3.51,3.45,3.48,2406150,152873557,3.518970e+11,-87595513450,0.018760,3.113775e+04,...,0.215327,2.848045,9.050278,-6.202234,3.427854,-0.571429,-0.573067,-95.697861,3.50,1
2016-01-02,3.52,3.53,3.49,3.50,3020260,153658445,3.518955e+11,-87592493190,0.033292,3.531881e+04,...,0.090110,2.562606,7.752744,-5.190138,3.428316,0.574713,0.573067,-95.673136,3.51,1

In [22]:
LTC_market.drop(["Future_Close"],axis=1,inplace=True)

In [23]:
# Shift all columns except 'Date'
columns_to_shift = LTC_market.columns.difference(['Date','Price_Direction'])
LTC_market[columns_to_shift] = LTC_market[columns_to_shift].shift(-1)

LTC_market.dropna(inplace=True)

In [24]:
LTC_market

,Open*,High,Low,Close**,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,...,momentum_ppo_signal,momentum_ppo_hist,momentum_pvo,momentum_pvo_signal,momentum_pvo_hist,momentum_kama,others_dr,others_dlr,others_cr,Price_Direction
Date,,,,,,,,,,,,,,,,,,,,,
2023-01-10,77.68,83.29,77.68,81.75,879528523.0,5.887263e+09,2.522485e+08,1.440632e+09,0.175096,7.563945e+08,...,0.016949,0.067796,4.344421,0.868884,3.475537,81.271781,1.063172,1.057560,1.063172,1
2023-01-09,76.37,77.68,75.53,77.68,384160222.0,5.593945e+09,6.364087e+08,1.056472e+09,0.348757,4.249764e+08,...,-0.036769,-0.214870,0.964625,0.888032,0.076593,79.949795,-4.978593,-5.106799,-3.968352,0
2023-01-08,75.99,76.60,75.67,76.37,332539243.0,5.499144e+09,8.044662e+08,7.239326e+08,0.372899,3.020332e+08,...,-0.158327,-0.486235,-2.585484,0.193329,-2.778813,78.709847,-1.686406,-1.700788,-5.587835,0
2023-01-07,74.26,76.27,73.01,75.99,537790219.0,5.471155e+09,1.249875e+09,1.861424e+08,0.463755,2.296913e+08,...,-0.323858,-0.662122,-2.401374,-0.325611,-2.075762,77.780587,-0.497578,-0.498820,-6.057609,0
2023-01-06,75.43,76.17,73.91,74.25,432215597.0,5.345242e+09,9.477068e+08,-2.460732e+08,0.303040,8.944177e+07,...,-0.543325,-0.877866,-3.814773,-1.023444,-2.791329,76.667048,-2.289775,-2.316397,-8.208678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-07,3.47,3.47,3.44,3.45,2208860.0,1.517348e+08,3.518966e+11,-8.759852e+10,-0.005065,3.404006e+04,...,2.236446,0.920849,8.884978,13.649254,-4.764276,3.417742,-4.166667,-4.255961,-95.734949,0
2016-01-06,3.49,3.51,3.45,3.47,2104650.0,1.523906e+08,3.518959e+11,-8.759642e+10,-0.000912,3.519048e+04,...,2.389240,0.611173,5.159473,11.951298,-6.791825,3.426695,0.579710,0.578036,-95.710224,1
2016-01-05,3.48,3.51,3.48,3.50,3309740.0,1.534679e+08,3.518970e+11,-8.759311e+10,0.003361,4.434787e+04,...,2.493859,0.418478,5.198991,10.600837,-5.401845,3.427636,0.864553,0.860837,-95.673136,1
2016-01-04,3.50,3.51,3.45,3.48,2406150.0,1.528736e+08,3.518970e+11,-8.759551e+10,0.018760,3.113775e+04,...,2.547691,0.215327,2.848045,9.050278,-6.202234,3.427854,-0.571429,-0.573067,-95.697861,0
2016-01-03,3.52,3.53,3.49,3.50,3020260.0,1.536584e+08,3.518955e+11,-8.759249e+10,0.033292,3.531881e+04,...,2.570218,0.090110,2.562606,7.752744,-5.190138,3.428316,0.574713,0.573067,-95.673136,1

In [25]:
LTC_market.columns.values

array(['Open*', 'High', 'Low', 'Close**', 'Volume', 'Market Cap',
       'volume_adi', 'volume_obv', 'volume_cmf', 'volume_fi', 'volume_em',
       'volume_sma_em', 'volume_vpt', 'volume_vwap', 'volume_mfi',
       'volume_nvi', 'volatility_bbm', 'volatility_bbh', 'volatility_bbl',
       'volatility_bbw', 'volatility_bbp', 'volatility_bbhi',
       'volatility_bbli', 'volatility_kcc', 'volatility_kch',
       'volatility_kcl', 'volatility_kcw', 'volatility_kcp',
       'volatility_kchi', 'volatility_kcli', 'volatility_dcl',
       'volatility_dch', 'volatility_dcm', 'volatility_dcw',
       'volatility_dcp', 'volatility_atr', 'volatility_ui', 'trend_macd',
       'trend_macd_signal', 'trend_macd_diff', 'trend_sma_fast',
       'trend_sma_slow', 'trend_ema_fast', 'trend_ema_slow',
       'trend_vortex_ind_pos', 'trend_vortex_ind_neg',
       'trend_vortex_ind_diff', 'trend_trix', 'trend_mass_index',
       'trend_dpo', 'trend_kst', 'trend_kst_sig', 'trend_kst_diff',
       'trend_ichimoku_conv', 'trend_ichimoku_base', 'trend_ichimoku_a',
       'trend_ichimoku_b', 'trend_stc', 'trend_adx', 'trend_adx_pos',
       'trend_adx_neg', 'trend_cci', 'trend_visual_ichimoku_a',
       'trend_visual_ichimoku_b', 'trend_aroon_up', 'trend_aroon_down',
       'trend_aroon_ind', 'trend_psar_up', 'trend_psar_down',
       'trend_psar_up_indicator', 'trend_psar_down_indicator',
       'momentum_rsi', 'momentum_stoch_rsi', 'momentum_stoch_rsi_k',
       'momentum_stoch_rsi_d', 'momentum_tsi', 'momentum_uo',
       'momentum_stoch', 'momentum_stoch_signal', 'momentum_wr',
       'momentum_ao', 'momentum_roc', 'momentum_ppo',
       'momentum_ppo_signal', 'momentum_ppo_hist', 'momentum_pvo',
       'momentum_pvo_signal', 'momentum_pvo_hist', 'momentum_kama',
       'others_dr', 'others_dlr', 'others_cr', 'Price_Direction'],
      dtype=object)

In [26]:
import numpy as np
from pycaret.classification import *

# Initialize setup
clf = setup(data=LTC_market, target='Price_Direction', session_id=123)

In [27]:
best_model=compare_models()