In [1]:
import pandas as pd

In [2]:
BNB=pd.read_excel(r"C:\Users\sdas1\Desktop\TCD\Dissertation\Altcoin\Altcoin-Price-Prediction\Binance\0 day lag individual.xlsx")

In [3]:
BNB['Date'] = pd.to_datetime(BNB['Date'])
BNB.set_index('Date', inplace=True)

In [4]:
BNB

,Gold_Price,Oil_Price,Nasdaq_Change_bin_0day,Nasdaq_Volume,S&P500_Change_Bin_0day,S&P500_Volume,BTC_Change_Bin_0day,BTC_Volume,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Binance_change
Date,,,,,,,,,,,,
2017-08-01,1276.1,49.16,0,1821780000,0,3470260000,0,1.232876e+09,25194,0.071988,-0.046656,0
2017-08-02,1275.1,49.59,0,2115870000,0,3487150000,0,9.440169e+08,23821,0.081365,0.000000,1
2017-08-03,1271.1,49.03,0,2124100000,0,3662410000,1,9.519068e+08,21192,0.100593,0.036089,1
2017-08-04,1261.3,49.58,1,1908930000,0,3239980000,1,1.595064e+09,19444,0.089727,-0.060275,1
2017-08-05,1261.3,49.58,1,1908930000,0,3239980000,1,1.406396e+09,18068,0.096537,0.000000,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-27,1797.7,75.89,0,3827290000,0,3030300000,0,1.574858e+10,39816,0.097602,-0.054126,1
2022-12-28,1797.7,75.89,0,3842970000,0,3083520000,0,1.700571e+10,42534,0.084050,-0.066367,0
2022-12-29,1797.7,75.89,1,4154100000,1,3003680000,1,1.447224e+10,41316,0.099584,-0.052279,1
2022-12-30,1797.7,75.89,1,3959030000,1,2979870000,0,1.592916e+10,40485,0.095240,-0.024360,0
2022-12-31,1797.7,75.89,1,3959030000,1,2979870000,0,1.123919e+10,35625,0.119512,-0.068864,1

In [5]:
BNB.drop(["Nasdaq_Volume","S&P500_Volume"],inplace=True,axis=1)

In [6]:
BNB

,Gold_Price,Oil_Price,Nasdaq_Change_bin_0day,S&P500_Change_Bin_0day,BTC_Change_Bin_0day,BTC_Volume,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Binance_change
Date,,,,,,,,,,
2017-08-01,1276.1,49.16,0,0,0,1.232876e+09,25194,0.071988,-0.046656,0
2017-08-02,1275.1,49.59,0,0,0,9.440169e+08,23821,0.081365,0.000000,1
2017-08-03,1271.1,49.03,0,0,1,9.519068e+08,21192,0.100593,0.036089,1
2017-08-04,1261.3,49.58,1,0,1,1.595064e+09,19444,0.089727,-0.060275,1
2017-08-05,1261.3,49.58,1,0,1,1.406396e+09,18068,0.096537,0.000000,1
...,...,...,...,...,...,...,...,...,...,...
2022-12-27,1797.7,75.89,0,0,0,1.574858e+10,39816,0.097602,-0.054126,1
2022-12-28,1797.7,75.89,0,0,0,1.700571e+10,42534,0.084050,-0.066367,0
2022-12-29,1797.7,75.89,1,1,1,1.447224e+10,41316,0.099584,-0.052279,1
2022-12-30,1797.7,75.89,1,1,0,1.592916e+10,40485,0.095240,-0.024360,0
2022-12-31,1797.7,75.89,1,1,0,1.123919e+10,35625,0.119512,-0.068864,1

In [6]:
Base_BNB = pd.read_excel(r"C:\Users\sdas1\Desktop\TCD\Dissertation\Altcoin\Altcoin-Price-Prediction\New_Experiments\Base_Datasets\Alt_Coin_Yearly_Rank.xlsx", sheet_name = 'Binance_Coin_Daily')

In [7]:
Base_BNB

,Date,Open*,High,Low,Close**,Volume,Market Cap
0,"Jan 10, 2023",$272.66,$278.27,$271.15,$277.29,"$470,259,383","$44,356,071,739"
1,"Jan 09, 2023",$274.44,$283.03,$271.90,$272.70,"$783,671,054","$43,622,192,228"
2,"Jan 08, 2023",$261.25,$274.39,$260.52,$274.39,"$491,734,030","$43,891,548,404"
3,"Jan 07, 2023",$259.85,$262.96,$259.59,$261.28,"$327,712,514","$41,795,720,412"
4,"Jan 06, 2023",$256.45,$260.22,$255.07,$259.87,"$417,893,264","$41,569,303,200"
...,...,...,...,...,...,...,...
1991,"Jul 29, 2017",$0.1048,$0.1113,$0.1011,$0.1078,"$340,218","$10,781,100"
1992,"Jul 28, 2017",$0.1076,$0.109,$0.1015,$0.1041,"$342,568","$10,406,700"
1993,"Jul 27, 2017",$0.1051,$0.1085,$0.1009,$0.1077,"$344,499","$10,773,700"
1994,"Jul 26, 2017",$0.1059,$0.109,$0.09927,$0.1051,"$200,395","$10,513,800"
1995,"Jul 25, 2017",$0.1152,$0.1158,$0.1015,$0.1059,"$145,269","$10,587,000"

In [8]:
Base_BNB['Date'] = pd.to_datetime(Base_BNB['Date'])
Base_BNB.set_index('Date', inplace=True)

In [9]:
# Convert columns to float, removing any non-numeric characters like commas
Base_BNB['Open*'] = pd.to_numeric(Base_BNB['Open*'].replace('[^\d.]', '', regex=True), errors='coerce')
Base_BNB['High'] = pd.to_numeric(Base_BNB['High'].replace('[^\d.]', '', regex=True), errors='coerce')
Base_BNB['Low'] = pd.to_numeric(Base_BNB['Low'].replace('[^\d.]', '', regex=True), errors='coerce')
Base_BNB['Close**'] = pd.to_numeric(Base_BNB['Close**'].replace('[^\d.]', '', regex=True), errors='coerce')
Base_BNB['Volume'] = pd.to_numeric(Base_BNB['Volume'].replace('[^\d.]', '', regex=True), errors='coerce')
Base_BNB['Market Cap'] = pd.to_numeric(Base_BNB['Market Cap'].replace('[^\d.]', '', regex=True), errors='coerce')

In [10]:
Base_BNB

               Open*      High        Low   Close**     Volume   Market Cap
Date
2023-01-10  272.6600  278.2700  271.15000  277.2900  470259383  44356071739
2023-01-09  274.4400  283.0300  271.90000  272.7000  783671054  43622192228
2023-01-08  261.2500  274.3900  260.52000  274.3900  491734030  43891548404
2023-01-07  259.8500  262.9600  259.59000  261.2800  327712514  41795720412
2023-01-06  256.4500  260.2200  255.07000  259.8700  417893264  41569303200
...              ...       ...        ...       ...        ...          ...
2017-07-29    0.1048    0.1113    0.10110    0.1078     340218     10781100
2017-07-28    0.1076    0.1090    0.10150    0.1041     342568     10406700
2017-07-27    0.1051    0.1085    0.10090    0.1077     344499     10773700
2017-07-26    0.1059    0.1090    0.09927    0.1051     200395     10513800
2017-07-25    0.1152    0.1158    0.10150    0.1059     145269     10587000

[1996 rows x 6 columns]

In [11]:
from ta import add_all_ta_features
from ta.utils import dropna

# Clean NaN values
Base_BNB = dropna(Base_BNB)

# Add all technical indicators
Base_BNB = add_all_ta_features(
    Base_BNB, open="Open*", high="High", low="Low", close="Close**", volume="Volume", fillna=True
)

C:\Users\sdas1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\ta\trend.py:1030: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  self._psar[i] = high2

# Specific Technical indicators with specification

In [13]:
from ta.momentum import RSIIndicator
from ta.trend import MACD
from ta.volatility import BollingerBands

# RSI
Base_BNB['rsi'] = RSIIndicator(close=Base_BNB['Close**'], window=14, fillna=True).rsi()

# MACD
macd = MACD(close=Base_BNB['Close**'], window_slow=26, window_fast=12, window_sign=9, fillna=True)
Base_BNB['macd'] = macd.macd()
Base_BNB['macd_signal'] = macd.macd_signal()
Base_BNB['macd_diff'] = macd.macd_diff()

# Bollinger Bands
indicator_bb = BollingerBands(close=Base_BNB['Close**'], window=20, window_dev=2, fillna=True)
Base_BNB['bb_bbm'] = indicator_bb.bollinger_mavg()
Base_BNB['bb_bbh'] = indicator_bb.bollinger_hband()
Base_BNB['bb_bbl'] = indicator_bb.bollinger_lband()

In [14]:
Base_BNB

,Open*,High,Low,Close**,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,...,others_dr,others_dlr,others_cr,rsi,macd,macd_signal,macd_diff,bb_bbm,bb_bbh,bb_bbl
Date,,,,,,,,,,,,,,,,,,,,,
2023-01-10,272.6600,278.2700,271.15000,277.2900,470259383,44356071739,3.408060e+08,470259383,0.724719,0.000000e+00,...,0.000000,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,277.290000,277.290000,277.290000
2023-01-09,274.4400,283.0300,271.90000,272.7000,783671054,43622192228,-3.302080e+08,-313411671,-0.263338,-3.597050e+09,...,-1.655307,-1.669160,-1.655307,0.000000,-0.366154,-0.073231,-0.292923,274.995000,279.585000,270.405000
2023-01-08,261.2500,274.3900,260.52000,274.3900,491734030,43891548404,1.615260e+08,178322359,0.092530,-2.964467e+09,...,0.619729,0.617816,-1.045836,28.393136,-0.514039,-0.161392,-0.352647,274.793333,278.584211,271.002455
2023-01-07,259.8500,262.9600,259.59000,261.2800,327712514,41795720412,1.624985e+08,-149390155,0.078374,-3.154731e+09,...,-4.777871,-4.895782,-5.773739,8.420275,-1.669857,-0.463085,-1.206772,271.415000,283.569658,259.260342
2023-01-06,256.4500,260.2200,255.07000,259.8700,417893264,41569303200,5.235907e+08,-567283419,0.210170,-2.788230e+09,...,-0.539651,-0.541112,-6.282232,7.785912,-2.668862,-0.904241,-1.764621,269.106000,283.371071,254.840929
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-07-29,0.1048,0.1113,0.10110,0.1078,340218,10781100,1.825375e+11,-24570673219,0.553229,-3.143992e+05,...,1.315789,1.307208,-99.961124,29.513863,-0.401613,-0.401931,0.000318,0.472188,1.548756,-0.604379
2017-07-28,0.1076,0.1090,0.10150,0.1041,342568,10406700,1.825374e+11,-24571015787,0.510700,-2.696661e+05,...,-3.432282,-3.492568,-99.962458,29.436383,-0.384372,-0.398419,0.014047,0.378893,1.217100,-0.459313
2017-07-27,0.1051,0.1085,0.10090,0.1077,344499,10773700,1.825377e+11,-24570671288,0.386339,-2.309652e+05,...,3.458213,3.399761,-99.961160,29.629953,-0.366197,-0.391974,0.025778,0.312279,1.001017,-0.376460
2017-07-26,0.1059,0.1090,0.09927,0.1051,200395,10513800,1.825377e+11,-24570871683,0.560714,-1.980446e+05,...,-2.414113,-2.443731,-99.962097,29.566869,-0.347991,-0.383178,0.035187,0.264534,0.866206,-0.337139
2017-07-25,0.1152,0.1158,0.10150,0.1059,145269,10587000,1.825377e+11,-24570726414,0.560612,-1.697359e+05,...,0.761180,0.758297,-99.961809,29.616524,-0.329698,-0.372482,0.042784,0.204828,0.576776,-0.167119

In [15]:
Base_BNB.drop(["Open*","High","Low","Close**"],inplace=True,axis=1)

In [16]:
Base_BNB

,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,volume_em,volume_sma_em,volume_vpt,volume_vwap,...,others_dr,others_dlr,others_cr,rsi,macd,macd_signal,macd_diff,bb_bbm,bb_bbh,bb_bbl
Date,,,,,,,,,,,,,,,,,,,,,
2023-01-10,470259383,44356071739,3.408060e+08,470259383,0.724719,0.000000e+00,0.000000,0.000000,0.000000e+00,275.570000,...,0.000000,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,277.290000,277.290000,277.290000
2023-01-09,783671054,43622192228,-3.302080e+08,-313411671,-0.263338,-3.597050e+09,3.912758,3.912758,-1.297216e+07,275.761658,...,-1.655307,-1.669160,-1.655307,0.000000,-0.366154,-0.073231,-0.292923,274.995000,279.585000,270.405000
2023-01-08,491734030,43891548404,1.615260e+08,178322359,0.092530,-2.964467e+09,-28.234511,-12.160877,-9.924743e+06,274.072936,...,0.619729,0.617816,-1.045836,28.393136,-0.514039,-0.161392,-0.352647,274.793333,278.584211,271.002455
2023-01-07,327712514,41795720412,1.624985e+08,-149390155,0.078374,-3.154731e+09,-6.355143,-10.225632,-2.558242e+07,272.050392,...,-4.777871,-4.895782,-5.773739,8.420275,-1.669857,-0.463085,-1.206772,271.415000,283.569658,259.260342
2023-01-06,417893264,41569303200,5.235907e+08,-567283419,0.210170,-2.788230e+09,-4.473511,-8.787602,-2.783759e+07,269.758397,...,-0.539651,-0.541112,-6.282232,7.785912,-2.668862,-0.904241,-1.764621,269.106000,283.371071,254.840929
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-07-29,340218,10781100,1.825375e+11,-24570673219,0.553229,-3.143992e+05,0.001649,-0.048011,2.839313e+09,0.259407,...,1.315789,1.307208,-99.961124,29.513863,-0.401613,-0.401931,0.000318,0.472188,1.548756,-0.604379
2017-07-28,342568,10406700,1.825374e+11,-24571015787,0.510700,-2.696661e+05,-0.002080,-0.040756,2.839302e+09,0.219780,...,-3.432282,-3.492568,-99.962458,29.436383,-0.384372,-0.398419,0.014047,0.378893,1.217100,-0.459313
2017-07-27,344499,10773700,1.825377e+11,-24570671288,0.386339,-2.309652e+05,-0.001213,-0.029407,2.839314e+09,0.176778,...,3.458213,3.399761,-99.961160,29.629953,-0.366197,-0.391974,0.025778,0.312279,1.001017,-0.376460
2017-07-26,200395,10513800,1.825377e+11,-24570871683,0.560714,-1.980446e+05,-0.002743,-0.024595,2.839309e+09,0.146665,...,-2.414113,-2.443731,-99.962097,29.566869,-0.347991,-0.383178,0.035187,0.264534,0.866206,-0.337139
2017-07-25,145269,10587000,1.825377e+11,-24570726414,0.560612,-1.697359e+05,0.044445,-0.009752,2.839310e+09,0.115665,...,0.761180,0.758297,-99.961809,29.616524,-0.329698,-0.372482,0.042784,0.204828,0.576776,-0.167119

In [17]:
#market vap btc missing
Base_BNB[["Gold_Price","Oil_Price","Nasdaq_Change_bin_0day","S&P500_Change_Bin_0day","BTC_Change_Bin_0day","BTC_Volume","Tweets_Count","Tweets_Vader_Sentiment","News_Vader_Sentiment","Binance_change"]]=BNB[["Gold_Price","Oil_Price","Nasdaq_Change_bin_0day","S&P500_Change_Bin_0day","BTC_Change_Bin_0day","BTC_Volume","Tweets_Count","Tweets_Vader_Sentiment","News_Vader_Sentiment","Binance_change"]]
Base_BNB

C:\Users\sdas1\AppData\Local\Temp\ipykernel_15940\3746069019.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Base_BNB[["Gold_Price","Oil_Price","Nasdaq_Change_bin_0day","S&P500_Change_Bin_0day","BTC_Change_Bin_0day","BTC_Volume","Tweets_Count","Tweets_Vader_Sentiment","News_Vader_Sentiment","Binance_change"]]=BNB[["Gold_Price","Oil_Price","Nasdaq_Change_bin_0day","S&P500_Change_Bin_0day","BTC_Change_Bin_0day","BTC_Volume","Tweets_Count","Tweets_Vader_Sentiment","News_Vader_Sentiment","Binance_change"]]
C:\Users\sdas1\AppData\Local\Temp\ipykernel_15940\3746069019.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Base_BNB[["Gold_Price","Oil_Price","Nasdaq_Change_bin_0day","S&P500_Change_Bin_0day","BTC_Change_Bin_0day","BTC_Volume","Tweets_Count","Tweets_Vader_Sentiment","News_Vader_Sentiment","Binance_change"]]=BNB[["Gold_Price","Oil_Price","Nasdaq_Change_bin_0day","S&P500_Change_Bin_0day","BTC_Change_Bin_0day","BTC_Volume","Tweets_Count","Tweets_Vader_Sentiment","News_Vader_Sentiment","Binance_change"]]
C:\Users\sdas1\AppData\Local\Temp\ipykernel_15940\3746069019.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Base_BNB[["Gold_Price","Oil_Price","Nasdaq_Change_bin_0day","S&P500_Change_Bin_0day","BTC_Change_Bin_0day","BTC_Volume","Tweets_Count","Tweets_Vader_Sentiment","News_Vader_Sentiment","Binance_change"]]=BNB[["Gold_Price","Oil_Price","Nasdaq_Change_bin_0day","S&P500_Change_Bin_0day","BTC_Change_Bin_0day","BTC_Volume","Tweets_Count","Tweets_Vader_Sentiment","News_Vader_Sentiment","Binance_change"]]
C:\Users\sdas1\AppData\Local\Temp\ipykernel_15940\3746069019.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Base_BNB[["Gold_Price","Oil_Price","Nasdaq_Change_bin_0day","S&P500_Change_Bin_0day","BTC_Change_Bin_0day","BTC_Volume","Tweets_Count","Tweets_Vader_Sentiment","News_Vader_Sentiment","Binance_change"]]=BNB[["Gold_Price","Oil_Price","Nasdaq_Change_bin_0day","S&P500_Change_Bin_0day","BTC_Change_Bin_0day","BTC_Volume","Tweets_Count","Tweets_Vader_Sentiment","News_Vader_Sentiment","Binance_change"]]

,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,volume_em,volume_sma_em,volume_vpt,volume_vwap,...,Gold_Price,Oil_Price,Nasdaq_Change_bin_0day,S&P500_Change_Bin_0day,BTC_Change_Bin_0day,BTC_Volume,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Binance_change
Date,,,,,,,,,,,,,,,,,,,,,
2023-01-10,470259383,44356071739,3.408060e+08,470259383,0.724719,0.000000e+00,0.000000,0.000000,0.000000e+00,275.570000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-01-09,783671054,43622192228,-3.302080e+08,-313411671,-0.263338,-3.597050e+09,3.912758,3.912758,-1.297216e+07,275.761658,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-01-08,491734030,43891548404,1.615260e+08,178322359,0.092530,-2.964467e+09,-28.234511,-12.160877,-9.924743e+06,274.072936,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-01-07,327712514,41795720412,1.624985e+08,-149390155,0.078374,-3.154731e+09,-6.355143,-10.225632,-2.558242e+07,272.050392,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-01-06,417893264,41569303200,5.235907e+08,-567283419,0.210170,-2.788230e+09,-4.473511,-8.787602,-2.783759e+07,269.758397,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-07-29,340218,10781100,1.825375e+11,-24570673219,0.553229,-3.143992e+05,0.001649,-0.048011,2.839313e+09,0.259407,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-07-28,342568,10406700,1.825374e+11,-24571015787,0.510700,-2.696661e+05,-0.002080,-0.040756,2.839302e+09,0.219780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-07-27,344499,10773700,1.825377e+11,-24570671288,0.386339,-2.309652e+05,-0.001213,-0.029407,2.839314e+09,0.176778,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-07-26,200395,10513800,1.825377e+11,-24570871683,0.560714,-1.980446e+05,-0.002743,-0.024595,2.839309e+09,0.146665,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-07-25,145269,10587000,1.825377e+11,-24570726414,0.560612,-1.697359e+05,0.044445,-0.009752,2.839310e+09,0.115665,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
Base_BNB.dropna(inplace=True)

In [19]:
Base_BNB

,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,volume_em,volume_sma_em,volume_vpt,volume_vwap,...,Gold_Price,Oil_Price,Nasdaq_Change_bin_0day,S&P500_Change_Bin_0day,BTC_Change_Bin_0day,BTC_Volume,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Binance_change
Date,,,,,,,,,,,,,,,,,,,,,
2022-12-31,307551853,39407173516,9.042078e+08,-983578055,0.188828,-1.466070e+09,1.052083,-4.978942,-4.431034e+07,260.221210,...,1797.7,75.89,1.0,1.0,0.0,1.123919e+10,35625.0,0.119512,-0.068864,1.0
2022-12-30,342300809,39316042284,1.100244e+09,-1325878864,0.214438,-1.284504e+09,-1.506307,-4.663248,-4.510235e+07,259.214850,...,1797.7,75.89,1.0,1.0,0.0,1.592916e+10,40485.0,0.095240,-0.024360,0.0
2022-12-29,345312528,39428145950,1.418114e+09,-980566336,0.258963,-1.066472e+09,0.240507,-4.254602,-4.411887e+07,258.353386,...,1797.7,75.89,1.0,1.0,1.0,1.447224e+10,41316.0,0.099584,-0.052279,1.0
2022-12-28,414698978,39054223214,1.359372e+09,-1395265314,0.230761,-1.052747e+09,-0.701461,-3.981283,-4.805589e+07,257.368523,...,1797.7,75.89,0.0,0.0,0.0,1.700571e+10,42534.0,0.084050,-0.066367,0.0
2022-12-27,391342277,39446947208,1.585617e+09,-1003923037,0.252399,-7.648258e+08,0.843865,-3.636630,-4.411265e+07,255.104257,...,1797.7,75.89,0.0,0.0,0.0,1.574858e+10,39816.0,0.097602,-0.054126,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-08-05,542878,12887100,1.825368e+11,-24570340172,0.169130,-9.241469e+05,-0.029782,-0.313325,2.839361e+09,1.541591,...,1261.3,49.58,1.0,0.0,1.0,1.406396e+09,18068.0,0.096537,0.000000,1.0
2017-08-04,287621,10749400,1.825370e+11,-24570627793,0.220680,-7.930052e+05,-0.036616,-0.337737,2.839313e+09,1.262926,...,1261.3,49.58,1.0,0.0,1.0,1.595064e+09,19444.0,0.089727,-0.060275,1.0
2017-08-03,293008,10664200,1.825373e+11,-24570920801,0.320985,-6.797564e+05,-0.005890,-0.282463,2.839310e+09,1.022447,...,1271.1,49.03,0.0,0.0,1.0,9.519068e+08,21192.0,0.100593,0.036089,1.0
2017-08-02,256793,10045200,1.825375e+11,-24571177594,0.349082,-5.828721e+05,-0.005652,-0.244947,2.839296e+09,0.932209,...,1275.1,49.59,0.0,0.0,0.0,9.440169e+08,23821.0,0.081365,0.000000,1.0
2017-08-01,300413,9986680,1.825374e+11,-24571478007,0.391284,-4.996317e+05,0.006530,-0.225840,2.839294e+09,0.886643,...,1276.1,49.16,0.0,0.0,0.0,1.232876e+09,25194.0,0.071988,-0.046656,0.0

In [55]:
Base_BNB.to_csv("BNB_raw_technical_plus_old.csv")

In [56]:
import numpy as np
from pycaret.classification import *

# Initialize setup
clf = setup(data=Base_BNB, target='Binance_change', session_id=123)

In [57]:
best_model = compare_models()

In [34]:
from pycaret.classification import tune_model

# Tune the best model
tuned_model = tune_model(best_model)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [35]:
for lag in range(1, 6):  # Creating lags from 1 to 5 days
        Base_BNB[f'Price_Direction_lag_{lag}'] = Base_BNB["Binance_change"].shift(lag)

# Drop rows with NaN values created by shifting
Base_BNB.dropna(inplace=True)

In [36]:
Base_BNB

,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,volume_em,volume_sma_em,volume_vpt,volume_vwap,...,BTC_Volume,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Binance_change,Price_Direction_lag_1,Price_Direction_lag_2,Price_Direction_lag_3,Price_Direction_lag_4,Price_Direction_lag_5
Date,,,,,,,,,,,,,,,,,,,,,
2022-12-26,276115280,39063326955,1.768921e+09,-1280038317,0.269723,-7.502330e+08,-1.473950,-4.021395,-4.679990e+07,251.440291,...,1.188696e+10,36179.0,0.093310,-0.035239,1.0,1.0,0.0,1.0,0.0,1.0
2022-12-25,298063868,38894316963,1.683865e+09,-1578102185,0.245592,-6.881923e+08,0.412378,-1.975188,-4.809371e+07,249.215255,...,1.165638e+10,30277.0,0.118710,-0.047619,0.0,1.0,1.0,0.0,1.0,0.0
2022-12-24,280627376,39133349164,1.576900e+09,-1297474809,0.220948,-5.297447e+08,1.072775,-1.444623,-4.636244e+07,248.196789,...,9.744636e+09,31346.0,0.104037,-0.115418,0.0,0.0,1.0,1.0,0.0,1.0
2022-12-23,388929772,39375368363,1.534138e+09,-908545037,0.203847,-3.701691e+08,1.271926,-1.034234,-4.396184e+07,247.203692,...,1.532927e+10,38289.0,0.095745,-0.035277,1.0,0.0,0.0,1.0,1.0,0.0
2022-12-22,543367184,39334222657,1.769477e+09,-1451912221,0.219286,-3.374700e+08,-2.924864,-1.221046,-4.453578e+07,246.310293,...,1.644157e+10,41898.0,0.092558,-0.033695,0.0,1.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-08-05,542878,12887100,1.825368e+11,-24570340172,0.169130,-9.241469e+05,-0.029782,-0.313325,2.839361e+09,1.541591,...,1.406396e+09,18068.0,0.096537,0.000000,1.0,1.0,1.0,1.0,1.0,1.0
2017-08-04,287621,10749400,1.825370e+11,-24570627793,0.220680,-7.930052e+05,-0.036616,-0.337737,2.839313e+09,1.262926,...,1.595064e+09,19444.0,0.089727,-0.060275,1.0,1.0,1.0,1.0,1.0,1.0
2017-08-03,293008,10664200,1.825373e+11,-24570920801,0.320985,-6.797564e+05,-0.005890,-0.282463,2.839310e+09,1.022447,...,9.519068e+08,21192.0,0.100593,0.036089,1.0,1.0,1.0,1.0,1.0,1.0
2017-08-02,256793,10045200,1.825375e+11,-24571177594,0.349082,-5.828721e+05,-0.005652,-0.244947,2.839296e+09,0.932209,...,9.440169e+08,23821.0,0.081365,0.000000,1.0,1.0,1.0,1.0,1.0,1.0
2017-08-01,300413,9986680,1.825374e+11,-24571478007,0.391284,-4.996317e+05,0.006530,-0.225840,2.839294e+09,0.886643,...,1.232876e+09,25194.0,0.071988,-0.046656,0.0,1.0,1.0,1.0,1.0,1.0

In [39]:
import numpy as np
from pycaret.classification import *

# Initialize setup
clf = setup(data=Base_BNB, target='Binance_change', session_id=321)

In [40]:
best_model = compare_models()

In [41]:
Base_BNB

,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,volume_em,volume_sma_em,volume_vpt,volume_vwap,...,BTC_Volume,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Binance_change,Price_Direction_lag_1,Price_Direction_lag_2,Price_Direction_lag_3,Price_Direction_lag_4,Price_Direction_lag_5
Date,,,,,,,,,,,,,,,,,,,,,
2022-12-26,276115280,39063326955,1.768921e+09,-1280038317,0.269723,-7.502330e+08,-1.473950,-4.021395,-4.679990e+07,251.440291,...,1.188696e+10,36179.0,0.093310,-0.035239,1.0,1.0,0.0,1.0,0.0,1.0
2022-12-25,298063868,38894316963,1.683865e+09,-1578102185,0.245592,-6.881923e+08,0.412378,-1.975188,-4.809371e+07,249.215255,...,1.165638e+10,30277.0,0.118710,-0.047619,0.0,1.0,1.0,0.0,1.0,0.0
2022-12-24,280627376,39133349164,1.576900e+09,-1297474809,0.220948,-5.297447e+08,1.072775,-1.444623,-4.636244e+07,248.196789,...,9.744636e+09,31346.0,0.104037,-0.115418,0.0,0.0,1.0,1.0,0.0,1.0
2022-12-23,388929772,39375368363,1.534138e+09,-908545037,0.203847,-3.701691e+08,1.271926,-1.034234,-4.396184e+07,247.203692,...,1.532927e+10,38289.0,0.095745,-0.035277,1.0,0.0,0.0,1.0,1.0,0.0
2022-12-22,543367184,39334222657,1.769477e+09,-1451912221,0.219286,-3.374700e+08,-2.924864,-1.221046,-4.453578e+07,246.310293,...,1.644157e+10,41898.0,0.092558,-0.033695,0.0,1.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-08-05,542878,12887100,1.825368e+11,-24570340172,0.169130,-9.241469e+05,-0.029782,-0.313325,2.839361e+09,1.541591,...,1.406396e+09,18068.0,0.096537,0.000000,1.0,1.0,1.0,1.0,1.0,1.0
2017-08-04,287621,10749400,1.825370e+11,-24570627793,0.220680,-7.930052e+05,-0.036616,-0.337737,2.839313e+09,1.262926,...,1.595064e+09,19444.0,0.089727,-0.060275,1.0,1.0,1.0,1.0,1.0,1.0
2017-08-03,293008,10664200,1.825373e+11,-24570920801,0.320985,-6.797564e+05,-0.005890,-0.282463,2.839310e+09,1.022447,...,9.519068e+08,21192.0,0.100593,0.036089,1.0,1.0,1.0,1.0,1.0,1.0
2017-08-02,256793,10045200,1.825375e+11,-24571177594,0.349082,-5.828721e+05,-0.005652,-0.244947,2.839296e+09,0.932209,...,9.440169e+08,23821.0,0.081365,0.000000,1.0,1.0,1.0,1.0,1.0,1.0
2017-08-01,300413,9986680,1.825374e+11,-24571478007,0.391284,-4.996317e+05,0.006530,-0.225840,2.839294e+09,0.886643,...,1.232876e+09,25194.0,0.071988,-0.046656,0.0,1.0,1.0,1.0,1.0,1.0

# Study Derived Best Result

In [2]:
import pandas as pd

In [3]:
BNB=pd.read_excel("../../../Binance/0 day lag individual.xlsx")
BNB['Date'] = pd.to_datetime(BNB['Date'])
BNB.set_index('Date', inplace=True)

In [4]:
BNB

,Gold_Price,Oil_Price,Nasdaq_Change_bin_0day,Nasdaq_Volume,S&P500_Change_Bin_0day,S&P500_Volume,BTC_Change_Bin_0day,BTC_Volume,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Binance_change
Date,,,,,,,,,,,,
2017-08-01,1276.1,49.16,0,1821780000,0,3470260000,0,1.232876e+09,25194,0.071988,-0.046656,0
2017-08-02,1275.1,49.59,0,2115870000,0,3487150000,0,9.440169e+08,23821,0.081365,0.000000,1
2017-08-03,1271.1,49.03,0,2124100000,0,3662410000,1,9.519068e+08,21192,0.100593,0.036089,1
2017-08-04,1261.3,49.58,1,1908930000,0,3239980000,1,1.595064e+09,19444,0.089727,-0.060275,1
2017-08-05,1261.3,49.58,1,1908930000,0,3239980000,1,1.406396e+09,18068,0.096537,0.000000,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-27,1797.7,75.89,0,3827290000,0,3030300000,0,1.574858e+10,39816,0.097602,-0.054126,1
2022-12-28,1797.7,75.89,0,3842970000,0,3083520000,0,1.700571e+10,42534,0.084050,-0.066367,0
2022-12-29,1797.7,75.89,1,4154100000,1,3003680000,1,1.447224e+10,41316,0.099584,-0.052279,1
2022-12-30,1797.7,75.89,1,3959030000,1,2979870000,0,1.592916e+10,40485,0.095240,-0.024360,0
2022-12-31,1797.7,75.89,1,3959030000,1,2979870000,0,1.123919e+10,35625,0.119512,-0.068864,1

In [5]:
#BTC MarketCap missing
# List of columns to convert
columns_to_convert = ['Gold_Price', 'Oil_Price','BTC_Volume','Tweets_Count','Tweets_Vader_Sentiment','News_Vader_Sentiment']

# Applying the transformation
for column in columns_to_convert:
    BNB[column + '_binary'] = (BNB[column] > BNB[column].shift(1)).astype(int)

In [6]:
BNB

,Gold_Price,Oil_Price,Nasdaq_Change_bin_0day,Nasdaq_Volume,S&P500_Change_Bin_0day,S&P500_Volume,BTC_Change_Bin_0day,BTC_Volume,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Binance_change,Gold_Price_binary,Oil_Price_binary,BTC_Volume_binary,Tweets_Count_binary,Tweets_Vader_Sentiment_binary,News_Vader_Sentiment_binary
Date,,,,,,,,,,,,,,,,,,
2017-08-01,1276.1,49.16,0,1821780000,0,3470260000,0,1.232876e+09,25194,0.071988,-0.046656,0,0,0,0,0,0,0
2017-08-02,1275.1,49.59,0,2115870000,0,3487150000,0,9.440169e+08,23821,0.081365,0.000000,1,0,1,0,0,1,1
2017-08-03,1271.1,49.03,0,2124100000,0,3662410000,1,9.519068e+08,21192,0.100593,0.036089,1,0,0,1,0,1,1
2017-08-04,1261.3,49.58,1,1908930000,0,3239980000,1,1.595064e+09,19444,0.089727,-0.060275,1,0,1,1,0,0,0
2017-08-05,1261.3,49.58,1,1908930000,0,3239980000,1,1.406396e+09,18068,0.096537,0.000000,1,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-27,1797.7,75.89,0,3827290000,0,3030300000,0,1.574858e+10,39816,0.097602,-0.054126,1,0,0,1,1,1,0
2022-12-28,1797.7,75.89,0,3842970000,0,3083520000,0,1.700571e+10,42534,0.084050,-0.066367,0,0,0,1,1,0,0
2022-12-29,1797.7,75.89,1,4154100000,1,3003680000,1,1.447224e+10,41316,0.099584,-0.052279,1,0,0,0,0,1,1
2022-12-30,1797.7,75.89,1,3959030000,1,2979870000,0,1.592916e+10,40485,0.095240,-0.024360,0,0,0,1,0,0,1
2022-12-31,1797.7,75.89,1,3959030000,1,2979870000,0,1.123919e+10,35625,0.119512,-0.068864,1,0,0,0,0,1,0

In [7]:
BNB.drop(["Gold_Price","Oil_Price","Nasdaq_Volume","S&P500_Volume"],inplace=True,axis=1)
#'BTC_Volume','BTC_Market_Cap','Tweets_Count','Tweets_Vader_Sentiment','News_Vader_Sentiment'

In [8]:
columns_to_lag = ['Binance_change'] #'Gold_Price_binary','Oil_Price_binary','Tweets_Count_binary','Tweets_Vader_Sentiment_binary','News_Vader_Sentiment_binary'

# Number of lags (days back) to create
number_of_lags = 5

# Create lag features for the selected columns
for column in columns_to_lag:
    for lag in range(1, number_of_lags + 1):
        BNB[f'{column}_lag_{lag}'] = BNB[column].shift(lag)

# Optionally, remove any rows with NaN values that were created due to shifting
BNB.dropna(inplace=True)

In [9]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

#BTC market cap missing

# Selecting the columns to standardize
features = BNB[['BTC_Volume', 'Tweets_Count', 'Tweets_Vader_Sentiment', 'News_Vader_Sentiment']]

# Initialize the StandardScaler
scaler = StandardScaler()

# Standardize the features
features_scaled = scaler.fit_transform(features)

# Replace the original columns with the scaled columns
BNB[['BTC_Volume', 'Tweets_Count', 'Tweets_Vader_Sentiment', 'News_Vader_Sentiment']] = features_scaled

In [10]:
BNB

,Nasdaq_Change_bin_0day,S&P500_Change_Bin_0day,BTC_Change_Bin_0day,BTC_Volume,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Binance_change,Gold_Price_binary,Oil_Price_binary,BTC_Volume_binary,Tweets_Count_binary,Tweets_Vader_Sentiment_binary,News_Vader_Sentiment_binary,Binance_change_lag_1,Binance_change_lag_2,Binance_change_lag_3,Binance_change_lag_4,Binance_change_lag_5
Date,,,,,,,,,,,,,,,,,,,
2017-08-06,1,0,1,-1.015928,-1.247806,-1.536951,-0.199540,1,0,0,0,0,0,0,1.0,1.0,1.0,1.0,0.0
2017-08-07,1,1,0,-1.003762,-0.822851,-1.353929,0.320624,1,1,0,1,1,1,1,1.0,1.0,1.0,1.0,1.0
2017-08-08,0,0,0,-1.004687,-0.734560,-0.954867,0.576072,1,0,0,0,1,1,1,1.0,1.0,1.0,1.0,1.0
2017-08-09,1,1,1,-1.011429,-0.844116,-1.242745,0.607802,1,1,1,0,0,0,1,1.0,1.0,1.0,1.0,1.0
2017-08-10,0,0,1,-1.000630,-0.898440,-0.894275,0.898726,1,1,0,1,0,1,1,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-27,0,0,0,-0.618140,0.265451,-1.216665,-0.691402,1,0,0,1,1,1,0,1.0,0.0,0.0,1.0,0.0
2022-12-28,0,0,0,-0.583735,0.419578,-1.515805,-0.802641,0,0,0,1,1,0,0,1.0,1.0,0.0,0.0,1.0
2022-12-29,1,1,1,-0.653071,0.350510,-1.172920,-0.674618,1,0,0,0,0,1,1,0.0,1.0,1.0,0.0,0.0
2022-12-30,1,1,0,-0.613198,0.303388,-1.268801,-0.420909,0,0,0,1,0,0,1,1.0,0.0,1.0,1.0,0.0
2022-12-31,1,1,0,-0.741554,0.027796,-0.733051,-0.825334,1,0,0,0,0,1,0,0.0,1.0,0.0,1.0,1.0

In [11]:
BNB_market= pd.read_excel("../../Base_Datasets/Alt_Coin_Yearly_Rank.xlsx", sheet_name = 'Binance_Coin_Daily')
BNB_market['Date'] = pd.to_datetime(BNB_market['Date'])
BNB_market.set_index('Date', inplace=True)

In [12]:
BNB_market

              Open*     High       Low  Close**        Volume       Market Cap
Date
2023-01-10  $272.66  $278.27   $271.15  $277.29  $470,259,383  $44,356,071,739
2023-01-09  $274.44  $283.03   $271.90  $272.70  $783,671,054  $43,622,192,228
2023-01-08  $261.25  $274.39   $260.52  $274.39  $491,734,030  $43,891,548,404
2023-01-07  $259.85  $262.96   $259.59  $261.28  $327,712,514  $41,795,720,412
2023-01-06  $256.45  $260.22   $255.07  $259.87  $417,893,264  $41,569,303,200
...             ...      ...       ...      ...           ...              ...
2017-07-29  $0.1048  $0.1113   $0.1011  $0.1078      $340,218      $10,781,100
2017-07-28  $0.1076   $0.109   $0.1015  $0.1041      $342,568      $10,406,700
2017-07-27  $0.1051  $0.1085   $0.1009  $0.1077      $344,499      $10,773,700
2017-07-26  $0.1059   $0.109  $0.09927  $0.1051      $200,395      $10,513,800
2017-07-25  $0.1152  $0.1158   $0.1015  $0.1059      $145,269      $10,587,000

[1996 rows x 6 columns]

In [13]:
# Convert columns to float, removing any non-numeric characters like commas
BNB_market['Open*'] = pd.to_numeric(BNB_market['Open*'].replace('[^\d.]', '', regex=True), errors='coerce')
BNB_market['High'] = pd.to_numeric(BNB_market['High'].replace('[^\d.]', '', regex=True), errors='coerce')
BNB_market['Low'] = pd.to_numeric(BNB_market['Low'].replace('[^\d.]', '', regex=True), errors='coerce')
BNB_market['Close**'] = pd.to_numeric(BNB_market['Close**'].replace('[^\d.]', '', regex=True), errors='coerce')
BNB_market['Volume'] = pd.to_numeric(BNB_market['Volume'].replace('[^\d.]', '', regex=True), errors='coerce')
BNB_market['Market Cap'] = pd.to_numeric(BNB_market['Market Cap'].replace('[^\d.]', '', regex=True), errors='coerce')

In [14]:
BNB_market

               Open*      High        Low   Close**     Volume   Market Cap
Date
2023-01-10  272.6600  278.2700  271.15000  277.2900  470259383  44356071739
2023-01-09  274.4400  283.0300  271.90000  272.7000  783671054  43622192228
2023-01-08  261.2500  274.3900  260.52000  274.3900  491734030  43891548404
2023-01-07  259.8500  262.9600  259.59000  261.2800  327712514  41795720412
2023-01-06  256.4500  260.2200  255.07000  259.8700  417893264  41569303200
...              ...       ...        ...       ...        ...          ...
2017-07-29    0.1048    0.1113    0.10110    0.1078     340218     10781100
2017-07-28    0.1076    0.1090    0.10150    0.1041     342568     10406700
2017-07-27    0.1051    0.1085    0.10090    0.1077     344499     10773700
2017-07-26    0.1059    0.1090    0.09927    0.1051     200395     10513800
2017-07-25    0.1152    0.1158    0.10150    0.1059     145269     10587000

[1996 rows x 6 columns]

In [15]:
from ta import add_all_ta_features
from ta.utils import dropna

# Clean NaN values
BNB_market = dropna(BNB_market)

# Add all technical indicators
BNB_market = add_all_ta_features(
    BNB_market, open="Open*", high="High", low="Low", close="Close**", volume="Volume", fillna=True
)

C:\Users\sdas1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\ta\trend.py:1030: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  self._psar[i] = high2

In [16]:
BNB_market

,Open*,High,Low,Close**,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,...,momentum_ppo,momentum_ppo_signal,momentum_ppo_hist,momentum_pvo,momentum_pvo_signal,momentum_pvo_hist,momentum_kama,others_dr,others_dlr,others_cr
Date,,,,,,,,,,,,,,,,,,,,,
2023-01-10,272.6600,278.2700,271.15000,277.2900,470259383,44356071739,3.408060e+08,470259383,0.724719,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,277.290000,0.000000,0.000000,0.000000
2023-01-09,274.4400,283.0300,271.90000,272.7000,783671054,43622192228,-3.302080e+08,-313411671,-0.263338,-3.597050e+09,...,-0.132209,-0.026442,-0.105767,5.066416,1.013283,4.053133,275.368225,-1.655307,-1.669160,-1.655307
2023-01-08,261.2500,274.3900,260.52000,274.3900,491734030,43891548404,1.615260e+08,178322359,0.092530,-2.964467e+09,...,-0.185734,-0.058300,-0.127434,4.259936,1.662614,2.597323,274.958505,0.619729,0.617816,-1.045836
2023-01-07,259.8500,262.9600,259.59000,261.2800,327712514,41795720412,1.624985e+08,-149390155,0.078374,-3.154731e+09,...,-0.605869,-0.167814,-0.438055,0.949958,1.520083,-0.570125,270.119299,-4.777871,-4.895782,-5.773739
2023-01-06,256.4500,260.2200,255.07000,259.8700,417893264,41569303200,5.235907e+08,-567283419,0.210170,-2.788230e+09,...,-0.972449,-0.328741,-0.643708,-0.246296,1.166807,-1.413103,266.558376,-0.539651,-0.541112,-6.282232
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-07-29,0.1048,0.1113,0.10110,0.1078,340218,10781100,1.825375e+11,-24570673219,0.553229,-3.143992e+05,...,-60.619773,-49.923981,-10.695793,-66.412964,-50.256165,-16.156800,0.111259,1.315789,1.307208,-99.961124
2017-07-28,0.1076,0.1090,0.10150,0.1041,342568,10406700,1.825374e+11,-24571015787,0.510700,-2.696661e+05,...,-61.880937,-52.315372,-9.565565,-68.889239,-53.982780,-14.906460,0.109404,-3.432282,-3.492568,-99.962458
2017-07-27,0.1051,0.1085,0.10090,0.1077,344499,10773700,1.825377e+11,-24570671288,0.386339,-2.309652e+05,...,-62.800123,-54.412322,-8.387801,-71.111620,-57.408548,-13.703072,0.109175,3.458213,3.399761,-99.961160
2017-07-26,0.1059,0.1090,0.09927,0.1051,200395,10513800,1.825377e+11,-24570871683,0.560714,-1.980446e+05,...,-63.536073,-56.237072,-7.299001,-73.309983,-60.588835,-12.721148,0.108616,-2.414113,-2.443731,-99.962097
2017-07-25,0.1152,0.1158,0.10150,0.1059,145269,10587000,1.825377e+11,-24570726414,0.560612,-1.697359e+05,...,-64.021485,-57.793955,-6.227531,-75.379778,-63.547023,-11.832755,0.108588,0.761180,0.758297,-99.961809

In [17]:
from ta.momentum import RSIIndicator
from ta.trend import MACD
from ta.volatility import BollingerBands

# RSI
BNB_market['rsi'] = RSIIndicator(close=BNB_market['Close**'], window=14, fillna=True).rsi()

# MACD
macd = MACD(close=BNB_market['Close**'], window_slow=26, window_fast=12, window_sign=9, fillna=True)
BNB_market['macd'] = macd.macd()
BNB_market['macd_signal'] = macd.macd_signal()
BNB_market['macd_diff'] = macd.macd_diff()

# Bollinger Bands
indicator_bb = BollingerBands(close=BNB_market['Close**'], window=20, window_dev=2, fillna=True)
BNB_market['bb_bbm'] = indicator_bb.bollinger_mavg()
BNB_market['bb_bbh'] = indicator_bb.bollinger_hband()
BNB_market['bb_bbl'] = indicator_bb.bollinger_lband()

In [18]:
BNB_market

,Open*,High,Low,Close**,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,...,others_dr,others_dlr,others_cr,rsi,macd,macd_signal,macd_diff,bb_bbm,bb_bbh,bb_bbl
Date,,,,,,,,,,,,,,,,,,,,,
2023-01-10,272.6600,278.2700,271.15000,277.2900,470259383,44356071739,3.408060e+08,470259383,0.724719,0.000000e+00,...,0.000000,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,277.290000,277.290000,277.290000
2023-01-09,274.4400,283.0300,271.90000,272.7000,783671054,43622192228,-3.302080e+08,-313411671,-0.263338,-3.597050e+09,...,-1.655307,-1.669160,-1.655307,0.000000,-0.366154,-0.073231,-0.292923,274.995000,279.585000,270.405000
2023-01-08,261.2500,274.3900,260.52000,274.3900,491734030,43891548404,1.615260e+08,178322359,0.092530,-2.964467e+09,...,0.619729,0.617816,-1.045836,28.393136,-0.514039,-0.161392,-0.352647,274.793333,278.584211,271.002455
2023-01-07,259.8500,262.9600,259.59000,261.2800,327712514,41795720412,1.624985e+08,-149390155,0.078374,-3.154731e+09,...,-4.777871,-4.895782,-5.773739,8.420275,-1.669857,-0.463085,-1.206772,271.415000,283.569658,259.260342
2023-01-06,256.4500,260.2200,255.07000,259.8700,417893264,41569303200,5.235907e+08,-567283419,0.210170,-2.788230e+09,...,-0.539651,-0.541112,-6.282232,7.785912,-2.668862,-0.904241,-1.764621,269.106000,283.371071,254.840929
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-07-29,0.1048,0.1113,0.10110,0.1078,340218,10781100,1.825375e+11,-24570673219,0.553229,-3.143992e+05,...,1.315789,1.307208,-99.961124,29.513863,-0.401613,-0.401931,0.000318,0.472188,1.548756,-0.604379
2017-07-28,0.1076,0.1090,0.10150,0.1041,342568,10406700,1.825374e+11,-24571015787,0.510700,-2.696661e+05,...,-3.432282,-3.492568,-99.962458,29.436383,-0.384372,-0.398419,0.014047,0.378893,1.217100,-0.459313
2017-07-27,0.1051,0.1085,0.10090,0.1077,344499,10773700,1.825377e+11,-24570671288,0.386339,-2.309652e+05,...,3.458213,3.399761,-99.961160,29.629953,-0.366197,-0.391974,0.025778,0.312279,1.001017,-0.376460
2017-07-26,0.1059,0.1090,0.09927,0.1051,200395,10513800,1.825377e+11,-24570871683,0.560714,-1.980446e+05,...,-2.414113,-2.443731,-99.962097,29.566869,-0.347991,-0.383178,0.035187,0.264534,0.866206,-0.337139
2017-07-25,0.1152,0.1158,0.10150,0.1059,145269,10587000,1.825377e+11,-24570726414,0.560612,-1.697359e+05,...,0.761180,0.758297,-99.961809,29.616524,-0.329698,-0.372482,0.042784,0.204828,0.576776,-0.167119

In [19]:
# Shift all columns except 'Date'
columns_to_shift = BNB_market.columns.difference(['Date'])
BNB_market[columns_to_shift] = BNB_market[columns_to_shift].shift(-1)

BNB_market.dropna(inplace=True)

In [20]:
BNB_market

,Open*,High,Low,Close**,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,...,others_dr,others_dlr,others_cr,rsi,macd,macd_signal,macd_diff,bb_bbm,bb_bbh,bb_bbl
Date,,,,,,,,,,,,,,,,,,,,,
2023-01-10,274.4400,283.0300,271.90000,272.7000,783671054.0,4.362219e+10,-3.302080e+08,-3.134117e+08,-0.263338,-3.597050e+09,...,-1.655307,-1.669160,-1.655307,0.000000,-0.366154,-0.073231,-0.292923,274.995000,279.585000,270.405000
2023-01-09,261.2500,274.3900,260.52000,274.3900,491734030.0,4.389155e+10,1.615260e+08,1.783224e+08,0.092530,-2.964467e+09,...,0.619729,0.617816,-1.045836,28.393136,-0.514039,-0.161392,-0.352647,274.793333,278.584211,271.002455
2023-01-08,259.8500,262.9600,259.59000,261.2800,327712514.0,4.179572e+10,1.624985e+08,-1.493902e+08,0.078374,-3.154731e+09,...,-4.777871,-4.895782,-5.773739,8.420275,-1.669857,-0.463085,-1.206772,271.415000,283.569658,259.260342
2023-01-07,256.4500,260.2200,255.07000,259.8700,417893264.0,4.156930e+10,5.235907e+08,-5.672834e+08,0.210170,-2.788230e+09,...,-0.539651,-0.541112,-6.282232,7.785912,-2.668862,-0.904241,-1.764621,269.106000,283.371071,254.840929
2023-01-06,259.0800,259.0800,255.60000,256.4200,342934041.0,4.101839e+10,3.422693e+08,-9.102175e+08,0.120764,-2.558929e+09,...,-1.327587,-1.336478,-7.526416,6.496293,-3.696357,-1.462664,-2.233693,266.991667,283.084677,250.898656
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-07-30,0.1048,0.1113,0.10110,0.1078,340218.0,1.078110e+07,1.825375e+11,-2.457067e+10,0.553229,-3.143992e+05,...,1.315789,1.307208,-99.961124,29.513863,-0.401613,-0.401931,0.000318,0.472188,1.548756,-0.604379
2017-07-29,0.1076,0.1090,0.10150,0.1041,342568.0,1.040670e+07,1.825374e+11,-2.457102e+10,0.510700,-2.696661e+05,...,-3.432282,-3.492568,-99.962458,29.436383,-0.384372,-0.398419,0.014047,0.378893,1.217100,-0.459313
2017-07-28,0.1051,0.1085,0.10090,0.1077,344499.0,1.077370e+07,1.825377e+11,-2.457067e+10,0.386339,-2.309652e+05,...,3.458213,3.399761,-99.961160,29.629953,-0.366197,-0.391974,0.025778,0.312279,1.001017,-0.376460
2017-07-27,0.1059,0.1090,0.09927,0.1051,200395.0,1.051380e+07,1.825377e+11,-2.457087e+10,0.560714,-1.980446e+05,...,-2.414113,-2.443731,-99.962097,29.566869,-0.347991,-0.383178,0.035187,0.264534,0.866206,-0.337139
2017-07-26,0.1152,0.1158,0.10150,0.1059,145269.0,1.058700e+07,1.825377e+11,-2.457073e+10,0.560612,-1.697359e+05,...,0.761180,0.758297,-99.961809,29.616524,-0.329698,-0.372482,0.042784,0.204828,0.576776,-0.167119

In [21]:
Binance_final_dataset=BNB_market.join(BNB,how='inner')

In [22]:
Binance_final_dataset

,Open*,High,Low,Close**,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,...,Oil_Price_binary,BTC_Volume_binary,Tweets_Count_binary,Tweets_Vader_Sentiment_binary,News_Vader_Sentiment_binary,Binance_change_lag_1,Binance_change_lag_2,Binance_change_lag_3,Binance_change_lag_4,Binance_change_lag_5
Date,,,,,,,,,,,,,,,,,,,,,
2022-12-31,246.4600,246.5000,243.1300,245.7800,342300809.0,3.931604e+10,1.100244e+09,-1.325879e+09,0.214438,-1.284504e+09,...,0,0,0,1,0,0.0,1.0,0.0,1.0,1.0
2022-12-30,244.1700,246.6000,243.5800,246.4800,345312528.0,3.942815e+10,1.418114e+09,-9.805663e+08,0.258963,-1.066472e+09,...,0,1,0,0,1,1.0,0.0,1.0,1.0,0.0
2022-12-29,246.6100,246.8400,242.1100,244.1400,414698978.0,3.905422e+10,1.359372e+09,-1.395265e+09,0.230761,-1.052747e+09,...,0,0,0,1,1,0.0,1.0,1.0,0.0,0.0
2022-12-28,244.2000,247.6800,242.5600,246.6000,391342277.0,3.944695e+10,1.585617e+09,-1.003923e+09,0.252399,-7.648258e+08,...,0,1,1,0,0,1.0,1.0,0.0,0.0,1.0
2022-12-27,243.1500,244.6000,242.2200,244.2000,276115280.0,3.906333e+10,1.768921e+09,-1.280038e+09,0.269723,-7.502330e+08,...,0,1,1,1,0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-08-10,0.2247,0.2606,0.2222,0.2429,3075320.0,2.429120e+07,1.825335e+11,-2.456604e+10,0.091639,-1.691136e+06,...,0,1,0,1,1,1.0,1.0,1.0,1.0,1.0
2017-08-09,0.1490,0.2269,0.1478,0.2244,2617340.0,2.244210e+07,1.825359e+11,-2.456866e+10,0.102013,-1.456463e+06,...,1,0,0,0,1,1.0,1.0,1.0,1.0,1.0
2017-08-08,0.1340,0.1498,0.1333,0.1488,748177.0,1.488480e+07,1.825366e+11,-2.456940e+10,0.113774,-1.256477e+06,...,0,0,1,1,1,1.0,1.0,1.0,1.0,1.0
2017-08-07,0.1293,0.1330,0.1274,0.1310,393681.0,1.309990e+07,1.825367e+11,-2.456980e+10,0.129626,-1.077981e+06,...,0,1,1,1,1,1.0,1.0,1.0,1.0,1.0
2017-08-06,0.1074,0.1447,0.1071,0.1289,542878.0,1.288710e+07,1.825368e+11,-2.457034e+10,0.169130,-9.241469e+05,...,0,0,0,0,0,1.0,1.0,1.0,1.0,0.0

In [23]:
Binance_final_dataset.to_csv("Binance_final_dataset.csv")

In [24]:
import numpy as np
from pycaret.classification import *

# Initialize setup
clf = setup(data=Binance_final_dataset, target='Binance_change', session_id=123)

In [25]:
best_model=compare_models()

# Further Exploring some relations

In [12]:
df=Base_BNB.join(BNB,how="inner")

In [13]:
df

,Open*,High,Low,Close**,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,...,Gold_Price,Oil_Price,Nasdaq_Change_bin_0day,S&P500_Change_Bin_0day,BTC_Change_Bin_0day,BTC_Volume,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Binance_change
Date,,,,,,,,,,,,,,,,,,,,,
2022-12-31,245.79000,247.5800,245.11000,246.35000,307551853,39407173516,9.042078e+08,-983578055,0.188828,-1.466070e+09,...,1797.7,75.89,1,1,0,1.123919e+10,35625,0.119512,-0.068864,1
2022-12-30,246.46000,246.5000,243.13000,245.78000,342300809,39316042284,1.100244e+09,-1325878864,0.214438,-1.284504e+09,...,1797.7,75.89,1,1,0,1.592916e+10,40485,0.095240,-0.024360,0
2022-12-29,244.17000,246.6000,243.58000,246.48000,345312528,39428145950,1.418114e+09,-980566336,0.258963,-1.066472e+09,...,1797.7,75.89,1,1,1,1.447224e+10,41316,0.099584,-0.052279,1
2022-12-28,246.61000,246.8400,242.11000,244.14000,414698978,39054223214,1.359372e+09,-1395265314,0.230761,-1.052747e+09,...,1797.7,75.89,0,0,0,1.700571e+10,42534,0.084050,-0.066367,0
2022-12-27,244.20000,247.6800,242.56000,246.60000,391342277,39446947208,1.585617e+09,-1003923037,0.252399,-7.648258e+08,...,1797.7,75.89,0,0,0,1.574858e+10,39816,0.097602,-0.054126,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-08-05,0.10740,0.1447,0.10710,0.12890,542878,12887100,1.825368e+11,-24570340172,0.169130,-9.241469e+05,...,1261.3,49.58,1,0,1,1.406396e+09,18068,0.096537,0.000000,1
2017-08-04,0.10670,0.1078,0.10270,0.10750,287621,10749400,1.825370e+11,-24570627793,0.220680,-7.930052e+05,...,1261.3,49.58,1,0,1,1.595064e+09,19444,0.089727,-0.060275,1
2017-08-03,0.10030,0.1070,0.09912,0.10660,293008,10664200,1.825373e+11,-24570920801,0.320985,-6.797564e+05,...,1271.1,49.03,0,0,1,9.519068e+08,21192,0.100593,0.036089,1
2017-08-02,0.09972,0.1012,0.09736,0.10050,256793,10045200,1.825375e+11,-24571177594,0.349082,-5.828721e+05,...,1275.1,49.59,0,0,0,9.440169e+08,23821,0.081365,0.000000,1
2017-08-01,0.10460,0.1063,0.09611,0.09987,300413,9986680,1.825374e+11,-24571478007,0.391284,-4.996317e+05,...,1276.1,49.16,0,0,0,1.232876e+09,25194,0.071988,-0.046656,0

In [15]:
Coin_price=df[["Open*","High","Low","Close**","Volume","Market Cap","Binance_change"]]

In [16]:
Coin_price

,Open*,High,Low,Close**,Volume,Market Cap,Binance_change
Date,,,,,,,
2022-12-31,245.79000,247.5800,245.11000,246.35000,307551853,39407173516,1
2022-12-30,246.46000,246.5000,243.13000,245.78000,342300809,39316042284,0
2022-12-29,244.17000,246.6000,243.58000,246.48000,345312528,39428145950,1
2022-12-28,246.61000,246.8400,242.11000,244.14000,414698978,39054223214,0
2022-12-27,244.20000,247.6800,242.56000,246.60000,391342277,39446947208,1
...,...,...,...,...,...,...,...
2017-08-05,0.10740,0.1447,0.10710,0.12890,542878,12887100,1
2017-08-04,0.10670,0.1078,0.10270,0.10750,287621,10749400,1
2017-08-03,0.10030,0.1070,0.09912,0.10660,293008,10664200,1
2017-08-02,0.09972,0.1012,0.09736,0.10050,256793,10045200,1
2017-08-01,0.10460,0.1063,0.09611,0.09987,300413,9986680,0

In [18]:
import numpy as np
from pycaret.classification import *

# Initialize setup
clf = setup(data=Coin_price, target='Binance_change', session_id=123)

In [19]:
best_model=compare_models()

In [20]:
# Shift all columns except 'Date'
columns_to_shift = Coin_price.columns.difference(['Date'])
Coin_price[columns_to_shift] = Coin_price[columns_to_shift].shift(-1)

Coin_price.dropna(inplace=True)

In [21]:
import numpy as np
from pycaret.classification import *

# Initialize setup
clf = setup(data=Coin_price, target='Binance_change', session_id=123)

In [22]:
best_model=compare_models()