### 1. **Price-Based Features**
   - **Historical prices**: Daily opening, closing, high, and low prices.
   - **Volatility**: Measures of how much the price fluctuates over a given time period.
   - **Moving averages**: Short-term and long-term moving averages (e.g., 7-day, 30-day, 90-day).

### 2. **Volume-Based Features**
   - **Trade volume**: Total number of coins traded in a specific time period.
   - **Volume averages**: Moving averages of trade volumes.

### 3. **Market Sentiment**
   - **Social media sentiment**: Analysis of sentiments expressed on Twitter
   - **News sentiment**: Sentiment analysis of news articles and press releases related to the cryptocurrency.

### 4. **Technical Indicators**
   - **Relative Strength Index (RSI)**: Measures the speed and change of price movements.
   - **Moving Average Convergence Divergence (MACD)**: Shows the relationship between two moving averages of prices.
   - **Bollinger Bands**: Provides a relative understanding of high and low prices.
   - **On-Balance Volume (OBV)**: Uses volume flow to predict changes in stock price.

### 5. **Market Data**
   - **Market cap**: Total market value of the crypto's circulating supply.
   - **Dominance percentage**: Percentage of total market cap that is comprised of the altcoin.

# Enhancements with Different Approaches 
 - **Application of Lags** 
 - **Technical indicators Interprerations turned features**

In [1]:
import pandas as pd
import numpy as np

In [2]:
BTC=pd.read_excel("..\Base_Datasets\Alt_Coin_Yearly_Rank.xlsx", sheet_name = 'Bitcoin_Daily')

In [4]:
BTC

,Date,Open*,High,Low,Close**,Volume,Market Cap
0,"Dec 31, 2022","$16,603.67","$16,628.99","$16,517.52","$16,547.50","$11,239,186,456","$318,516,317,872"
1,"Dec 30, 2022","$16,641.33","$16,643.43","$16,408.48","$16,602.59","$15,929,162,910","$319,559,502,980"
2,"Dec 29, 2022","$16,552.32","$16,651.76","$16,508.68","$16,642.34","$14,472,237,479","$320,309,344,586"
3,"Dec 28, 2022","$16,716.40","$16,768.17","$16,497.56","$16,552.57","$17,005,713,920","$318,567,071,312"
4,"Dec 27, 2022","$16,919.29","$16,959.85","$16,642.07","$16,717.17","$15,748,580,239","$321,717,198,701"
...,...,...,...,...,...,...,...
2552,"Jan 05, 2016",$433.07,$434.18,$429.68,$431.96,"$34,522,600","$6,500,393,256"
2553,"Jan 04, 2016",$430.06,$434.52,$429.08,$433.09,"$38,477,500","$6,515,713,340"
2554,"Jan 03, 2016",$433.58,$433.74,$424.71,$430.01,"$39,633,800","$6,467,429,942"
2555,"Jan 02, 2016",$434.62,$436.06,$431.87,$433.44,"$30,096,600","$6,517,390,487"
2556,"Jan 01, 2016",$430.72,$436.25,$427.52,$434.33,"$36,278,900","$6,529,299,589"

# Ethereum

In [12]:
ETH=pd.read_excel("..\..\Ethereum\\2022Ethereum_Original_LowCloseRemoved.xlsx")

In [11]:
ETH

,Date,Gold_Price,Oil_Price,Nasdaq_Open,Nasdaq_Volume,S&P500_Open,S&P500_Volume,BTC_Open,BTC_Volume,BTC_Market_Cap,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Ethereum_Change
0,2016-01-01,1060.5,37.04,4897.649902,2218420000,2038.20,4304880000,434.334,3.173093e+07,6.521422e+09,13583,0.238774,0.000000,1
1,2016-01-02,1060.5,37.04,4897.649902,2218420000,2038.20,4304880000,433.438,3.117175e+07,6.461269e+09,13691,0.254835,0.000000,0
2,2016-01-03,1060.5,37.04,4897.649902,2218420000,2038.20,4304880000,430.011,3.715623e+07,6.494453e+09,13167,0.248901,0.000000,1
3,2016-01-04,1075.5,36.76,4897.649902,2218420000,2038.20,4304880000,433.091,3.669657e+07,6.504166e+09,15821,0.181530,0.000000,0
4,2016-01-05,1078.7,35.97,4917.839844,1927380000,2013.78,3706620000,431.960,3.357784e+07,6.471942e+09,16689,0.182860,0.153550,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2552,2022-12-27,1797.7,75.89,10462.190430,3827290000,3843.34,3030300000,16919.290,1.574858e+10,3.217172e+11,39816,0.097602,-0.054126,0
2553,2022-12-28,1797.7,75.89,10339.200195,3842970000,3829.56,3083520000,16716.400,1.700571e+10,3.185671e+11,42534,0.084050,-0.066367,0
2554,2022-12-29,1797.7,75.89,10321.459961,4154100000,3805.45,3003680000,16552.320,1.447224e+10,3.203093e+11,41316,0.099584,-0.052279,1
2555,2022-12-30,1797.7,75.89,10368.370117,3959030000,3829.06,2979870000,16641.330,1.592916e+10,3.195595e+11,40485,0.095240,-0.024360,0
2556,2022-12-31,1797.7,75.89,10368.370117,3959030000,3829.06,2979870000,16603.670,1.123919e+10,3.185163e+11,35625,0.119512,-0.068864,0

In [12]:
ETH.drop(["Nasdaq_Volume","S&P500_Volume"],inplace=True,axis=1)

ETH.head()

,Date,Gold_Price,Oil_Price,Nasdaq_Open,S&P500_Open,BTC_Open,BTC_Volume,BTC_Market_Cap,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Ethereum_Change
0,2016-01-01,1060.5,37.04,4897.649902,2038.20,434.334,3.173093e+07,6.521422e+09,13583,0.238774,0.00000,1
1,2016-01-02,1060.5,37.04,4897.649902,2038.20,433.438,3.117175e+07,6.461269e+09,13691,0.254835,0.00000,0
2,2016-01-03,1060.5,37.04,4897.649902,2038.20,430.011,3.715623e+07,6.494453e+09,13167,0.248901,0.00000,1
3,2016-01-04,1075.5,36.76,4897.649902,2038.20,433.091,3.669657e+07,6.504166e+09,15821,0.181530,0.00000,0
4,2016-01-05,1078.7,35.97,4917.839844,2013.78,431.960,3.357784e+07,6.471942e+09,16689,0.182860,0.15355,0

In [28]:
ETH['Date'] = pd.to_datetime(ETH['Date'])
ETH.set_index('Date', inplace=True)

In [14]:
ETH

,Gold_Price,Oil_Price,Nasdaq_Open,S&P500_Open,BTC_Open,BTC_Volume,BTC_Market_Cap,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Ethereum_Change
Date,,,,,,,,,,,
2016-01-01,1060.5,37.04,4897.649902,2038.20,434.334,3.173093e+07,6.521422e+09,13583,0.238774,0.000000,1
2016-01-02,1060.5,37.04,4897.649902,2038.20,433.438,3.117175e+07,6.461269e+09,13691,0.254835,0.000000,0
2016-01-03,1060.5,37.04,4897.649902,2038.20,430.011,3.715623e+07,6.494453e+09,13167,0.248901,0.000000,1
2016-01-04,1075.5,36.76,4897.649902,2038.20,433.091,3.669657e+07,6.504166e+09,15821,0.181530,0.000000,0
2016-01-05,1078.7,35.97,4917.839844,2013.78,431.960,3.357784e+07,6.471942e+09,16689,0.182860,0.153550,0
...,...,...,...,...,...,...,...,...,...,...,...
2022-12-27,1797.7,75.89,10462.190430,3843.34,16919.290,1.574858e+10,3.217172e+11,39816,0.097602,-0.054126,0
2022-12-28,1797.7,75.89,10339.200195,3829.56,16716.400,1.700571e+10,3.185671e+11,42534,0.084050,-0.066367,0
2022-12-29,1797.7,75.89,10321.459961,3805.45,16552.320,1.447224e+10,3.203093e+11,41316,0.099584,-0.052279,1
2022-12-30,1797.7,75.89,10368.370117,3829.06,16641.330,1.592916e+10,3.195595e+11,40485,0.095240,-0.024360,0
2022-12-31,1797.7,75.89,10368.370117,3829.06,16603.670,1.123919e+10,3.185163e+11,35625,0.119512,-0.068864,0

In [37]:
Base_ETH = pd.read_excel(r"C:\Users\sdas1\Desktop\TCD\Dissertation\Altcoin\Altcoin-Price-Prediction\New_Experiments\Base_Datasets\Alt_Coin_Yearly_Rank.xlsx", sheet_name = 'Ethereum_Daily')

In [38]:
Base_ETH

,Date,Open*,High,Low,Close**,Volume,Market Cap
0,"Dec 31, 2022","$1,199.36","$1,205.09","$1,194.20","$1,196.77","$3,018,513,333","$146,453,523,490"
1,"Dec 30, 2022","$1,201.57","$1,202.03","$1,187.46","$1,199.23","$4,055,668,253","$146,754,748,633"
2,"Dec 29, 2022","$1,190.01","$1,204.14","$1,188.36","$1,201.60","$4,132,233,940","$147,043,867,255"
3,"Dec 28, 2022","$1,212.74","$1,213.13","$1,185.70","$1,189.99","$4,991,669,631","$145,623,194,889"
4,"Dec 27, 2022","$1,226.99","$1,230.42","$1,205.90","$1,212.79","$4,091,530,737","$148,414,001,604"
...,...,...,...,...,...,...,...
2551,"Jan 05, 2016",$0.9531,$0.9706,$0.9465,$0.9502,"$219,833","$72,240,974"
2552,"Jan 04, 2016",$0.972,$0.9764,$0.9298,$0.9545,"$346,245","$72,543,707"
2553,"Jan 03, 2016",$0.9384,$0.9914,$0.9343,$0.9719,"$407,632","$73,843,292"
2554,"Jan 02, 2016",$0.9474,$0.9696,$0.9366,$0.9371,"$255,504","$71,176,658"
2555,"Jan 01, 2016",$0.9337,$0.9548,$0.9314,$0.948,"$206,062","$71,980,386"

In [17]:
print(Base_ETH.isnull().sum())

Date          0
Open*         0
High          0
Low           0
Close**       0
Volume        0
Market Cap    0
dtype: int64

In [61]:
Base_ETH['Date'] = pd.to_datetime(Base_ETH['Date'])
Base_ETH.set_index('Date', inplace=True)

In [40]:
# Convert columns to float, removing any non-numeric characters like commas
Base_ETH['Open*'] = pd.to_numeric(Base_ETH['Open*'].replace('[^\d.]', '', regex=True), errors='coerce')
Base_ETH['High'] = pd.to_numeric(Base_ETH['High'].replace('[^\d.]', '', regex=True), errors='coerce')
Base_ETH['Low'] = pd.to_numeric(Base_ETH['Low'].replace('[^\d.]', '', regex=True), errors='coerce')
Base_ETH['Close**'] = pd.to_numeric(Base_ETH['Close**'].replace('[^\d.]', '', regex=True), errors='coerce')
Base_ETH['Volume'] = pd.to_numeric(Base_ETH['Volume'].replace('[^\d.]', '', regex=True), errors='coerce')
Base_ETH['Market Cap'] = pd.to_numeric(Base_ETH['Market Cap'].replace('[^\d.]', '', regex=True), errors='coerce')

In [16]:
from ta import add_all_ta_features
from ta.utils import dropna

# Clean NaN values
Base_ETH = dropna(Base_ETH)

# Add all technical indicators
Base_ETH = add_all_ta_features(
    Base_ETH, open="Open*", high="High", low="Low", close="Close**", volume="Volume", fillna=True
)

In [41]:
from ta.momentum import RSIIndicator
from ta.trend import MACD
from ta.volatility import BollingerBands

# RSI
Base_ETH['rsi'] = RSIIndicator(close=Base_ETH['Close**'], window=14, fillna=True).rsi()

# MACD
macd = MACD(close=Base_ETH['Close**'], window_slow=26, window_fast=12, window_sign=9, fillna=True)
Base_ETH['macd'] = macd.macd()
Base_ETH['macd_signal'] = macd.macd_signal()
Base_ETH['macd_diff'] = macd.macd_diff()

# Bollinger Bands
indicator_bb = BollingerBands(close=Base_ETH['Close**'], window=20, window_dev=2, fillna=True)
Base_ETH['bb_bbm'] = indicator_bb.bollinger_mavg()
Base_ETH['bb_bbh'] = indicator_bb.bollinger_hband()
Base_ETH['bb_bbl'] = indicator_bb.bollinger_lband()

In [42]:
Base_ETH

,Open*,High,Low,Close**,Volume,Market Cap,rsi,macd,macd_signal,macd_diff,bb_bbm,bb_bbh,bb_bbl
Date,,,,,,,,,,,,,
2022-12-31,1199.3600,1205.0900,1194.2000,1196.7700,3018513333,146453523490,100.000000,0.000000,0.000000,0.000000,1196.770000,1196.770000,1196.770000
2022-12-30,1201.5700,1202.0300,1187.4600,1199.2300,4055668253,146754748633,100.000000,0.196239,0.039248,0.156991,1198.000000,1200.460000,1195.540000
2022-12-29,1190.0100,1204.1400,1188.3600,1201.6000,4132233940,147043867255,100.000000,0.536812,0.138761,0.398051,1199.200000,1203.143907,1195.256093
2022-12-28,1212.7400,1213.1300,1185.7000,1189.9900,4991669631,145623194889,27.127046,-0.128630,0.085283,-0.213912,1196.897500,1205.574128,1188.220872
2022-12-27,1226.9900,1230.4200,1205.9000,1212.7900,4091530737,148414001604,71.323196,1.170282,0.302283,0.868000,1200.076000,1214.971398,1185.180602
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-05,0.9531,0.9706,0.9465,0.9502,219833,72240974,23.222015,-0.573078,-0.675665,0.102587,1.279295,1.930723,0.627867
2016-01-04,0.9720,0.9764,0.9298,0.9545,346245,72543707,23.443580,-0.543918,-0.649316,0.105398,1.220020,1.752223,0.687817
2016-01-03,0.9384,0.9914,0.9343,0.9719,407632,73843292,24.394372,-0.513486,-0.622150,0.108664,1.170115,1.586163,0.754067
2016-01-02,0.9474,0.9696,0.9366,0.9371,255504,71176658,23.758831,-0.486567,-0.595033,0.108466,1.141970,1.540746,0.743194
2016-01-01,0.9337,0.9548,0.9314,0.9480,206062,71980386,24.422995,-0.459062,-0.567839,0.108777,1.111870,1.471905,0.751835

In [43]:
Base_ETH[["Gold_Price","Oil_Price","Nasdaq_Open","S&P500_Open","BTC_Open","BTC_Volume","BTC_Market_Cap","Tweets_Count","Tweets_Vader_Sentiment","News_Vader_Sentiment"]]=ETH[["Gold_Price","Oil_Price","Nasdaq_Open","S&P500_Open","BTC_Open","BTC_Volume","BTC_Market_Cap","Tweets_Count","Tweets_Vader_Sentiment","News_Vader_Sentiment"]]
Base_ETH

,Open*,High,Low,Close**,Volume,Market Cap,rsi,macd,macd_signal,macd_diff,...,Gold_Price,Oil_Price,Nasdaq_Open,S&P500_Open,BTC_Open,BTC_Volume,BTC_Market_Cap,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment
Date,,,,,,,,,,,,,,,,,,,,,
2022-12-31,1199.3600,1205.0900,1194.2000,1196.7700,3018513333,146453523490,100.000000,0.000000,0.000000,0.000000,...,1797.7,75.89,10368.370117,3829.06,16603.670,1.123919e+10,3.185163e+11,35625,0.119512,-0.068864
2022-12-30,1201.5700,1202.0300,1187.4600,1199.2300,4055668253,146754748633,100.000000,0.196239,0.039248,0.156991,...,1797.7,75.89,10368.370117,3829.06,16641.330,1.592916e+10,3.195595e+11,40485,0.095240,-0.024360
2022-12-29,1190.0100,1204.1400,1188.3600,1201.6000,4132233940,147043867255,100.000000,0.536812,0.138761,0.398051,...,1797.7,75.89,10321.459961,3805.45,16552.320,1.447224e+10,3.203093e+11,41316,0.099584,-0.052279
2022-12-28,1212.7400,1213.1300,1185.7000,1189.9900,4991669631,145623194889,27.127046,-0.128630,0.085283,-0.213912,...,1797.7,75.89,10339.200195,3829.56,16716.400,1.700571e+10,3.185671e+11,42534,0.084050,-0.066367
2022-12-27,1226.9900,1230.4200,1205.9000,1212.7900,4091530737,148414001604,71.323196,1.170282,0.302283,0.868000,...,1797.7,75.89,10462.190430,3843.34,16919.290,1.574858e+10,3.217172e+11,39816,0.097602,-0.054126
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-05,0.9531,0.9706,0.9465,0.9502,219833,72240974,23.222015,-0.573078,-0.675665,0.102587,...,1078.7,35.97,4917.839844,2013.78,431.960,3.357784e+07,6.471942e+09,16689,0.182860,0.153550
2016-01-04,0.9720,0.9764,0.9298,0.9545,346245,72543707,23.443580,-0.543918,-0.649316,0.105398,...,1075.5,36.76,4897.649902,2038.20,433.091,3.669657e+07,6.504166e+09,15821,0.181530,0.000000
2016-01-03,0.9384,0.9914,0.9343,0.9719,407632,73843292,24.394372,-0.513486,-0.622150,0.108664,...,1060.5,37.04,4897.649902,2038.20,430.011,3.715623e+07,6.494453e+09,13167,0.248901,0.000000
2016-01-02,0.9474,0.9696,0.9366,0.9371,255504,71176658,23.758831,-0.486567,-0.595033,0.108466,...,1060.5,37.04,4897.649902,2038.20,433.438,3.117175e+07,6.461269e+09,13691,0.254835,0.000000
2016-01-01,0.9337,0.9548,0.9314,0.9480,206062,71980386,24.422995,-0.459062,-0.567839,0.108777,...,1060.5,37.04,4897.649902,2038.20,434.334,3.173093e+07,6.521422e+09,13583,0.238774,0.000000

In [45]:
# Base_ETH["Price_Direction"]=Base_ETH["Close**"]-Base_ETH["Open*"]
# Binary_direction=[]
# for price in Base_ETH["Price_Direction"]:
#     if(price<0) :
#         Binary_direction.append(0)
#     else :
#         Binary_direction.append(1) 
# Base_ETH["Price_Direction"]=Binary_direction

Base_ETH['Future_Close'] = Base_ETH['Close**'].shift(-1)  # Shift closing price to the previous day for comparison
Base_ETH['Price_Direction'] = (Base_ETH['Future_Close'] > Base_ETH['Close**']).astype(int)  # 1 if price increases, else 0
Base_ETH.dropna(inplace=True)  # Drop the last row where Future_Close is NaN

In [46]:
Base_ETH

,Open*,High,Low,Close**,Volume,Market Cap,rsi,macd,macd_signal,macd_diff,...,Nasdaq_Open,S&P500_Open,BTC_Open,BTC_Volume,BTC_Market_Cap,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Future_Close,Price_Direction
Date,,,,,,,,,,,,,,,,,,,,,
2022-12-31,1199.3600,1205.0900,1194.2000,1196.7700,3018513333,146453523490,100.000000,0.000000,0.000000,0.000000,...,10368.370117,3829.06,16603.670,1.123919e+10,3.185163e+11,35625,0.119512,-0.068864,1199.2300,1
2022-12-30,1201.5700,1202.0300,1187.4600,1199.2300,4055668253,146754748633,100.000000,0.196239,0.039248,0.156991,...,10368.370117,3829.06,16641.330,1.592916e+10,3.195595e+11,40485,0.095240,-0.024360,1201.6000,1
2022-12-29,1190.0100,1204.1400,1188.3600,1201.6000,4132233940,147043867255,100.000000,0.536812,0.138761,0.398051,...,10321.459961,3805.45,16552.320,1.447224e+10,3.203093e+11,41316,0.099584,-0.052279,1189.9900,0
2022-12-28,1212.7400,1213.1300,1185.7000,1189.9900,4991669631,145623194889,27.127046,-0.128630,0.085283,-0.213912,...,10339.200195,3829.56,16716.400,1.700571e+10,3.185671e+11,42534,0.084050,-0.066367,1212.7900,1
2022-12-27,1226.9900,1230.4200,1205.9000,1212.7900,4091530737,148414001604,71.323196,1.170282,0.302283,0.868000,...,10462.190430,3843.34,16919.290,1.574858e+10,3.217172e+11,39816,0.097602,-0.054126,1226.9700,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-06,0.9500,0.9607,0.9357,0.9509,308791,72317149,23.232179,-0.601523,-0.701312,0.099789,...,4813.759766,2011.71,429.105,6.315093e+07,6.756367e+09,15981,0.212686,0.000000,0.9502,0
2016-01-05,0.9531,0.9706,0.9465,0.9502,219833,72240974,23.222015,-0.573078,-0.675665,0.102587,...,4917.839844,2013.78,431.960,3.357784e+07,6.471942e+09,16689,0.182860,0.153550,0.9545,1
2016-01-04,0.9720,0.9764,0.9298,0.9545,346245,72543707,23.443580,-0.543918,-0.649316,0.105398,...,4897.649902,2038.20,433.091,3.669657e+07,6.504166e+09,15821,0.181530,0.000000,0.9719,1
2016-01-03,0.9384,0.9914,0.9343,0.9719,407632,73843292,24.394372,-0.513486,-0.622150,0.108664,...,4897.649902,2038.20,430.011,3.715623e+07,6.494453e+09,13167,0.248901,0.000000,0.9371,0
2016-01-02,0.9474,0.9696,0.9366,0.9371,255504,71176658,23.758831,-0.486567,-0.595033,0.108466,...,4897.649902,2038.20,433.438,3.117175e+07,6.461269e+09,13691,0.254835,0.000000,0.9480,1

In [47]:
Base_ETH.drop(["Open*","High","Low","Close**","Future_Close"],inplace=True,axis=1)

In [48]:
Base_ETH

,Volume,Market Cap,rsi,macd,macd_signal,macd_diff,bb_bbm,bb_bbh,bb_bbl,Gold_Price,Oil_Price,Nasdaq_Open,S&P500_Open,BTC_Open,BTC_Volume,BTC_Market_Cap,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Price_Direction
Date,,,,,,,,,,,,,,,,,,,,
2022-12-31,3018513333,146453523490,100.000000,0.000000,0.000000,0.000000,1196.770000,1196.770000,1196.770000,1797.7,75.89,10368.370117,3829.06,16603.670,1.123919e+10,3.185163e+11,35625,0.119512,-0.068864,1
2022-12-30,4055668253,146754748633,100.000000,0.196239,0.039248,0.156991,1198.000000,1200.460000,1195.540000,1797.7,75.89,10368.370117,3829.06,16641.330,1.592916e+10,3.195595e+11,40485,0.095240,-0.024360,1
2022-12-29,4132233940,147043867255,100.000000,0.536812,0.138761,0.398051,1199.200000,1203.143907,1195.256093,1797.7,75.89,10321.459961,3805.45,16552.320,1.447224e+10,3.203093e+11,41316,0.099584,-0.052279,0
2022-12-28,4991669631,145623194889,27.127046,-0.128630,0.085283,-0.213912,1196.897500,1205.574128,1188.220872,1797.7,75.89,10339.200195,3829.56,16716.400,1.700571e+10,3.185671e+11,42534,0.084050,-0.066367,1
2022-12-27,4091530737,148414001604,71.323196,1.170282,0.302283,0.868000,1200.076000,1214.971398,1185.180602,1797.7,75.89,10462.190430,3843.34,16919.290,1.574858e+10,3.217172e+11,39816,0.097602,-0.054126,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-06,308791,72317149,23.232179,-0.601523,-0.701312,0.099789,1.356785,2.179404,0.534166,1092.2,33.97,4813.759766,2011.71,429.105,6.315093e+07,6.756367e+09,15981,0.212686,0.000000,0
2016-01-05,219833,72240974,23.222015,-0.573078,-0.675665,0.102587,1.279295,1.930723,0.627867,1078.7,35.97,4917.839844,2013.78,431.960,3.357784e+07,6.471942e+09,16689,0.182860,0.153550,1
2016-01-04,346245,72543707,23.443580,-0.543918,-0.649316,0.105398,1.220020,1.752223,0.687817,1075.5,36.76,4897.649902,2038.20,433.091,3.669657e+07,6.504166e+09,15821,0.181530,0.000000,1
2016-01-03,407632,73843292,24.394372,-0.513486,-0.622150,0.108664,1.170115,1.586163,0.754067,1060.5,37.04,4897.649902,2038.20,430.011,3.715623e+07,6.494453e+09,13167,0.248901,0.000000,0
2016-01-02,255504,71176658,23.758831,-0.486567,-0.595033,0.108466,1.141970,1.540746,0.743194,1060.5,37.04,4897.649902,2038.20,433.438,3.117175e+07,6.461269e+09,13691,0.254835,0.000000,1

In [60]:
Base_ETH.to_csv("Ethereum/RawTechnical_plus_Old.csv")

In [3]:
Base_ETH=pd.read_csv("Ethereum/RawTechnical_plus_Old.csv")

In [4]:
Base_ETH

,Date,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,volume_em,volume_sma_em,volume_vpt,...,Oil_Price,Nasdaq_Open,S&P500_Open,BTC_Open,BTC_Volume,BTC_Market_Cap,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Price_Direction
0,2022-12-31,3018513333,146453523490,-1.593797e+09,3018513333,-0.528007,0.000000e+00,0.000000,0.000000,0.000000e+00,...,75.89,10368.370117,3829.06,16603.670,1.123919e+10,3.185163e+11,35625,0.119512,-0.068864,0
1,2022-12-30,4055668253,146754748633,9.030692e+08,7074181586,0.127657,9.976944e+09,-1.760326,-1.760326,8.336559e+06,...,75.89,10368.370117,3829.06,16641.330,1.592916e+10,3.195595e+11,40485,0.095240,-0.024360,0
2,2022-12-29,4132233940,147043867255,3.705028e+09,11206415526,0.330617,9.950723e+09,0.574723,-0.592802,1.650296e+07,...,75.89,10321.459961,3805.45,16552.320,1.447224e+10,3.203093e+11,41316,0.099584,-0.052279,1
3,2022-12-28,4991669631,145623194889,2.747333e+08,6214745895,0.016961,2.501501e+08,1.739217,0.184538,-3.172714e+07,...,75.89,10339.200195,3829.56,16716.400,1.700571e+10,3.185671e+11,42534,0.084050,-0.066367,0
4,2022-12-27,4091530737,148414001604,-1.517397e+09,10306276632,-0.074787,1.354111e+10,11.233629,2.946811,4.666588e+07,...,75.89,10462.190430,3843.34,16919.290,1.574858e+10,3.217172e+11,39816,0.097602,-0.054126,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2551,2016-01-05,219833,72240974,2.460530e+12,-1372918065031,0.197787,-9.471747e+04,0.113466,-0.276769,8.780225e+07,...,35.97,4917.839844,2013.78,431.960,3.357784e+07,6.471942e+09,16689,0.182860,0.153550,0
2552,2016-01-04,346245,72543707,2.460530e+12,-1372917718786,0.195874,-8.097371e+04,-0.073350,-0.298535,8.780381e+07,...,36.76,4897.649902,2038.20,433.091,3.669657e+07,6.504166e+09,15821,0.181530,0.000000,0
2553,2016-01-03,407632,73843292,2.460530e+12,-1372917311154,0.051470,-6.839278e+04,0.136575,-0.171678,8.781125e+07,...,37.04,4897.649902,2038.20,430.011,3.715623e+07,6.494453e+09,13167,0.248901,0.000000,1
2554,2016-01-02,255504,71176658,2.460530e+12,-1372917566658,0.070587,-5.989260e+04,-0.125928,-0.168491,8.780210e+07,...,37.04,4897.649902,2038.20,433.438,3.117175e+07,6.461269e+09,13691,0.254835,0.000000,0
2555,2016-01-01,206062,71980386,2.460530e+12,-1372917360596,0.065394,-5.101565e+04,-0.113558,-0.173315,8.780449e+07,...,37.04,4897.649902,2038.20,434.334,3.173093e+07,6.521422e+09,13583,0.238774,0.000000,1

# All Technical indicators no parameters

In [5]:
import numpy as np
from pycaret.classification import *

# Initialize setup
clf = setup(data=Base_ETH, target='Price_Direction', session_id=123)

In [6]:
best_model = compare_models()

In [7]:
from pycaret.classification import tune_model

# Tune the best model
tuned_model = tune_model(best_model)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [8]:
from pycaret.classification import finalize_model, save_model

# Finalize the model
final_model = finalize_model(tuned_model)

# Save the model to disk
save_model(final_model, 'ETH_raw_prediction_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['Volume', 'Market Cap',
                                              'volume_adi', 'volume_obv',
                                              'volume_cmf', 'volume_fi',
                                              'volume_em', 'volume_sma_em',
                                              'volume_vpt', 'volume_vwap',
                                              'volume_mfi', 'volume_nvi',
                                              'volatility_bbm', 'volatility_bbh',
                                              'volatility_bbl', 'volatility_bbw',
                                              'volatility_bbp',
                                              'vola...
                                                               return_df=True,
                                                               smoothing=10,
                                                               verbose=0))),
                 ('clean_column_names',
                  TransformerWrapper(exclude=None, include=None,
                                     transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+'))),
                 ('actual_estimator',
                  RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True,
                                  fit_intercept=True, max_iter=None,
                                  positive=False, random_state=123,
                                  solver='auto', tol=0.0001))],
          verbose=False),
 'ETH_raw_prediction_model.pkl')

# All Technical indicators with parameters

In [7]:
import numpy as np
from pycaret.classification import *

# Initialize setup
exp_clf = setup(data=Base_ETH, target='Price_Direction', session_id=123, normalize=True, transformation=True)

In [8]:
best_model = compare_models()

In [9]:
from pycaret.classification import tune_model

# Tune the best model
tuned_model = tune_model(best_model)

Fitting 10 folds for each of 10 candidates, totalling 100 fits

# Specific Technical indicators no parameters different price parameter

In [50]:
Base_ETH

,Volume,Market Cap,rsi,macd,macd_signal,macd_diff,bb_bbm,bb_bbh,bb_bbl,Gold_Price,Oil_Price,Nasdaq_Open,S&P500_Open,BTC_Open,BTC_Volume,BTC_Market_Cap,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Price_Direction
Date,,,,,,,,,,,,,,,,,,,,
2022-12-31,3018513333,146453523490,100.000000,0.000000,0.000000,0.000000,1196.770000,1196.770000,1196.770000,1797.7,75.89,10368.370117,3829.06,16603.670,1.123919e+10,3.185163e+11,35625,0.119512,-0.068864,1
2022-12-30,4055668253,146754748633,100.000000,0.196239,0.039248,0.156991,1198.000000,1200.460000,1195.540000,1797.7,75.89,10368.370117,3829.06,16641.330,1.592916e+10,3.195595e+11,40485,0.095240,-0.024360,1
2022-12-29,4132233940,147043867255,100.000000,0.536812,0.138761,0.398051,1199.200000,1203.143907,1195.256093,1797.7,75.89,10321.459961,3805.45,16552.320,1.447224e+10,3.203093e+11,41316,0.099584,-0.052279,0
2022-12-28,4991669631,145623194889,27.127046,-0.128630,0.085283,-0.213912,1196.897500,1205.574128,1188.220872,1797.7,75.89,10339.200195,3829.56,16716.400,1.700571e+10,3.185671e+11,42534,0.084050,-0.066367,1
2022-12-27,4091530737,148414001604,71.323196,1.170282,0.302283,0.868000,1200.076000,1214.971398,1185.180602,1797.7,75.89,10462.190430,3843.34,16919.290,1.574858e+10,3.217172e+11,39816,0.097602,-0.054126,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-06,308791,72317149,23.232179,-0.601523,-0.701312,0.099789,1.356785,2.179404,0.534166,1092.2,33.97,4813.759766,2011.71,429.105,6.315093e+07,6.756367e+09,15981,0.212686,0.000000,0
2016-01-05,219833,72240974,23.222015,-0.573078,-0.675665,0.102587,1.279295,1.930723,0.627867,1078.7,35.97,4917.839844,2013.78,431.960,3.357784e+07,6.471942e+09,16689,0.182860,0.153550,1
2016-01-04,346245,72543707,23.443580,-0.543918,-0.649316,0.105398,1.220020,1.752223,0.687817,1075.5,36.76,4897.649902,2038.20,433.091,3.669657e+07,6.504166e+09,15821,0.181530,0.000000,1
2016-01-03,407632,73843292,24.394372,-0.513486,-0.622150,0.108664,1.170115,1.586163,0.754067,1060.5,37.04,4897.649902,2038.20,430.011,3.715623e+07,6.494453e+09,13167,0.248901,0.000000,0
2016-01-02,255504,71176658,23.758831,-0.486567,-0.595033,0.108466,1.141970,1.540746,0.743194,1060.5,37.04,4897.649902,2038.20,433.438,3.117175e+07,6.461269e+09,13691,0.254835,0.000000,1

In [51]:
import numpy as np
from pycaret.classification import *

# Initialize setup
clf = setup(data=Base_ETH, target='Price_Direction', session_id=123)

In [52]:
best_model = compare_models()

Initiated  . . . . . . . . . . . . . . . . . .              10:10:26
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library

In [36]:
from pycaret.classification import tune_model

# Tune the best model
tuned_model = tune_model(best_model)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

# Only Technical indicators

In [59]:
Base_ETH.drop(["Gold_Price","Oil_Price","Nasdaq_Open","S&P500_Open","BTC_Open","BTC_Volume","BTC_Market_Cap","Tweets_Count","Tweets_Vader_Sentiment","News_Vader_Sentiment"],inplace=True,axis=1)

In [62]:
Base_ETH

,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,volume_em,volume_sma_em,volume_vpt,volume_vwap,...,others_dlr,others_cr,rsi,macd,macd_signal,macd_diff,bb_bbm,bb_bbh,bb_bbl,Price_Direction
Date,,,,,,,,,,,,,,,,,,,,,
2022-12-31,3018513333,146453523490,-1.593797e+09,3018513333,-0.528007,0.000000e+00,0.000000,0.000000,0.000000e+00,1198.686667,...,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,1196.770000,1196.770000,1196.770000,0
2022-12-30,4055668253,146754748633,9.030692e+08,7074181586,0.127657,9.976944e+09,-1.760326,-1.760326,8.336559e+06,1197.283979,...,0.205342,0.205553,100.000000,0.196239,0.039248,0.156991,1198.000000,1200.460000,1195.540000,0
2022-12-29,4132233940,147043867255,3.705028e+09,11206415526,0.330617,9.950723e+09,0.574723,-0.592802,1.650296e+07,1197.560295,...,0.197432,0.403586,100.000000,0.536812,0.138761,0.398051,1199.200000,1203.143907,1195.256093,1
2022-12-28,4991669631,145623194889,2.747333e+08,6214745895,0.016961,2.501501e+08,1.739217,0.184538,-3.172714e+07,1197.163699,...,-0.970910,-0.566525,27.127046,-0.128630,0.085283,-0.213912,1196.897500,1205.574128,1188.220872,0
2022-12-27,4091530737,148414001604,-1.517397e+09,10306276632,-0.074787,1.354111e+10,11.233629,2.946811,4.666588e+07,1201.036772,...,1.897859,1.338603,71.323196,1.170282,0.302283,0.868000,1200.076000,1214.971398,1185.180602,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-05,219833,72240974,2.460530e+12,-1372918065031,0.197787,-9.471747e+04,0.113466,-0.276769,8.780225e+07,1.216191,...,-0.073642,-99.920603,23.222015,-0.573078,-0.675665,0.102587,1.279295,1.930723,0.627867,0
2016-01-04,346245,72543707,2.460530e+12,-1372917718786,0.195874,-8.097371e+04,-0.073350,-0.298535,8.780381e+07,1.152925,...,0.451515,-99.920244,23.443580,-0.543918,-0.649316,0.105398,1.220020,1.752223,0.687817,0
2016-01-03,407632,73843292,2.460530e+12,-1372917311154,0.051470,-6.839278e+04,0.136575,-0.171678,8.781125e+07,1.137279,...,1.806528,-99.918790,24.394372,-0.513486,-0.622150,0.108664,1.170115,1.586163,0.754067,1
2016-01-02,255504,71176658,2.460530e+12,-1372917566658,0.070587,-5.989260e+04,-0.125928,-0.168491,8.780210e+07,1.115236,...,-3.646292,-99.921698,23.758831,-0.486567,-0.595033,0.108466,1.141970,1.540746,0.743194,0
2016-01-01,206062,71980386,2.460530e+12,-1372917360596,0.065394,-5.101565e+04,-0.113558,-0.173315,8.780449e+07,1.065592,...,1.156450,-99.920787,24.422995,-0.459062,-0.567839,0.108777,1.111870,1.471905,0.751835,1

In [63]:
import numpy as np
from pycaret.classification import *

# Initialize setup
clf = setup(data=Base_ETH, target='Price_Direction', session_id=123)

In [64]:
best_model = compare_models()

In [65]:
from pycaret.classification import tune_model

# Tune the best model
tuned_model = tune_model(best_model)

Fitting 10 folds for each of 10 candidates, totalling 100 fits

# LAGs

In [1]:
import pandas as pd

# Load the dataset
Lag_ETH = pd.read_csv('Ethereum/RawTechnical_plus_Old.csv')

Lag_ETH.columns  # Print column names to decide which to lag

Index(['Date', 'Volume', 'Market Cap', 'volume_adi', 'volume_obv',
       'volume_cmf', 'volume_fi', 'volume_em', 'volume_sma_em', 'volume_vpt',
       ...
       'Oil_Price', 'Nasdaq_Open', 'S&P500_Open', 'BTC_Open', 'BTC_Volume',
       'BTC_Market_Cap', 'Tweets_Count', 'Tweets_Vader_Sentiment',
       'News_Vader_Sentiment', 'Price_Direction'],
      dtype='object', length=107)

In [7]:
# Creating lagged features for specified columns, assuming these columns exist
columns_to_lag = Base_ETH.columns 

for column in columns_to_lag:
    for lag in range(1, 6):  # Creating lags from 1 to 5 days
        Lag_ETH[f'{column}_lag_{lag}'] = Lag_ETH[column].shift(lag)

# Drop rows with NaN values created by shifting
Lag_ETH.dropna(inplace=True)

# Optionally, save the new dataset with lag features
Lag_ETH.to_csv('Ethereum/ETH_raw_Technical_plus_old_with_Lags.csv', index=False)

# Display the new DataFrame structure with lagged features
print(Lag_ETH.head())

          Date      Volume    Market Cap    volume_adi  volume_obv  \
10  2022-12-21  4217182733  148512923134  8.102317e+09 -2078678088
11  2022-12-20  6684951715  149015094982  1.332661e+10  4606273627
12  2022-12-19  4943628091  142884939549  1.057982e+10  -337354464
13  2022-12-18  3350092519  144978183336  1.040134e+10  3012738055
14  2022-12-17  5077258586  145398457166  1.509201e+10  8089996641

    volume_cmf     volume_fi  volume_em  volume_sma_em    volume_vpt  ...  \
10    0.182111  1.982126e+09   2.160714       0.271512  3.564710e+07  ...
11    0.260407  5.614437e+09 -15.285380      -1.142751  5.823140e+07  ...
12    0.188522 -3.056282e+10 -11.976332      -2.045549 -1.451244e+08  ...
13    0.174901 -1.800812e+10   4.599007      -1.534430 -9.603257e+07  ...
14    0.233814 -1.294767e+10  -3.710877      -1.689890 -8.133290e+07  ...

    News_Vader_Sentiment_lag_1  News_Vader_Sentiment_lag_2  \
10                   -0.033695                   -0.035277
11                    0.000846                   -0.033695
12                    0.011000                    0.000846
13                   -0.007025                    0.011000
14                    0.004755                   -0.007025

    News_Vader_Sentiment_lag_3  News_Vader_Sentiment_lag_4  \
10                   -0.115418                   -0.047619
11                   -0.035277                   -0.115418
12                   -0.033695                   -0.035277
13                    0.000846                   -0.033695
14                    0.011000                    0.000846

    News_Vader_Sentiment_lag_5  Price_Direction_lag_1  Price_Direction_lag_2  \
10                   -0.035239                    1.0                    1.0
11                   -0.047619                    0.0                    1.0
12                   -0.115418                    1.0                    0.0
13                   -0.035277                    0.0                    1.0
14                   -0.033695                    0.0                    0.0

    Price_Direction_lag_3  Price_Direction_lag_4  Price_Direction_lag_5
10                    1.0                    0.0                    1.0
11                    1.0                    1.0                    0.0
12                    1.0                    1.0                    1.0
13                    0.0                    1.0                    1.0
14                    1.0                    0.0                    1.0

[5 rows x 642 columns]

In [8]:
Lag_ETH

,Date,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,volume_em,volume_sma_em,volume_vpt,...,News_Vader_Sentiment_lag_1,News_Vader_Sentiment_lag_2,News_Vader_Sentiment_lag_3,News_Vader_Sentiment_lag_4,News_Vader_Sentiment_lag_5,Price_Direction_lag_1,Price_Direction_lag_2,Price_Direction_lag_3,Price_Direction_lag_4,Price_Direction_lag_5
10,2022-12-21,4217182733,148512923134,8.102317e+09,-2078678088,0.182111,1.982126e+09,2.160714,0.271512,3.564710e+07,...,-0.033695,-0.035277,-0.115418,-0.047619,-0.035239,1.0,1.0,1.0,0.0,1.0
11,2022-12-20,6684951715,149015094982,1.332661e+10,4606273627,0.260407,5.614437e+09,-15.285380,-1.142751,5.823140e+07,...,0.000846,-0.033695,-0.035277,-0.115418,-0.047619,0.0,1.0,1.0,1.0,0.0
12,2022-12-19,4943628091,142884939549,1.057982e+10,-337354464,0.188522,-3.056282e+10,-11.976332,-2.045549,-1.451244e+08,...,0.011000,0.000846,-0.033695,-0.035277,-0.115418,1.0,0.0,1.0,1.0,1.0
13,2022-12-18,3350092519,144978183336,1.040134e+10,3012738055,0.174901,-1.800812e+10,4.599007,-1.534430,-9.603257e+07,...,-0.007025,0.011000,0.000846,-0.033695,-0.035277,0.0,1.0,0.0,1.0,1.0
14,2022-12-17,5077258586,145398457166,1.509201e+10,8089996641,0.233814,-1.294767e+10,-3.710877,-1.689890,-8.133290e+07,...,0.004755,-0.007025,0.011000,0.000846,-0.033695,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2551,2016-01-05,219833,72240974,2.460530e+12,-1372918065031,0.197787,-9.471747e+04,0.113466,-0.276769,8.780225e+07,...,0.000000,0.127267,-0.050575,-0.050575,-0.050575,1.0,0.0,1.0,1.0,1.0
2552,2016-01-04,346245,72543707,2.460530e+12,-1372917718786,0.195874,-8.097371e+04,-0.073350,-0.298535,8.780381e+07,...,0.153550,0.000000,0.127267,-0.050575,-0.050575,0.0,1.0,0.0,1.0,1.0
2553,2016-01-03,407632,73843292,2.460530e+12,-1372917311154,0.051470,-6.839278e+04,0.136575,-0.171678,8.781125e+07,...,0.000000,0.153550,0.000000,0.127267,-0.050575,0.0,0.0,1.0,0.0,1.0
2554,2016-01-02,255504,71176658,2.460530e+12,-1372917566658,0.070587,-5.989260e+04,-0.125928,-0.168491,8.780210e+07,...,0.000000,0.000000,0.153550,0.000000,0.127267,1.0,0.0,0.0,1.0,0.0
2555,2016-01-01,206062,71980386,2.460530e+12,-1372917360596,0.065394,-5.101565e+04,-0.113558,-0.173315,8.780449e+07,...,0.000000,0.000000,0.000000,0.153550,0.000000,0.0,1.0,0.0,0.0,1.0

In [9]:
Lag_ETH['Date'] = pd.to_datetime(Lag_ETH['Date'])
Lag_ETH.set_index('Date', inplace=True)

In [10]:
Lag_ETH

,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,volume_em,volume_sma_em,volume_vpt,volume_vwap,...,News_Vader_Sentiment_lag_1,News_Vader_Sentiment_lag_2,News_Vader_Sentiment_lag_3,News_Vader_Sentiment_lag_4,News_Vader_Sentiment_lag_5,Price_Direction_lag_1,Price_Direction_lag_2,Price_Direction_lag_3,Price_Direction_lag_4,Price_Direction_lag_5
Date,,,,,,,,,,,,,,,,,,,,,
2022-12-21,4217182733,148512923134,8.102317e+09,-2078678088,0.182111,1.982126e+09,2.160714,0.271512,3.564710e+07,1209.323676,...,-0.033695,-0.035277,-0.115418,-0.047619,-0.035239,1.0,1.0,1.0,0.0,1.0
2022-12-20,6684951715,149015094982,1.332661e+10,4606273627,0.260407,5.614437e+09,-15.285380,-1.142751,5.823140e+07,1208.427533,...,0.000846,-0.033695,-0.035277,-0.115418,-0.047619,0.0,1.0,1.0,1.0,0.0
2022-12-19,4943628091,142884939549,1.057982e+10,-337354464,0.188522,-3.056282e+10,-11.976332,-2.045549,-1.451244e+08,1205.362776,...,0.011000,0.000846,-0.033695,-0.035277,-0.115418,1.0,0.0,1.0,1.0,1.0
2022-12-18,3350092519,144978183336,1.040134e+10,3012738055,0.174901,-1.800812e+10,4.599007,-1.534430,-9.603257e+07,1204.217939,...,-0.007025,0.011000,0.000846,-0.033695,-0.035277,0.0,1.0,0.0,1.0,1.0
2022-12-17,5077258586,145398457166,1.509201e+10,8089996641,0.233814,-1.294767e+10,-3.710877,-1.689890,-8.133290e+07,1202.562652,...,0.004755,-0.007025,0.011000,0.000846,-0.033695,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-05,219833,72240974,2.460530e+12,-1372918065031,0.197787,-9.471747e+04,0.113466,-0.276769,8.780225e+07,1.216191,...,0.000000,0.127267,-0.050575,-0.050575,-0.050575,1.0,0.0,1.0,1.0,1.0
2016-01-04,346245,72543707,2.460530e+12,-1372917718786,0.195874,-8.097371e+04,-0.073350,-0.298535,8.780381e+07,1.152925,...,0.153550,0.000000,0.127267,-0.050575,-0.050575,0.0,1.0,0.0,1.0,1.0
2016-01-03,407632,73843292,2.460530e+12,-1372917311154,0.051470,-6.839278e+04,0.136575,-0.171678,8.781125e+07,1.137279,...,0.000000,0.153550,0.000000,0.127267,-0.050575,0.0,0.0,1.0,0.0,1.0
2016-01-02,255504,71176658,2.460530e+12,-1372917566658,0.070587,-5.989260e+04,-0.125928,-0.168491,8.780210e+07,1.115236,...,0.000000,0.000000,0.153550,0.000000,0.127267,1.0,0.0,0.0,1.0,0.0
2016-01-01,206062,71980386,2.460530e+12,-1372917360596,0.065394,-5.101565e+04,-0.113558,-0.173315,8.780449e+07,1.065592,...,0.000000,0.000000,0.000000,0.153550,0.000000,0.0,1.0,0.0,0.0,1.0

In [11]:
import numpy as np
from pycaret.classification import *

# Initialize setup
exp_clf = setup(data=Lag_ETH, target='Price_Direction', session_id=123, normalize=True, transformation=True)

In [12]:
best_model = compare_models()

In [13]:
from pycaret.classification import tune_model

# Tune the best model
tuned_model = tune_model(best_model)

Fitting 10 folds for each of 10 candidates, totalling 100 fits

# Only previous price direction lags

In [2]:
Lag_ETH

,Date,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,volume_em,volume_sma_em,volume_vpt,...,Oil_Price,Nasdaq_Open,S&P500_Open,BTC_Open,BTC_Volume,BTC_Market_Cap,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Price_Direction
0,2022-12-31,3018513333,146453523490,-1.593797e+09,3018513333,-0.528007,0.000000e+00,0.000000,0.000000,0.000000e+00,...,75.89,10368.370117,3829.06,16603.670,1.123919e+10,3.185163e+11,35625,0.119512,-0.068864,0
1,2022-12-30,4055668253,146754748633,9.030692e+08,7074181586,0.127657,9.976944e+09,-1.760326,-1.760326,8.336559e+06,...,75.89,10368.370117,3829.06,16641.330,1.592916e+10,3.195595e+11,40485,0.095240,-0.024360,0
2,2022-12-29,4132233940,147043867255,3.705028e+09,11206415526,0.330617,9.950723e+09,0.574723,-0.592802,1.650296e+07,...,75.89,10321.459961,3805.45,16552.320,1.447224e+10,3.203093e+11,41316,0.099584,-0.052279,1
3,2022-12-28,4991669631,145623194889,2.747333e+08,6214745895,0.016961,2.501501e+08,1.739217,0.184538,-3.172714e+07,...,75.89,10339.200195,3829.56,16716.400,1.700571e+10,3.185671e+11,42534,0.084050,-0.066367,0
4,2022-12-27,4091530737,148414001604,-1.517397e+09,10306276632,-0.074787,1.354111e+10,11.233629,2.946811,4.666588e+07,...,75.89,10462.190430,3843.34,16919.290,1.574858e+10,3.217172e+11,39816,0.097602,-0.054126,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2551,2016-01-05,219833,72240974,2.460530e+12,-1372918065031,0.197787,-9.471747e+04,0.113466,-0.276769,8.780225e+07,...,35.97,4917.839844,2013.78,431.960,3.357784e+07,6.471942e+09,16689,0.182860,0.153550,0
2552,2016-01-04,346245,72543707,2.460530e+12,-1372917718786,0.195874,-8.097371e+04,-0.073350,-0.298535,8.780381e+07,...,36.76,4897.649902,2038.20,433.091,3.669657e+07,6.504166e+09,15821,0.181530,0.000000,0
2553,2016-01-03,407632,73843292,2.460530e+12,-1372917311154,0.051470,-6.839278e+04,0.136575,-0.171678,8.781125e+07,...,37.04,4897.649902,2038.20,430.011,3.715623e+07,6.494453e+09,13167,0.248901,0.000000,1
2554,2016-01-02,255504,71176658,2.460530e+12,-1372917566658,0.070587,-5.989260e+04,-0.125928,-0.168491,8.780210e+07,...,37.04,4897.649902,2038.20,433.438,3.117175e+07,6.461269e+09,13691,0.254835,0.000000,0
2555,2016-01-01,206062,71980386,2.460530e+12,-1372917360596,0.065394,-5.101565e+04,-0.113558,-0.173315,8.780449e+07,...,37.04,4897.649902,2038.20,434.334,3.173093e+07,6.521422e+09,13583,0.238774,0.000000,1

In [3]:
Lag_ETH['Date'] = pd.to_datetime(Lag_ETH['Date'])
Lag_ETH.set_index('Date', inplace=True)

In [5]:
for lag in range(1, 6):  # Creating lags from 1 to 5 days
        Lag_ETH[f'Price_Direction_lag_{lag}'] = Lag_ETH["Price_Direction"].shift(lag)

# Drop rows with NaN values created by shifting
Lag_ETH.dropna(inplace=True)

In [6]:
Lag_ETH

,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,volume_em,volume_sma_em,volume_vpt,volume_vwap,...,BTC_Market_Cap,Tweets_Count,Tweets_Vader_Sentiment,News_Vader_Sentiment,Price_Direction,Price_Direction_lag_1,Price_Direction_lag_2,Price_Direction_lag_3,Price_Direction_lag_4,Price_Direction_lag_5
Date,,,,,,,,,,,,,,,,,,,,,
2022-12-26,3282098400,150149593574,1.764701e+09,13588375032,0.074865,1.825526e+10,0.960113,2.549471,8.504033e+07,1204.061490,...,3.256043e+11,36179,0.093310,-0.035239,1,0.0,0.0,1.0,0.0,0.0
2022-12-25,3942720070,149169092950,3.891381e+09,9645654962,0.141431,1.113577e+10,-3.532916,1.535740,5.930116e+07,1205.686258,...,3.240932e+11,30277,0.118710,-0.047619,0,1.0,0.0,0.0,1.0,0.0
2022-12-24,2626153345,149436675609,4.213138e+09,12271808307,0.139783,1.036656e+10,2.285961,1.642914,6.401935e+07,1207.003120,...,3.241902e+11,31346,0.104037,-0.115418,1,0.0,1.0,0.0,0.0,1.0
2022-12-23,4835831923,149315624697,3.040416e+09,7435976384,0.086928,8.201695e+09,0.198078,1.462310,6.009888e+07,1208.945239,...,3.232031e+11,38289,0.095745,-0.035277,1,1.0,0.0,1.0,0.0,0.0
2022-12-22,5297471739,149073659685,7.179920e+09,2138504645,0.178277,5.531597e+09,-11.144073,0.061601,5.150247e+07,1208.965595,...,3.238314e+11,41898,0.092558,-0.033695,1,1.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-05,219833,72240974,2.460530e+12,-1372918065031,0.197787,-9.471747e+04,0.113466,-0.276769,8.780225e+07,1.216191,...,6.471942e+09,16689,0.182860,0.153550,0,1.0,0.0,1.0,1.0,1.0
2016-01-04,346245,72543707,2.460530e+12,-1372917718786,0.195874,-8.097371e+04,-0.073350,-0.298535,8.780381e+07,1.152925,...,6.504166e+09,15821,0.181530,0.000000,0,0.0,1.0,0.0,1.0,1.0
2016-01-03,407632,73843292,2.460530e+12,-1372917311154,0.051470,-6.839278e+04,0.136575,-0.171678,8.781125e+07,1.137279,...,6.494453e+09,13167,0.248901,0.000000,1,0.0,0.0,1.0,0.0,1.0
2016-01-02,255504,71176658,2.460530e+12,-1372917566658,0.070587,-5.989260e+04,-0.125928,-0.168491,8.780210e+07,1.115236,...,6.461269e+09,13691,0.254835,0.000000,0,1.0,0.0,0.0,1.0,0.0
2016-01-01,206062,71980386,2.460530e+12,-1372917360596,0.065394,-5.101565e+04,-0.113558,-0.173315,8.780449e+07,1.065592,...,6.521422e+09,13583,0.238774,0.000000,1,0.0,1.0,0.0,0.0,1.0

In [7]:
import numpy as np
from pycaret.classification import *

# Initialize setup
exp_clf = setup(data=Lag_ETH, target='Price_Direction', session_id=123, normalize=True, transformation=True)

In [8]:
best_model = compare_models()

In [9]:
from pycaret.classification import tune_model

# Tune the best model
tuned_model = tune_model(best_model)

Fitting 10 folds for each of 10 candidates, totalling 100 fits

# Technical with price Lags

# Percentage difference

In [78]:
Base_ETH

,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,volume_em,volume_sma_em,volume_vpt,volume_vwap,...,others_dlr,others_cr,rsi,macd,macd_signal,macd_diff,bb_bbm,bb_bbh,bb_bbl,Price_Direction
Date,,,,,,,,,,,,,,,,,,,,,
2022-12-31,3018513333,146453523490,-1.593797e+09,3018513333,-0.528007,0.000000e+00,0.000000,0.000000,0.000000e+00,1198.686667,...,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,1196.770000,1196.770000,1196.770000,0
2022-12-30,4055668253,146754748633,9.030692e+08,7074181586,0.127657,9.976944e+09,-1.760326,-1.760326,8.336559e+06,1197.283979,...,0.205342,0.205553,100.000000,0.196239,0.039248,0.156991,1198.000000,1200.460000,1195.540000,0
2022-12-29,4132233940,147043867255,3.705028e+09,11206415526,0.330617,9.950723e+09,0.574723,-0.592802,1.650296e+07,1197.560295,...,0.197432,0.403586,100.000000,0.536812,0.138761,0.398051,1199.200000,1203.143907,1195.256093,1
2022-12-28,4991669631,145623194889,2.747333e+08,6214745895,0.016961,2.501501e+08,1.739217,0.184538,-3.172714e+07,1197.163699,...,-0.970910,-0.566525,27.127046,-0.128630,0.085283,-0.213912,1196.897500,1205.574128,1188.220872,0
2022-12-27,4091530737,148414001604,-1.517397e+09,10306276632,-0.074787,1.354111e+10,11.233629,2.946811,4.666588e+07,1201.036772,...,1.897859,1.338603,71.323196,1.170282,0.302283,0.868000,1200.076000,1214.971398,1185.180602,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-05,219833,72240974,2.460530e+12,-1372918065031,0.197787,-9.471747e+04,0.113466,-0.276769,8.780225e+07,1.216191,...,-0.073642,-99.920603,23.222015,-0.573078,-0.675665,0.102587,1.279295,1.930723,0.627867,0
2016-01-04,346245,72543707,2.460530e+12,-1372917718786,0.195874,-8.097371e+04,-0.073350,-0.298535,8.780381e+07,1.152925,...,0.451515,-99.920244,23.443580,-0.543918,-0.649316,0.105398,1.220020,1.752223,0.687817,0
2016-01-03,407632,73843292,2.460530e+12,-1372917311154,0.051470,-6.839278e+04,0.136575,-0.171678,8.781125e+07,1.137279,...,1.806528,-99.918790,24.394372,-0.513486,-0.622150,0.108664,1.170115,1.586163,0.754067,1
2016-01-02,255504,71176658,2.460530e+12,-1372917566658,0.070587,-5.989260e+04,-0.125928,-0.168491,8.780210e+07,1.115236,...,-3.646292,-99.921698,23.758831,-0.486567,-0.595033,0.108466,1.141970,1.540746,0.743194,0
2016-01-01,206062,71980386,2.460530e+12,-1372917360596,0.065394,-5.101565e+04,-0.113558,-0.173315,8.780449e+07,1.065592,...,1.156450,-99.920787,24.422995,-0.459062,-0.567839,0.108777,1.111870,1.471905,0.751835,1

In [83]:
columns_to_change = Base_ETH.columns.drop(['Price_Direction'])

# Create a new DataFrame for percentage changes
df_pct_change = Base_ETH[columns_to_change].pct_change() * 100

# If you want to add the 'Date' column to this new DataFrame
# df_pct_change['Date'] = Base_ETH['Date']

# Rearrange to move 'Date' to the first column if needed
# df_pct_change = df_pct_change[['Date'] + [col for col in df_pct_change.columns if col != 'Date']]

df_pct_change["Price_Direction"]=Base_ETH["Price_Direction"]

In [84]:
df_pct_change

,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,volume_em,volume_sma_em,volume_vpt,volume_vwap,...,others_dlr,others_cr,rsi,macd,macd_signal,macd_diff,bb_bbm,bb_bbh,bb_bbl,Price_Direction
Date,,,,,,,,,,,,,,,,,,,,,
2022-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2022-12-30,34.359793,0.205680,-1.566615e+02,134.359793,-124.177138,inf,-inf,-inf,inf,-0.117019,...,inf,inf,0.000000,inf,inf,inf,0.102777,0.308330,-0.102777,0
2022-12-29,1.887869,0.197008,3.102706e+02,58.412890,158.988143,-0.262819,-132.648662,-66.324331,97.958906,0.023079,...,-3.852359,96.341463,0.000000,173.549441,253.549441,153.549441,0.100167,0.223573,-0.023747,1
2022-12-28,20.798331,-0.966155,-9.258485e+01,-44.542964,-94.869934,-97.486111,202.618232,-131.129761,-292.251166,-0.033117,...,-591.769766,-240.372671,-72.872954,-123.961799,-38.539802,-153.739916,-0.192003,0.201989,-0.588595,0
2022-12-27,-18.032822,1.916458,-6.523164e+02,65.835849,-540.938273,5313.195146,545.901666,1496.860582,-247.085061,0.323521,...,-295.472187,-336.283186,162.922822,-1009.807312,254.448316,-505.773845,0.265562,0.779485,-0.255867,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-05,-28.808482,-0.105335,-6.191040e-06,0.000016,-21.790451,-14.265816,-300.212455,-15.789598,-0.000184,-1.678797,...,-107.831186,0.000059,-0.043749,-4.728822,-3.656974,2.804065,-5.711295,-11.410536,17.541697,0
2016-01-04,57.503650,0.419060,8.455260e-07,-0.000025,-0.967157,-14.510270,-164.644920,7.864105,0.001785,-5.201999,...,-713.125690,-0.000360,0.954118,-5.088269,-3.899770,2.739486,-4.633411,-9.245245,9.548202,0
2016-01-03,17.729353,1.791451,5.251484e-06,-0.000030,-73.723187,-15.537055,-286.197372,-42.493008,0.008463,-1.357028,...,300.103157,-0.001455,4.055656,-5.595049,-4.183790,3.099201,-4.090507,-9.477060,9.631800,1
2016-01-02,-37.319936,-3.611207,-1.006943e-05,0.000019,37.143323,-12.428472,-192.203710,-1.856536,-0.010419,-1.938286,...,-301.839815,0.002910,-2.605275,-5.242354,-4.358525,-0.182043,-2.405319,-2.863366,-1.441826,0
2016-01-01,-19.350773,1.129202,3.507353e-06,-0.000015,-7.357522,-14.821453,-9.822728,2.862751,0.002730,-4.451401,...,-131.715789,-0.000911,2.795440,-5.652792,-4.570193,0.286220,-2.635796,-4.468012,1.162644,1

In [81]:
# df_pct_change.dropna(inplace=True,axis=1)

In [85]:
df_pct_change

,Volume,Market Cap,volume_adi,volume_obv,volume_cmf,volume_fi,volume_em,volume_sma_em,volume_vpt,volume_vwap,...,others_dlr,others_cr,rsi,macd,macd_signal,macd_diff,bb_bbm,bb_bbh,bb_bbl,Price_Direction
Date,,,,,,,,,,,,,,,,,,,,,
2022-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2022-12-30,34.359793,0.205680,-1.566615e+02,134.359793,-124.177138,inf,-inf,-inf,inf,-0.117019,...,inf,inf,0.000000,inf,inf,inf,0.102777,0.308330,-0.102777,0
2022-12-29,1.887869,0.197008,3.102706e+02,58.412890,158.988143,-0.262819,-132.648662,-66.324331,97.958906,0.023079,...,-3.852359,96.341463,0.000000,173.549441,253.549441,153.549441,0.100167,0.223573,-0.023747,1
2022-12-28,20.798331,-0.966155,-9.258485e+01,-44.542964,-94.869934,-97.486111,202.618232,-131.129761,-292.251166,-0.033117,...,-591.769766,-240.372671,-72.872954,-123.961799,-38.539802,-153.739916,-0.192003,0.201989,-0.588595,0
2022-12-27,-18.032822,1.916458,-6.523164e+02,65.835849,-540.938273,5313.195146,545.901666,1496.860582,-247.085061,0.323521,...,-295.472187,-336.283186,162.922822,-1009.807312,254.448316,-505.773845,0.265562,0.779485,-0.255867,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-05,-28.808482,-0.105335,-6.191040e-06,0.000016,-21.790451,-14.265816,-300.212455,-15.789598,-0.000184,-1.678797,...,-107.831186,0.000059,-0.043749,-4.728822,-3.656974,2.804065,-5.711295,-11.410536,17.541697,0
2016-01-04,57.503650,0.419060,8.455260e-07,-0.000025,-0.967157,-14.510270,-164.644920,7.864105,0.001785,-5.201999,...,-713.125690,-0.000360,0.954118,-5.088269,-3.899770,2.739486,-4.633411,-9.245245,9.548202,0
2016-01-03,17.729353,1.791451,5.251484e-06,-0.000030,-73.723187,-15.537055,-286.197372,-42.493008,0.008463,-1.357028,...,300.103157,-0.001455,4.055656,-5.595049,-4.183790,3.099201,-4.090507,-9.477060,9.631800,1
2016-01-02,-37.319936,-3.611207,-1.006943e-05,0.000019,37.143323,-12.428472,-192.203710,-1.856536,-0.010419,-1.938286,...,-301.839815,0.002910,-2.605275,-5.242354,-4.358525,-0.182043,-2.405319,-2.863366,-1.441826,0
2016-01-01,-19.350773,1.129202,3.507353e-06,-0.000015,-7.357522,-14.821453,-9.822728,2.862751,0.002730,-4.451401,...,-131.715789,-0.000911,2.795440,-5.652792,-4.570193,0.286220,-2.635796,-4.468012,1.162644,1

# Exploration After Base result

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Load the dataset
df = pd.read_csv('../Experiment_sets/Ethereum/Ethereum_final_dataset.csv')

df['Date'] = pd.to_datetime(df['Date'])
df.set_index('Date', inplace=True)